//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.17 at 10:11:05 AM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.bestwrostreturn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"bestReturn", "worstReturn"})
@XmlRootElement(name = "api")
public class Api {

    @XmlElement(name = "BestReturn", required = true)
    protected BestReturn bestReturn;
    @XmlElement(name = "WorstReturn", required = true)
    protected WorstReturn worstReturn;
    @XmlAttribute(name = "_name")
    protected String name;

    
    public BestReturn getBestReturn() {
        return this.bestReturn;
    }

    
    public void setBestReturn(final BestReturn value) {
        this.bestReturn = value;
    }

    
    public WorstReturn getWorstReturn() {
        return this.worstReturn;
    }

    
    public void setWorstReturn(final WorstReturn value) {
        this.worstReturn = value;
    }

    
    public String getName() {
        return this.name;
    }

    
    public void setName(final String value) {
        this.name = value;
    }

}
