//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.01.13 at 02:58:33 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.bestwrostreturn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "WorstReturn")
public class WorstReturn {

    @XmlAttribute(name = "startdate")
    protected String startdate;
    @XmlAttribute(name = "v")
    protected String v;
    @XmlAttribute(name = "enddate")
    protected String enddate;


    public String getStartdate() {
        return this.startdate;
    }


    public void setStartdate(final String value) {
        this.startdate = value;
    }


    public String getV() {
        return this.v;
    }


    public void setV(final String value) {
        this.v = value;
    }


    public String getEnddate() {
        return this.enddate;
    }


    public void setEnddate(final String value) {
        this.enddate = value;
    }

}
