spring:
  datasource:
    url: jdbc:postgresql://amh-dev-wppostgresql01.wealth-platform-amh.dev.aws.cloud.dummy:5432/productdb
    username: ocushkd_appuser
    password: "{cipher}49d32290d0d44c4eee0d3a2f86559a2c7ee50bfb9d42710db9bf1660d27c235b51bc31f0b2b0d047d4d50d331b3aa52c"
    driver-class-name: org.postgresql.Driver
batch:
  graphQLUrl: "https://product-graphql-b-debug.uat.wealth-platform-amh.ape1.dev.aws.cloud.dummy/graphql"
  file:
    pattern: ^{ctryRecCde}_{grpMembrRecCde}_{systemCde}_TradingEligibility_(\d{14})\.[Xx][Mm][Ll]$
  size: 100

system-default-values:
  - systemCde: "AMHGSOPS.CE"
    defaultValues:
      "[tradeElig.ovridCuspCatEligInd]": "Y"
      "[tradeElig.reqCmplRpqInd]": "N"
      "[tradeElig.ovridReqCmplRpqInd]": "Y"
      "[tradeElig.ovridReqFormInd]": "Y"
      "[tradeElig.ageAllowTrdMinNum]": 18
      "[tradeElig.ovridMinAgeRestrInd]": "N"
      "[tradeElig.ovridMaxAgeRestrInd]": "Y"
      "[tradeElig.operTypeCde]": "T"
      "[tradeElig.ovridCorsCtryChkInd]": "Y"
      "[tradeElig.ovridResCtryChkInd]": "Y"
      "[tradeElig.ovridNatlChkInd]": "Y"

system-update-config:
  - systemCde: "AMHGSOPS.CE"
    config:
      - collection: product
        updateAttrs:
          - "tradeElig.ageAllowTrdMaxNum"
          - "tradeElig.ovridMinAgeRestrInd"
          - "tradeElig.ovridMaxAgeRestrIn"
          - "tradeElig.ovridCorsCtryChkInd"
          - "tradeElig.ovridResCtryChkInd"
          - "tradeElig.ovridNatlChkInd"
          - "restrCustGroup"
          - "formReqmt"
          - "restrCustCtry"
          - "udf"
