spring:
  datasource:
    url: "jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = wp-rds.wealth-platform-uk.euw1.dev.aws.cloud.dummy)(PORT = 1521)))(CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = DUKWP01)))"
    username: WPCGLGBPA5
    password: WPCGLGBPA5.123
  data:
    mongodb:
      port: 27017
      host: localhost
      database: WPC_UK_DEV

product:
  sync:
    interval: 60   # 60 seconds by default
    auto-watch: false

server:
  port: 8088