productTables:
  TB_PROD:
    - "CTRY_REC_CDE"
    - "GRP_MEMBR_REC_CDE"
    - "PROD_ID"
    - "PROD_TYPE"
    - "PROD_TYPE_CDE"
    - "PROD_SUBTP_CDE"
    - "PROD_CDE"
    - "PROD_ALT_PRIM_NUM"
    - "PROD_NAME"
    - "PROD_PLL_NAME"
    - "PROD_SLL_NAME"
    - "PROD_SHRT_NAME"
    - "PROD_SHRT_PLL_NAME"
    - "PROD_SHRT_SLL_NAME"
    - "PROD_DESC"
    - "PROD_PLL_DESC"
    - "PROD_SLL_DESC"
    - "ASET_CLASS_CDE"
    - "PROD_STAT_CDE"
    - "CCY_PROD_CDE"
    - "RISK_LVL_CDE"
    - "PRD_PROD_CDE"
    - "PRD_PROD_NUM"
    - "TERM_REMAIN_DAY_CNT"
    - "PROD_LNCH_DT"
    - "PROD_MTUR_DT"
    - "MKT_INVST_CDE"
    - "SECT_INVST_CDE"
    - "ALLOW_BUY_PROD_IND"
    - "ALLOW_SELL_PROD_IND"
    - "ALLOW_BUY_UT_PROD_IND"
    - "ALLOW_BUY_AMT_PROD_IND"
    - "ALLOW_SELL_UT_PROD_IND"
    - "ALLOW_SELL_AMT_PROD_IND"
    - "ALLOW_SELL_MIP_PROD_IND"
    - "ALLOW_SELL_MIP_UT_PROD_IND"
    - "ALLOW_SELL_MIP_AMT_PROD_IND"
    - "ALLOW_SW_IN_PROD_IND"
    - "ALLOW_SW_IN_UT_PROD_IND"
    - "ALLOW_SW_IN_AMT_PROD_IND"
    - "ALLOW_SW_OUT_PROD_IND"
    - "ALLOW_SW_OUT_UT_PROD_IND"
    - "ALLOW_SW_OUT_AMT_PROD_IND"
    - "INCM_CHAR_PROD_IND"
    - "CPTL_GURNT_PROD_IND"
    - "YIELD_ENHN_PROD_IND"
    - "GRWTH_CHAR_PROD_IND"
    - "PRTY_PROD_SRCH_RSULT_NUM"
    - "AVAIL_MKT_INFO_IND"
    - "PRD_RTRN_AVG_NUM"
    - "RTRN_VOLTL_AVG_PCT"
    - "DMY_PROD_SUBTP_REC_IND"
    - "DISP_COM_PROD_SRCH_IND"
    - "MRK_TO_MKT_IND"
    - "PROD_NARR_TEXT"
    - "CTRY_PROD_TRADE_1_CDE"
    - "CTRY_PROD_TRADE_2_CDE"
    - "CTRY_PROD_TRADE_3_CDE"
    - "CTRY_PROD_TRADE_4_CDE"
    - "CTRY_PROD_TRADE_5_CDE"
    - "BUS_START_TM"
    - "BUS_END_TM"
    - "INTRO_PROD_CURR_PRD_IND"
    - "PROD_TOP_SELL_RANK_NUM"
    - "PROD_TOP_PERFM_RANK_NUM"
    - "PROD_TOP_YIELD_RANK_NUM"
    - "PROD_ISSUE_CROS_REFER_DT"
    - "PROD_CMNT_TEXT"
    - "CCY_INVST_CDE"
    - "BCHMK_NAME"
    - "BCHMK_PLL_NAME"
    - "BCHMK_SLL_NAME"
    - "TRD_FIRST_DT"
    - "LOAN_PROD_OD_MRGN_PCT"
    - "QTY_UNIT_PROD_CDE"
    - "PROD_LOC_CDE"
    - "PROD_TAX_FREE_WRAP_ACT_STA_CDE"
    - "PRC_EFF_DT"
    - "CCY_PROD_MKT_PRC_CDE"
    - "PROD_BID_PRC_AMT"
    - "PROD_OFFR_PRC_AMT"
    - "PROD_MKT_PRC_AMT"
    - "PROD_NAV_PRC_AMT"
    - "PROD_PRC_UPDT_DT_TM"
    - "DCML_PLACE_TRADE_UNIT_NUM"
    - "PROD_OFFR_CHANL_UPDT_DT_TM"
    - "PLDG_LIMIT_ASSOC_ACCT_IND"
    - "PROD_OWN_CDE"
    - "FORGN_PROD_IND"
    - "PROD_STAT_UPDT_DT_TM"
    - "ASET_CAT_EXTNL_CDE"
    - "PROD_MKT_PRICE_PREV_AMT"
    - "REC_CREAT_DT_TM"
    - "REC_UPDT_DT_TM"
    - "REC_ONLN_UPDT_DT_TM"
    - "PRC_INP_DT"
    - "CHRG_CAT_CDE"
    - "SUPT_RCBL_CASH_PROD_IND"
    - "SUPT_RCBL_SCRIP_PROD_IND"
    - "ASET_UNDER_MGMT_CHRG_PROD_IND"
    - "INVST_IMIG_PROD_IND"
    - "RESTR_INVSTR_PROD_IND"
    - "PROD_INVST_OBJ_TEXT"
    - "INVST_INIT_MIN_AMT"
    - "NO_SCRIB_FEE_PROD_IND"
    - "TOP_SELL_PROD_IND"
    - "TOP_PERFM_PROD_IND"
    - "INVST_INIT_MAX_AMT"
    - "RCMND_PROD_DECSN_CDE"
    - "ASET_TEXT"
    - "PROD_DERVT_CDE"
    - "PROD_DERVT_RVS_CDE"
    - "PRD_DERV_RVS_EFF_DT"
    - "EQTY_UNDL_IND"
    - "WLTH_ACCUM_GOAL_IND"
    - "PRTY_WLTH_ACCUM_GOAL_CDE"
    - "PLAN_FOR_RTIRE_GOAL_IND"
    - "PRTY_PLN_FOR_RTIRE_CDE"
    - "EDUC_GOAL_IND"
    - "PRTY_EDUC_CDE"
    - "LIVE_IN_RTIRE_GOAL_IND"
    - "PRTY_LIVE_IN_RTIRE_CDE"
    - "PROTC_GOAL_IND"
    - "PRTY_PROTC_CDE"
    - "MNG_SOLN_IND"
    - "PRD_INVST_TNOR_NUM"
    - "GEO_RISK_IND"
    - "PROD_LQDY_IND"
    - "RVRSE_ENQ_PROD_IND"
    - "PROD_INVST_TYPE_CDE"
    - "DIVR_NUM"
    - "PRICE_HIST_SRCE_RDY_STAT_CDE"
    - "PRICE_HIST_DELVR_DT_TM"
    - "ISLM_PROD_IND"
    - "CNTL_ADVC_IND"
    - "ASET_VOLTL_CLASS_MAJR_PRNT_CDE"
    - "REC_STGC_FIN_PLN_UPDT_DT_TM"
    - "PROD_PARNT_ID"

  TB_PROD_ALT_ID:
    - "CTRY_REC_CDE"
    - "GRP_MEMBR_REC_CDE"
    - "PROD_ID"
    - "PROD_CDE_ALT_CLASS_CDE"
    - "PROD_TYPE_CDE"
    - "PROD_ALT_NUM"
    - "REC_CREAT_DT_TM"
    - "REC_UPDT_DT_TM"

  TB_STOCK_INSTM:
    - "PROD_ID_STOCK_INSTM"
    - "PROD_PRC_CHNG_PCT"
    - "PROD_PRC_CHNG_AMT"
    - "PROD_OPEN_PRC_AMT"
    - "PROD_TDY_HIGH_PRC_AMT"
    - "PROD_TDY_LOW_PRC_AMT"
    - "SHARE_TRD_CNT"
    - "PROD_TRNVR_AMT"
    - "PROD_PRC_52_WEEK_MAX_AMT"
    - "PROD_PRC_52_WEEK_MIN_AMT"
    - "PRC_EARN_RATE"
    - "EARN_PER_SHARE_ANNL_AMT"
    - "DIV_PCT"
    - "MRGN_TRD_IND"
    - "MRGN_SEC_OD_PCT"
    - "SUPT_AUCTN_TRD_IND"
    - "STOP_LOSS_MIN_PCT"
    - "STOP_LOSS_MAX_PCT"
    - "SPRD_STOP_LOSS_MIN_CNT"
    - "SPRD_STOP_LOSS_MAX_CNT"
    - "PROD_BOD_LOT_QTY_CNT"
    - "MKT_PROD_TRD_CDE"
    - "SUPT_MIP_IND"
    - "INVST_MIP_MIN_AMT"
    - "INVST_MIP_INCRM_MIN_AMT"
    - "PROD_ISS_QTY_TTL_CNT"
    - "BOD_LOT_PROD_IND"
    - "TRD_LIMIT_IND"
    - "PROD_MAX_INDV_OWNR_PCT"
    - "PROD_MAX_INDV_FORGN_INVSTR_PCT"
    - "PROD_MAX_FORGN_INVSTR_TTL_PCT"
    - "PROD_EXER_PRC_AMT"
    - "PSBL_PROD_BORW_IND"
    - "ALLW_PROD_LEND_IND"
    - "POOL_PROD_IND"
    - "SCRIP_ONLY_PROD_IND"
    - "SUPT_ATMC_TRD_IND"
    - "SUPT_NET_SETL_IND"
    - "SUPT_STOP_LOSS_ORD_IND"
    - "SUPT_WIN_WIN_ORD_IND"
    - "SUPT_ALL_IN_1_ORD_IND"
    - "SUPT_PROD_SPLT_IND"
    - "MRGN_PRC_AUCTN_TRD_PCT"
    - "PROD_AUCTN_TRD_EXPIR_DT"
    - "LOAN_PROD_MRGN_TRD_PCT"
    - "LOAN_BDGT_PROD_IPO_AMT"
    - "LOAN_PROD_IPO_TTL_AMT"
    - "EXCL_LIMIT_CALC_IND"
    - "PROD_MKT_STAT_CHNG_LA_DT"
    - "PRC_VAR_CDE"
    - "METH_CALC_SCRIP_CHRG_CDE"
    - "PROD_SELL_MAX_QTY_CNT"
    - "PROD_BUY_MAX_QTY_CNT"
    - "PRC_VAR_MIN_AMT"
    - "PRC_VAR_MIN_EFF_DT"
    - "MKT_SEG_EXCHG_CDE"
    - "CTRY_PROD_REGIS_CDE"
    - "MKT_PROC_LAST_CDE"

  TB_DEBT_INSTM:
    - "PROD_ID_DEBT_INSTM"
    - "ISR_BOND_NAME"
    - "ISSUE_NUM"
    - "PROD_ISS_DT"
    - "PDCY_COUPN_PYMT_CDE"
    - "COUPN_ANNL_RATE"
    - "COUPN_EXT_INSTM_RATE"
    - "PYMT_COUPN_NEXT_DT"
    - "FLEX_MAT_OPT_IND"
    - "INT_IND_ACCR_AMT"
    - "INVST_INCRM_MIN_AMT"
    - "PROD_BOD_LOT_QTY_CNT"
    - "MTUR_EXT_DT"
    - "SUB_DEBT_IND"
    - "BOND_STAT_CDE"
    - "CTRY_BOND_ISSUE_CDE"
    - "GRNTR_NAME"
    - "CPTL_TIER_TEXT"
    - "COUPN_TYPE"
    - "COUPN_PREV_RATE"
    - "INDEX_FLT_RATE_NAME"
    - "BOND_FLT_SPRD_RATE"
    - "COUPN_CURR_START_DT"
    - "COUPN_PREV_START_DT"
    - "BOND_CALL_NEXT_DT"
    - "INT_BASIS_CALC_TEXT"
    - "INT_ACCR_DAY_CNT"
    - "INVST_SOLD_LEST_AMT"
    - "INVST_INCRM_SOLD_AMT"
    - "SHR_BID_CNT"
    - "SHR_OFFR_CNT"
    - "PROD_CLOSE_BID_PRC_AMT"
    - "PROD_CLOSE_OFFR_PRC_AMT"
    - "BOND_CLOSE_DT"
    - "BOND_SETL_DT"
    - "DSCNT_MRGN_BSEL_PCT"
    - "DSCNT_MRGN_BBUY_PCT"
    - "PRC_BOND_RECV_DT_TM"
    - "YIELD_OFFER_TEXT"
    - "COUPN_ANNL_TEXT"
    - "YIELD_EFF_DT"
    - "YIELD_BID_PCT"
    - "YIELD_TO_CALL_BID_PCT"
    - "YIELD_TO_MTUR_BID_PCT"
    - "YIELD_BID_CLOSE_PCT"
    - "YIELD_OFFER_PCT"
    - "YIELD_TO_CALL_OFFER_PCT"
    - "YIELD_TO_MTUR_OFFER_TEXT"
    - "YIELD_OFFER_CLOSE_PCT"
    - "YIELD_DT"
    - "ISR_DESC"
    - "SR_TYPE_CDE"

  TB_DEBT_INSTM_CRED_RTNG:
    - "PROD_ID_DEBT_INSTM"
    - "CREDIT_RTNG_AGCY_CDE"
    - "CREDIT_RTNG_CDE"
    - "REC_CREAT_DT_TM"
    - "REC_UPDT_DT_TM"

  TB_EQTY_LINK_INVST:
    - "PROD_ID_EQTY_LINK_INVST"
    - "PROD_EXTNL_CDE"
    - "PROD_EXTNL_TYPE_CDE"
    - "EQTY_LINK_INVST_TYPE_CDE"
    - "TRD_DT"
    - "DSCNT_BUY_PCT"
    - "DSCNT_SELL_PCT"
    - "YIELD_TO_MTUR_PCT"
    - "DEN_AMT"
    - "TRD_MIN_AMT"
    - "SUPT_AON_IND"
    - "PYMT_DT"
    - "VALN_DT"
    - "OFFER_TYPE_CDE"
    - "CUST_SELL_QTA_CNT"
    - "RULE_QTA_ALTMT_CDE"
    - "SETL_DT"
    - "LNCH_PROD_IND"
    - "RTRV_PROD_EXTNL_IND"
    - "PROD_EXTNL_CAT_CDE"
    - "PDCY_CALL_CDE"
    - "PDCY_KNOCK_IN_CDE"

  TB_STRUC_INVST_DEPST:
    - "PROD_ID_STRUC_INVST_DEPST"
    - "PROD_EXTNL_CDE"
    - "PROD_EXTNL_TYPE_CDE"
    - "PROD_CONV_CDE"
    - "RTRN_INTRM_PREV_PCT"
    - "RTRN_INTRM_PAID_PREV_DT"
    - "RTRN_INTRM_PAID_NEXT_DT"
    - "CCY_LINK_DEPST_CDE"
    - "MKT_START_DT"
    - "MKT_END_DT"
    - "YIELD_ANNL_MIN_PCT"
    - "YIELD_ANNL_POTEN_PCT"
    - "ALLOW_EARLY_RDM_IND"
    - "RDM_EARLY_DALW_TEXT"
    - "PRC_EARLY_RDM_PCT"
    - "RDM_EARLY_IND_AMT"
    - "OFFER_TYPE_CDE"
    - "CUST_SELL_QTA_NUM"
    - "RULE_QTA_ALTMT_CDE"
    - "BONUS_INT_CALC_TYPE_CDE"
    - "BONUS_INT_DT_TYPE_CDE"
    - "CPTL_PROTC_PCT"
    - "LNCH_PROD_IND"
    - "RTRV_PROD_EXTNL_IND"

  TB_UT_TRST_INSTM:
    - "PROD_ID_UT_TRST_INSTM"
    - "FUND_HOUSE_CDE"
    - "CLOSE_END_FUND_IND"
    - "UT_PRC_PROD_LNCH_AMT"
    - "FUND_AMT"
    - "INVST_INCRM_MIN_AMT"
    - "UT_RDM_MIN_NUM"
    - "RDM_MIN_AMT"
    - "UT_RTAIN_MIN_NUM"
    - "FUND_RTAIN_MIN_AMT"
    - "SUPT_MIP_IND"
    - "INVST_MIP_MIN_AMT"
    - "INVST_MIP_INCRM_MIN_AMT"
    - "UT_MIP_RDM_MIN_NUM"
    - "RDM_MIP_MIN_AMT"
    - "UT_MIP_RTAIN_MIN_NUM"
    - "FUND_MIP_RTAIN_MIN_AMT"
    - "RTRN_GURNT_PCT"
    - "SCHEM_CHRG_CDE"
    - "CHRG_INIT_SALES_PCT"
    - "CHRG_FUND_SW_PCT"
    - "DSCNT_MAX_PCT"
    - "OFFER_START_DT_TM"
    - "OFFER_END_DT_TM"
    - "PAY_CASH_DIV_IND"
    - "HLDAY_FUND_NEXT_DT"
    - "SCRIB_CTOFF_NEXT_DT_TM"
    - "RDM_CTOFF_NEXT_DT_TM"
    - "DEAL_NEXT_DT"
    - "FUND_CLASS_CDE"
    - "AMCM_IND"
    - "DIV_DCLR_DT"
    - "DIV_PYMT_DT"
    - "AUTO_SWEEP_FUND_IND"
    - "SPCL_FUND_IND"
    - "INSU_LINK_UT_TRST_IND"
    - "PROD_TRMT_DT"
    - "FUND_SW_IN_MIN_AMT"
    - "FUND_SW_OUT_MIN_AMT"
    - "FUND_SW_OUT_RTAIN_MIN_AMT"
    - "UT_SW_OUT_RTAIN_MIN_NUM"
    - "FUND_SW_OUT_MAX_AMT"
    - "TRAN_MAX_AMT"
    - "INCM_HANDL_OPT_CDE"
    - "AUTO_RENEW_FUND_IND"
    - "FUND_VALN_TM"
    - "PROD_SHORE_LOC_CDE"
    - "DIV_YIELD_PCT"

  TB_PROD_USER_DEFIN_EXT_FIELD:
    - "PROD_ID"
    - "FIELD_TYPE_CDE"
    - "FIELD_CDE"
    - "FIELD_SEQ_NUM"
    - "CTRY_REC_CDE"
    - "GRP_MEMBR_REC_CDE"
    - "FIELD_DATA_TYPE_TEXT"
    - "FIELD_CHAR_VALUE_TEXT"
    - "FIELD_STRNG_VALUE_TEXT"
    - "FIELD_INTG_VALUE_NUM"
    - "FIELD_DCML_VALUE_NUM"
    - "FIELD_DT_VALUE_DT"
    - "FIELD_TS_VALUE_DT_TM"
    - "REC_CREAT_DT_TM"
    - "REC_UPDT_DT_TM"

  TB_PROD_USER_DEFIN_EG_EXT_FIEL:
    - "PROD_ID"
    - "FIELD_TYPE_CDE"
    - "FIELD_CDE"
    - "FIELD_SEQ_NUM"
    - "CTRY_REC_CDE"
    - "GRP_MEMBR_REC_CDE"
    - "FIELD_DATA_TYPE_TEXT"
    - "FIELD_CHAR_VALUE_TEXT"
    - "FIELD_STRNG_VALUE_TEXT"
    - "FIELD_INTG_VALUE_NUM"
    - "FIELD_DCML_VALUE_NUM"
    - "FIELD_DT_VALUE_DT"
    - "FIELD_TS_VALUE_DT_TM"
    - "REC_CREAT_DT_TM"
    - "REC_UPDT_DT_TM"

  TB_PROD_USER_DEFIN_OP_EXT_FIEL:
    - "PROD_ID"
    - "FIELD_TYPE_CDE"
    - "FIELD_CDE"
    - "FIELD_SEQ_NUM"
    - "CTRY_REC_CDE"
    - "GRP_MEMBR_REC_CDE"
    - "FIELD_DATA_TYPE_TEXT"
    - "FIELD_CHAR_VALUE_TEXT"
    - "FIELD_STRNG_VALUE_TEXT"
    - "FIELD_INTG_VALUE_NUM"
    - "FIELD_DCML_VALUE_NUM"
    - "FIELD_DT_VALUE_DT"
    - "FIELD_TS_VALUE_DT_TM"
    - "REC_CREAT_DT_TM"
    - "REC_UPDT_DT_TM"

  TB_PROD_USER_DEFIN_FIELD:
    - "CTRY_REC_CDE"
    - "GRP_MEMBR_REC_CDE"
    - "PROD_ID"
    - "FIELD_TYPE_CDE"
    - "FIELD_CDE"
    - "FIELD_VALUE_TEXT"
    - "REC_CREAT_DT_TM"
    - "REC_UPDT_DT_TM"

singleTables:
  PROD_PRC_HIST:
    - "PROD_ID"
    - "PDCY_PRC_CDE"
    - "PRC_EFF_DT"
    - "PRC_INP_DT"
    - "CCY_PROD_MKT_PRC_CDE"
    - "PROD_BID_PRC_AMT"
    - "PROD_OFFR_PRC_AMT"
    - "PROD_MKT_PRC_AMT"
    - "PROD_NAV_PRC_AMT"
    - "REC_CREAT_DT_TM"
    - "REC_UPDT_DT_TM"

  CDE_DESC_VALUE:
    - "CTRY_REC_CDE"
    - "GRP_MEMBR_REC_CDE"
    - "CDV_TYPE_CDE"
    - "CDV_CDE"
    - "CDV_DESC"
    - "CDV_PLL_DESC"
    - "CDV_SLL_DESC"
    - "CDV_DISP_SEQ_NUM"
    - "CDV_PARNT_TYPE_CDE"
    - "CDV_PARNT_CDE"
    - "REC_CMNT_TEXT"
    - "REC_CREAT_DT_TM"
    - "REC_UPDT_DT_TM"