//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.31 at 06:38:03 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.assetallocation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"portfolioDate", "assetAllocBondNet", "preferredStockNet", "assetAllocCashNet", "otherNet",
    "assetAllocEquityNet"})
@XmlRootElement(name = "api")
public class Api {

    @XmlElement(name = "PortfolioDate", required = true)
    protected String portfolioDate;
    @XmlElement(name = "AssetAllocBondNet", required = true)
    protected String assetAllocBondNet;
    @XmlElement(name = "PreferredStockNet", required = true)
    protected String preferredStockNet;
    @XmlElement(name = "AssetAllocCashNet", required = true)
    protected String assetAllocCashNet;
    @XmlElement(name = "OtherNet", required = true)
    protected String otherNet;
    @XmlElement(name = "AssetAllocEquityNet", required = true)
    protected String assetAllocEquityNet;
    @XmlAttribute(name = "_id")
    protected String id;


    public String getPortfolioDate() {
        return this.portfolioDate;
    }


    public void setPortfolioDate(final String portfolioDate) {
        this.portfolioDate = portfolioDate;
    }


    public String getAssetAllocBondNet() {
        return this.assetAllocBondNet;
    }


    public void setAssetAllocBondNet(final String assetAllocBondNet) {
        this.assetAllocBondNet = assetAllocBondNet;
    }


    public String getPreferredStockNet() {
        return this.preferredStockNet;
    }


    public void setPreferredStockNet(final String preferredStockNet) {
        this.preferredStockNet = preferredStockNet;
    }


    public String getAssetAllocCashNet() {
        return this.assetAllocCashNet;
    }


    public void setAssetAllocCashNet(final String assetAllocCashNet) {
        this.assetAllocCashNet = assetAllocCashNet;
    }


    public String getOtherNet() {
        return this.otherNet;
    }


    public void setOtherNet(final String otherNet) {
        this.otherNet = otherNet;
    }


    public String getAssetAllocEquityNet() {
        return this.assetAllocEquityNet;
    }


    public void setAssetAllocEquityNet(final String assetAllocEquityNet) {
        this.assetAllocEquityNet = assetAllocEquityNet;
    }


    public String getId() {
        return this.id;
    }


    public void setId(final String id) {
        this.id = id;
    }
}
