mds:
  distributed-cache-uri: https://distributed-cache-system-hk-hase-v1-cert.apps.cf.skm-drn-01.cloud.hk.hhhh/cache
  news:
    detail-uri: https://aag.uat.wealth-platform-hase.ape1.dev.aws.cloud.hhhh/wealth/api/v1/market-data/news/equity/detail
    headlines-uri: https://aag.uat.wealth-platform-hase.ape1.dev.aws.cloud.hhhh/wealth/api/v1/market-data/news/equity/headlines
  equity:
    current-ipo-uri: https://aag.uat.wealth-platform-hase.ape1.dev.aws.cloud.hhhh/wealth/api/v1/market-data/equity/currentIPO
    listed-ipo-uri: https://aag.uat.wealth-platform-hase.ape1.dev.aws.cloud.hhhh/wealth/api/v1/market-data/equity/listedIPO
  charts:
    performance-uri: https://aag.uat.wealth-platform-hase.ape1.dev.aws.cloud.hhhh/wealth/api/v1/market-data/equity/charts/performance
  product:
    predictive-search-uri: https://aag.uat.wealth-platform-hase.ape1.dev.aws.cloud.hhhh/wealth/api/v1/market-data/product/predictive-search
    multi-predictive-search-uri: https://aag.uat.wealth-platform-hase.ape1.dev.aws.cloud.hhhh/wealth/api/v1/market-data/product/multi-predictive-search
  quotes:
    top-mover-uri: https://aag.uat.wealth-platform-hase.ape1.dev.aws.cloud.hhhh/wealth/api/v1/market-data/equity/quotes/top-mover
    quotes-uri: https://aag.uat.wealth-platform-hase.ape1.dev.aws.cloud.hhhh/wealth/api/v1/market-data/equity/quotes
    index-quotes-uri: https://aag.uat.wealth-platform-hase.ape1.dev.aws.cloud.hhhh/wealth/api/v1/market-data/index/quotes