

server:
  max-http-header-size: 163840
  port: 9099

logging:
  level:
    root: info
    com.hhhh.wealth: info

#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@wealth-wpamh-ap-east-1-dev-orcl01.cn9pdf2888wz.ap-east-1.rds.amazonaws.com:1521:UAMHWP01
#    username: MDSHKUTUA1_APPUSER

spring: 
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 5
      maximum-pool-size: 10
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@amh-dev-wporcl01.wealth-platform-amh.dev.aws.cloud.hhhh:1521:UAMHWP01
    username: MDSHKUA1_APPUSER
    password: '{cipher}8406f2de50ae4683c34489241d5ad691036cbc66f248d62fcdb91f853b8f8264158d1f38dbaca60ee64fc9e1b9c5ccb6'
