package com.hhhh.group.secwealth.mktdata.common.beans;

import com.hhhh.group.secwealth.mktdata.common.beans.response.ProdAltNumSeg;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import java.util.ArrayList;


@RunWith(MockitoJUnitRunner.Silent.class)
public class SearchableObjectTest extends SearchableObject{

    @Test
    public void searchableObject(){
        SearchableObject searchableObject = new SearchableObject();
        searchableObject.setProductName_analyzed(new String[2]);
        searchableObject.getId();
        searchableObject.setId("");
        searchableObject.setProductName_analyzed(new String[1]);
        searchableObject.getProductName();
        searchableObject.setProductName("");
        searchableObject.getProductShortName_analyzed();
        searchableObject.setProductShortName_analyzed(new String[4]);
        searchableObject.getProductShortName();
        searchableObject.setProductShortName("");
        searchableObject.getSwitchableGroup_analyzed();
        searchableObject.setSwitchableGroup_analyzed(new String[2]);
        searchableObject.getSymbol_analyzed();
        searchableObject.setSymbol_analyzed("");
        searchableObject.getSymbol();
        searchableObject.setSymbol("");
        searchableObject.getKey_analyzed();
        searchableObject.setKey_analyzed("");
        searchableObject.getKey();
        searchableObject.setKey("");
        searchableObject.getProductType_analyzed();
        searchableObject.setProductType_analyzed("");
        searchableObject.getProductType();
        searchableObject.setProductType("");
        searchableObject.getCountryTradableCode();
        searchableObject.setCountryTradableCode("");
        searchableObject.getCountryTradableCode_analyzed();
        searchableObject.setCountryTradableCode_analyzed("");
        searchableObject.getProductSubType();
        searchableObject.setProductSubType("");
        searchableObject.getProductSubType_analyzed();
        searchableObject.setProductSubType_analyzed("");
        searchableObject.getFundHouseCde();
        searchableObject.setFundHouseCde("");
        searchableObject.getFundHouseCde_analyzed();
        searchableObject.setFundHouseCde_analyzed("");
        searchableObject.getIsrBndNme();
        searchableObject.setIsrBndNme("");
        searchableObject.getIsrBndNme_analyzed();
        searchableObject.setIsrBndNme_analyzed("");
        searchableObject.getAllowSellMipProdInd();
        searchableObject.setAllowSellMipProdInd("");
        searchableObject.getAllowSellMipProdInd_analyzed();
        searchableObject.setAllowSellMipProdInd_analyzed("");
        searchableObject.getRestrOnlScribInd();
        searchableObject.setRestrOnlScribInd("");
        searchableObject.getRestrOnlScribInd_analyzed();
        searchableObject.setRestrOnlScribInd_analyzed("");
        searchableObject.getAllowTradeProdInd();
        searchableObject.setAllowTradeProdInd("");
        searchableObject.getAllowTradeProdInd_analyzed();
        searchableObject.setAllowTradeProdInd_analyzed("");
        searchableObject.getAllowSwInProdInd();
        searchableObject.setAllowSwInProdInd("");
        searchableObject.getAllowSwInProdInd_analyzed();
        searchableObject.setAllowSwInProdInd_analyzed("");
        searchableObject.getAllowSwOutProdInd();
        searchableObject.setAllowSwOutProdInd("");
        searchableObject.getAllowSwOutProdInd_analyzed();
        searchableObject.setAllowSwOutProdInd_analyzed("");
        searchableObject.getProductCode();
        searchableObject.setProductCode("");
        searchableObject.getProductCode_analyzed();
        searchableObject.setProductCode_analyzed("");
        searchableObject.getProdTaxFreeWrapActStaCde();
        searchableObject.setProdTaxFreeWrapActStaCde("");
        searchableObject.getProdTaxFreeWrapActStaCde_analyzed();
        searchableObject.setProdTaxFreeWrapActStaCde_analyzed("");
        searchableObject.getCountryTradableCodeWeight();
        searchableObject.setCountryTradableCodeWeight(1);
        searchableObject.getProductTypeWeight();
        searchableObject.setProductTypeWeight(0.01);
        searchableObject.getMarket();
        searchableObject.setMarket("");
        searchableObject.getProdAltNumSegs();
        searchableObject.setProdAltNumSegs(new ArrayList<ProdAltNumSeg>());
        searchableObject.getFundUnswithSeg();
        searchableObject.setFundUnswithSeg(new String[4]);
        searchableObject.getResChannelCde();
        searchableObject.setResChannelCde(new String[6]);
        searchableObject.getResChannelCde_analyzed();
        searchableObject.setResChannelCde_analyzed(new String[5]);
        searchableObject.getChanlCde();
        searchableObject.setChanlCde(new String[4]);
        searchableObject.getChanlCde_analyzed();
        searchableObject.setChanlCde_analyzed(new String[5]);
        searchableObject.getAllowBuy();
        searchableObject.setAllowBuy("");
        searchableObject.getAllowBuy_analyzed();
        searchableObject.setAllowBuy_analyzed("");
        searchableObject.getAllowSell();
        searchableObject.setAllowSell("");
        searchableObject.getChanlAllowBuy();
        searchableObject.setChanlAllowBuy(new ArrayList<String>());
        searchableObject.getChanlAllowSell();
        searchableObject.setChanlAllowSell(new ArrayList<String>());
        searchableObject.getExchange();
        searchableObject.setExchange("");
        searchableObject.getProductCcy();
        searchableObject.setProductCcy("");
        searchableObject.getAssetCountry();
        searchableObject.setAssetCountry(new String[4]);
        searchableObject.getAssetSector();
        searchableObject.setAssetSector(new String[5]);
        searchableObject.getAssetSector();
        searchableObject.setAssetSector(new String[4]);
        searchableObject.getParentAssetClass();
        searchableObject.setParentAssetClass(new String[4]);
        searchableObject.getProdShoreLocCde();
        searchableObject.setProdShoreLocCde("");
        searchableObject.getRiskLvlCde();
        searchableObject.setRiskLvlCde("");
        searchableObject.getProdStatCde_analyzed();
        searchableObject.setProdStatCde_analyzed("");
        searchableObject.getProdStatCde();
        searchableObject.setProdStatCde("");
        searchableObject.getPiFundInd_analyzed();
        searchableObject.setPiFundInd_analyzed("");
        searchableObject.getPiFundInd();
        searchableObject.setPiFundInd("");
        searchableObject.getDeAuthFundInd_analyzed();
        searchableObject.setDeAuthFundInd_analyzed("");
        searchableObject.getDeAuthFundInd();
        Assert.assertTrue(true);
    }
}
