market-hour:
  session-info: 
    SHAS:
      1: 09:30:00-11:30:00,13:00:00-15:00:00
      2: 09:30:00-11:30:00,13:00:00-15:00:00
      3: 09:30:00-11:30:00,13:00:00-15:00:00
      4: 09:30:00-11:30:00,13:00:00-15:00:00
      5: 09:30:00-11:30:00,13:00:00-15:00:00
    SZAS:
      1: 09:30:00-11:30:00,13:00:00-15:00:00
      2: 09:30:00-11:30:00,13:00:00-15:00:00
      3: 09:30:00-11:30:00,13:00:00-15:00:00
      4: 09:30:00-11:30:00,13:00:00-15:00:00
      5: 09:30:00-11:30:00,13:00:00-15:00:00
  timezone:
    DEFAULT: GMT+8
    SHAS: Asia/Shanghai
    SZAS: Asia/Shanghai
  marketDelayClose:
    DEFAULT: 0
    SHAS: 15
    SZAS: 15
  holiday:
    DEFAULT:
      DEFAULT:
        DEFAULT:
          DEFAULT:
    SHAS:
      2019:
        20190101:
          tradinghour:
          desc:
        20190204:
          tradinghour:
          desc:
        20190205:
          tradinghour:
          desc:
        20190206:
          tradinghour:
          desc:
        20190207:
          tradinghour:
          desc:
        20190208:
          tradinghour:
          desc:
        20190405:
          tradinghour:
          desc:
        20190501:
          tradinghour:
          desc:
        20190502:
          tradinghour:
          desc:
        20190503:
          tradinghour:
          desc:
        20190607:
          tradinghour:
          desc:
        20190913:
          tradinghour:
          desc:
        20191001:
          tradinghour:
          desc:
        20191002:
          tradinghour:
          desc:
        20191003:
          tradinghour:
          desc:
        20191004:
          tradinghour:
          desc:
        20191007:
          tradinghour:
          desc:
      2020:
        20200101:
          tradinghour:
          desc:
        20200124:
          tradinghour:
          desc:
        20200127:
          tradinghour:
          desc:
        20200128:
          tradinghour:
          desc:
        20200129:
          tradinghour:
          desc:
        20200130:
          tradinghour:
          desc:
        20200131:
          tradinghour:
          desc:
        20200406:
          tradinghour:
          desc:
        20200501:
          tradinghour:
          desc:
        20200504:
          tradinghour:
          desc:
        20200505:
          tradinghour:
          desc:
        20200625:
          tradinghour:
          desc:
        20200626:
          tradinghour:
          desc:
        20201001:
          tradinghour:
          desc:
        20201002:
          tradinghour:
          desc:
        20201005:
          tradinghour:
          desc:
        20201006:
          tradinghour:
          desc:
        20201007:
          tradinghour:
          desc:
        20201008:
          tradinghour:
          desc:
    SZAS:
      2019:
        20190101:
          tradinghour:
          desc:
        20190204:
          tradinghour:
          desc:
        20190205:
          tradinghour:
          desc:
        20190206:
          tradinghour:
          desc:
        20190207:
          tradinghour:
          desc:
        20190208:
          tradinghour:
          desc:
        20190405:
          tradinghour:
          desc:
        20190501:
          tradinghour:
          desc:
        20190502:
          tradinghour:
          desc:
        20190503:
          tradinghour:
          desc:
        20190607:
          tradinghour:
          desc:
        20190913:
          tradinghour:
          desc:
        20191001:
          tradinghour:
          desc:
        20191002:
          tradinghour:
          desc:
        20191003:
          tradinghour:
          desc:
        20191004:
          tradinghour:
          desc:
        20191007:
          tradinghour:
          desc:
      2020:
        20200101:
          tradinghour:
          desc:
        20200124:
          tradinghour:
          desc:
        20200127:
          tradinghour:
          desc:
        20200128:
          tradinghour:
          desc:
        20200129:
          tradinghour:
          desc:
        20200130:
          tradinghour:
          desc:
        20200131:
          tradinghour:
          desc:
        20200406:
          tradinghour:
          desc:
        20200501:
          tradinghour:
          desc:
        20200504:
          tradinghour:
          desc:
        20200505:
          tradinghour:
          desc:
        20200625:
          tradinghour:
          desc:
        20200626:
          tradinghour:
          desc:
        20201001:
          tradinghour:
          desc:
        20201002:
          tradinghour:
          desc:
        20201005:
          tradinghour:
          desc:
        20201006:
          tradinghour:
          desc:
        20201007:
          tradinghour:
          desc:
        20201008:
          tradinghour:
          desc:
  special:
    DEFAULT:
      DEFAULT:
        DEFAULT:
          DEFAULT:
  delayed:
    DEFAULT:
      DEFAULT: DEFAULT
      


