package com.dummy.wpb.product.jpo;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Data
@Entity
@Table(name = "TB_PROD")
public class ProductPo implements Serializable {

    @Id
    @Column(name = "PROD_ID")
    private Long prodId;
    @Column(name = "CTRY_REC_CDE")
    private String ctryRecCde;
    @Column(name = "GRP_MEMBR_REC_CDE")
    private String grpMembrRecCde;
    @Column(name = "PROD_TYPE")
    private String prodType;
    @Column(name = "PROD_TYPE_CDE")
    private String prodTypeCde;
    @Column(name = "PROD_SUBTP_CDE")
    private String prodSubtpCde;
    @Column(name = "PROD_CDE")
    private String prodCde;
    @Column(name = "PROD_ALT_PRIM_NUM")
    private String prodAltPrimNum;
    @Column(name = "PROD_NAME")
    private String prodName;
    @Column(name = "PROD_PLL_NAME")
    private String prodPllName;
    @Column(name = "PROD_SLL_NAME")
    private String prodSllName;
    @Column(name = "PROD_SHRT_NAME")
    private String prodShrtName;
    @Column(name = "PROD_SHRT_PLL_NAME")
    private String prodShrtPllName;
    @Column(name = "PROD_SHRT_SLL_NAME")
    private String prodShrtSllName;
    @Column(name = "PROD_DESC")
    private String prodDesc;
    @Column(name = "PROD_PLL_DESC")
    private String prodPllDesc;
    @Column(name = "PROD_SLL_DESC")
    private String prodSllDesc;
    @Column(name = "ASET_CLASS_CDE")
    private String asetClassCde;
    @Column(name = "PROD_STAT_CDE")
    private String prodStatCde;
    @Column(name = "CCY_PROD_CDE")
    private String ccyProdCde;
    @Column(name = "RISK_LVL_CDE")
    private String riskLvlCde;
    @Column(name = "PRD_PROD_CDE")
    private String prdProdCde;
    @Column(name = "PRD_PROD_NUM")
    private Long prdProdNum;
    @Column(name = "TERM_REMAIN_DAY_CNT")
    private Long termRemainDayCnt;
    @Column(name = "PROD_LNCH_DT")
    private Date prodLnchDt;
    @Column(name = "PROD_MTUR_DT")
    private Date prodMturDt;
    @Column(name = "MKT_INVST_CDE")
    private String mktInvstCde;
    @Column(name = "SECT_INVST_CDE")
    private String sectInvstCde;
    @Column(name = "ALLOW_BUY_PROD_IND")
    private String allowBuyProdInd;
    @Column(name = "ALLOW_SELL_PROD_IND")
    private String allowSellProdInd;
    @Column(name = "ALLOW_BUY_UT_PROD_IND")
    private String allowBuyUtProdInd;
    @Column(name = "ALLOW_BUY_AMT_PROD_IND")
    private String allowBuyAmtProdInd;
    @Column(name = "ALLOW_SELL_UT_PROD_IND")
    private String allowSellUtProdInd;
    @Column(name = "ALLOW_SELL_AMT_PROD_IND")
    private String allowSellAmtProdInd;
    @Column(name = "ALLOW_SELL_MIP_PROD_IND")
    private String allowSellMipProdInd;
    @Column(name = "ALLOW_SELL_MIP_UT_PROD_IND")
    private String allowSellMipUtProdInd;
    @Column(name = "ALLOW_SELL_MIP_AMT_PROD_IND")
    private String allowSellMipAmtProdInd;
    @Column(name = "ALLOW_SW_IN_PROD_IND")
    private String allowSwInProdInd;
    @Column(name = "ALLOW_SW_IN_UT_PROD_IND")
    private String allowSwInUtProdInd;
    @Column(name = "ALLOW_SW_IN_AMT_PROD_IND")
    private String allowSwInAmtProdInd;
    @Column(name = "ALLOW_SW_OUT_PROD_IND")
    private String allowSwOutProdInd;
    @Column(name = "ALLOW_SW_OUT_UT_PROD_IND")
    private String allowSwOutUtProdInd;
    @Column(name = "ALLOW_SW_OUT_AMT_PROD_IND")
    private String allowSwOutAmtProdInd;
    @Column(name = "INCM_CHAR_PROD_IND")
    private String incmCharProdInd;
    @Column(name = "CPTL_GURNT_PROD_IND")
    private String cptlGurntProdInd;
    @Column(name = "YIELD_ENHN_PROD_IND")
    private String yieldEnhnProdInd;
    @Column(name = "GRWTH_CHAR_PROD_IND")
    private String grwthCharProdInd;
    @Column(name = "PRTY_PROD_SRCH_RSULT_NUM")
    private Long prtyProdSrchRsultNum;
    @Column(name = "AVAIL_MKT_INFO_IND")
    private String availMktInfoInd;
    @Column(name = "PRD_RTRN_AVG_NUM")
    private BigDecimal prdRtrnAvgNum;
    @Column(name = "RTRN_VOLTL_AVG_PCT")
    private BigDecimal rtrnVoltlAvgPct;
    @Column(name = "DMY_PROD_SUBTP_REC_IND")
    private String dmyProdSubtpRecInd;
    @Column(name = "DISP_COM_PROD_SRCH_IND")
    private String dispComProdSrchInd;
    @Column(name = "MRK_TO_MKT_IND")
    private String mrkToMktInd;
    @Column(name = "PROD_NARR_TEXT")
    private String prodNarrText;
    @Column(name = "CTRY_PROD_TRADE_1_CDE")
    private String ctryProdTrade1Cde;
    @Column(name = "CTRY_PROD_TRADE_2_CDE")
    private String ctryProdTrade2Cde;
    @Column(name = "CTRY_PROD_TRADE_3_CDE")
    private String ctryProdTrade3Cde;
    @Column(name = "CTRY_PROD_TRADE_4_CDE")
    private String ctryProdTrade4Cde;
    @Column(name = "CTRY_PROD_TRADE_5_CDE")
    private String ctryProdTrade5Cde;
    @Column(name = "BUS_START_TM")
    private Date busStartTm;
    @Column(name = "BUS_END_TM")
    private Date busEndTm;
    @Column(name = "INTRO_PROD_CURR_PRD_IND")
    private String introProdCurrPrdInd;
    @Column(name = "PROD_TOP_SELL_RANK_NUM")
    private Long prodTopSellRankNum;
    @Column(name = "PROD_TOP_PERFM_RANK_NUM")
    private Long prodTopPerfmRankNum;
    @Column(name = "PROD_TOP_YIELD_RANK_NUM")
    private Long prodTopYieldRankNum;
    @Column(name = "PROD_ISSUE_CROS_REFER_DT")
    private Date prodIssueCrosReferDt;
    @Column(name = "PROD_CMNT_TEXT")
    private String prodCmntText;
    @Column(name = "CCY_INVST_CDE")
    private String ccyInvstCde;
    @Column(name = "BCHMK_NAME")
    private String bchmkName;
    @Column(name = "BCHMK_PLL_NAME")
    private String bchmkPllName;
    @Column(name = "BCHMK_SLL_NAME")
    private String bchmkSllName;
    @Column(name = "TRD_FIRST_DT")
    private Date trdFirstDt;
    @Column(name = "LOAN_PROD_OD_MRGN_PCT")
    private BigDecimal loanProdOdMrgnPct;
    @Column(name = "QTY_UNIT_PROD_CDE")
    private String qtyUnitProdCde;
    @Column(name = "PROD_LOC_CDE")
    private String prodLocCde;
    @Column(name = "PROD_TAX_FREE_WRAP_ACT_STA_CDE")
    private String prodTaxFreeWrapActStaCde;
    @Column(name = "PRC_EFF_DT")
    private Date prcEffDt;
    @Column(name = "CCY_PROD_MKT_PRC_CDE")
    private String ccyProdMktPrcCde;
    @Column(name = "PROD_BID_PRC_AMT")
    private BigDecimal prodBidPrcAmt;
    @Column(name = "PROD_OFFR_PRC_AMT")
    private BigDecimal prodOffrPrcAmt;
    @Column(name = "PROD_MKT_PRC_AMT")
    private BigDecimal prodMktPrcAmt;
    @Column(name = "PROD_NAV_PRC_AMT")
    private BigDecimal prodNavPrcAmt;
    @Column(name = "PROD_PRC_UPDT_DT_TM")
    private Date prodPrcUpdtDtTm;
    @Column(name = "DCML_PLACE_TRADE_UNIT_NUM")
    private Long dcmlPlaceTradeUnitNum;
    @Column(name = "PROD_OFFR_CHANL_UPDT_DT_TM")
    private Date prodOffrChanlUpdtDtTm;
    @Column(name = "PLDG_LIMIT_ASSOC_ACCT_IND")
    private String pldgLimitAssocAcctInd;
    @Column(name = "PROD_OWN_CDE")
    private String prodOwnCde;
    @Column(name = "FORGN_PROD_IND")
    private String forgnProdInd;
    @Column(name = "PROD_STAT_UPDT_DT_TM")
    private Date prodStatUpdtDtTm;
    @Column(name = "ASET_CAT_EXTNL_CDE")
    private String asetCatExtnlCde;
    @Column(name = "PROD_MKT_PRICE_PREV_AMT")
    private BigDecimal prodMktPricePrevAmt;
    @Column(name = "REC_CREAT_DT_TM")
    private Date recCreatDtTm;
    @Column(name = "REC_UPDT_DT_TM")
    private Date recUpdtDtTm;
    @Column(name = "REC_ONLN_UPDT_DT_TM")
    private Date recOnlnUpdtDtTm;
    @Column(name = "PRC_INP_DT")
    private Date prcInpDt;
    @Column(name = "CHRG_CAT_CDE")
    private String chrgCatCde;
    @Column(name = "SUPT_RCBL_CASH_PROD_IND")
    private String suptRcblCashProdInd;
    @Column(name = "SUPT_RCBL_SCRIP_PROD_IND")
    private String suptRcblScripProdInd;
    @Column(name = "ASET_UNDER_MGMT_CHRG_PROD_IND")
    private String asetUnderMgmtChrgProdInd;
    @Column(name = "INVST_IMIG_PROD_IND")
    private String invstImigProdInd;
    @Column(name = "RESTR_INVSTR_PROD_IND")
    private String restrInvstrProdInd;
    @Column(name = "PROD_INVST_OBJ_TEXT")
    private String prodInvstObjText;
    @Column(name = "INVST_INIT_MIN_AMT")
    private BigDecimal invstInitMinAmt;
    @Column(name = "NO_SCRIB_FEE_PROD_IND")
    private String noScribFeeProdInd;
    @Column(name = "TOP_SELL_PROD_IND")
    private String topSellProdInd;
    @Column(name = "TOP_PERFM_PROD_IND")
    private String topPerfmProdInd;
    @Column(name = "INVST_INIT_MAX_AMT")
    private BigDecimal invstInitMaxAmt;
    @Column(name = "RCMND_PROD_DECSN_CDE")
    private String rcmndProdDecsnCde;
    @Column(name = "ASET_TEXT")
    private String asetText;
    @Column(name = "PROD_DERVT_CDE")
    private String prodDervtCde;
    @Column(name = "PROD_DERVT_RVS_CDE")
    private String prodDervtRvsCde;
    @Column(name = "PRD_DERV_RVS_EFF_DT")
    private Date prdDervRvsEffDt;
    @Column(name = "EQTY_UNDL_IND")
    private String eqtyUndlInd;
    @Column(name = "WLTH_ACCUM_GOAL_IND")
    private String wlthAccumGoalInd;
    @Column(name = "PRTY_WLTH_ACCUM_GOAL_CDE")
    private String prtyWlthAccumGoalCde;
    @Column(name = "PLAN_FOR_RTIRE_GOAL_IND")
    private String planForRtireGoalInd;
    @Column(name = "PRTY_PLN_FOR_RTIRE_CDE")
    private String prtyPlnForRtireCde;
    @Column(name = "EDUC_GOAL_IND")
    private String educGoalInd;
    @Column(name = "PRTY_EDUC_CDE")
    private String prtyEducCde;
    @Column(name = "LIVE_IN_RTIRE_GOAL_IND")
    private String liveInRtireGoalInd;
    @Column(name = "PRTY_LIVE_IN_RTIRE_CDE")
    private String prtyLiveInRtireCde;
    @Column(name = "PROTC_GOAL_IND")
    private String protcGoalInd;
    @Column(name = "PRTY_PROTC_CDE")
    private String prtyProtcCde;
    @Column(name = "MNG_SOLN_IND")
    private String mngSolnInd;
    @Column(name = "PRD_INVST_TNOR_NUM")
    private Long prdInvstTnorNum;
    @Column(name = "GEO_RISK_IND")
    private String geoRiskInd;
    @Column(name = "PROD_LQDY_IND")
    private String prodLqdyInd;
    @Column(name = "RVRSE_ENQ_PROD_IND")
    private String rvrseEnqProdInd;
    @Column(name = "PROD_INVST_TYPE_CDE")
    private String prodInvstTypeCde;
    @Column(name = "DIVR_NUM")
    private BigDecimal divrNum;
    @Column(name = "PRICE_HIST_SRCE_RDY_STAT_CDE")
    private String priceHistSrceRdyStatCde;
    @Column(name = "PRICE_HIST_DELVR_DT_TM")
    private Date priceHistDelvrDtTm;
    @Column(name = "ISLM_PROD_IND")
    private String islmProdInd;
    @Column(name = "CNTL_ADVC_IND")
    private String cntlAdvcInd;
    @Column(name = "ASET_VOLTL_CLASS_MAJR_PRNT_CDE")
    private String asetVoltlClassMajrPrntCde;
    @Column(name = "REC_STGC_FIN_PLN_UPDT_DT_TM")
    private Date recStgcFinPlnUpdtDtTm;
    @Column(name = "PROD_PARNT_ID")
    private Long prodParntId;
}
