//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.31 at 06:38:03 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.quoteholdings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"fnaSurveyedFundNetAssets", "fnaAsOfOriginalReportedCurrencyId",
    "fnaCategoryNormalizedFundNetAssets", "fnaNormalizedFundNetAssets", "fnaFundNetAssets", "fnaCategoryFundNetAssets",
    "psTurnoverRatio", "psCategoryTurnoverRatio", "psPriceToEarnings", "psCategoryPriceToEarnings", "psPriceToBook",
    "psCategoryPriceToBook", "psroa", "psCategoryROA", "psroe", "psCategoryROE", "yldYield1Yr", "psAverageCreditQuality",
    "psCategoryAverageCreditQuality", "psYieldToMaturity", "psCategoryYieldToMaturity", "psEffectiveMaturity", "psrpPortfolioDate"})
@XmlRootElement(name = "api")
public class Api {

    @XmlElement(name = "FNA-SurveyedFundNetAssets", required = true)
    protected String fnaSurveyedFundNetAssets;
    @XmlElement(name = "FNA-AsOfOriginalReportedCurrencyId", required = true)
    protected String fnaAsOfOriginalReportedCurrencyId;
    @XmlElement(name = "FNA-CategoryNormalizedFundNetAssets", required = true)
    protected String fnaCategoryNormalizedFundNetAssets;
    @XmlElement(name = "FNA-NormalizedFundNetAssets", required = true)
    protected String fnaNormalizedFundNetAssets;
    @XmlElement(name = "FNA-FundNetAssets", required = true)
    protected String fnaFundNetAssets;
    @XmlElement(name = "FNA-CategoryFundNetAssets", required = true)
    protected String fnaCategoryFundNetAssets;
    @XmlElement(name = "PS-TurnoverRatio", required = true)
    protected String psTurnoverRatio;
    @XmlElement(name = "PS-CategoryTurnoverRatio", required = true)
    protected String psCategoryTurnoverRatio;
    @XmlElement(name = "PS-PriceToEarnings", required = true)
    protected String psPriceToEarnings;
    @XmlElement(name = "PS-CategoryPriceToEarnings", required = true)
    protected String psCategoryPriceToEarnings;
    @XmlElement(name = "PS-PriceToBook", required = true)
    protected String psPriceToBook;
    @XmlElement(name = "PS-CategoryPriceToBook", required = true)
    protected String psCategoryPriceToBook;
    @XmlElement(name = "PS-ROA", required = true)
    protected String psroa;
    @XmlElement(name = "PS-CategoryROA", required = true)
    protected String psCategoryROA;
    @XmlElement(name = "PS-ROE", required = true)
    protected String psroe;
    @XmlElement(name = "PS-CategoryROE", required = true)
    protected String psCategoryROE;
    @XmlElement(name = "YLD-Yield1Yr", required = true)
    protected String yldYield1Yr;
    @XmlElement(name = "PS-AverageCreditQuality", required = true)
    protected String psAverageCreditQuality;
    @XmlElement(name = "PS-CategoryAverageCreditQuality", required = true)
    protected String psCategoryAverageCreditQuality;
    @XmlElement(name = "PS-YieldToMaturity", required = true)
    protected String psYieldToMaturity;
    @XmlElement(name = "PS-CategoryYieldToMaturity", required = true)
    protected String psCategoryYieldToMaturity;
    @XmlElement(name = "PS-EffectiveMaturity", required = true)
    protected String psEffectiveMaturity;
    @XmlElement(name = "PSRP-PortfolioDate", required = true)
    protected String psrpPortfolioDate;
    @XmlAttribute(name = "_id")
    protected String id;


    public String getFNASurveyedFundNetAssets() {
        return this.fnaSurveyedFundNetAssets;
    }


    public void setFNASurveyedFundNetAssets(final String value) {
        this.fnaSurveyedFundNetAssets = value;
    }


    public String getFnaAsOfOriginalReportedCurrencyId() {
        return this.fnaAsOfOriginalReportedCurrencyId;
    }


    public void setFnaAsOfOriginalReportedCurrencyId(final String fnaAsOfOriginalReportedCurrencyId) {
        this.fnaAsOfOriginalReportedCurrencyId = fnaAsOfOriginalReportedCurrencyId;
    }


    public String getFnaCategoryNormalizedFundNetAssets() {
        return this.fnaCategoryNormalizedFundNetAssets;
    }


    public void setFnaCategoryNormalizedFundNetAssets(final String fnaCategoryNormalizedFundNetAssets) {
        this.fnaCategoryNormalizedFundNetAssets = fnaCategoryNormalizedFundNetAssets;
    }


    public String getFnaNormalizedFundNetAssets() {
        return this.fnaNormalizedFundNetAssets;
    }


    public void setFnaNormalizedFundNetAssets(final String fnaNormalizedFundNetAssets) {
        this.fnaNormalizedFundNetAssets = fnaNormalizedFundNetAssets;
    }


    public String getFNAFundNetAssets() {
        return this.fnaFundNetAssets;
    }


    public void setFNAFundNetAssets(final String value) {
        this.fnaFundNetAssets = value;
    }


    public String getFNACategoryFundNetAssets() {
        return this.fnaCategoryFundNetAssets;
    }


    public void setFNACategoryFundNetAssets(final String value) {
        this.fnaCategoryFundNetAssets = value;
    }


    public String getPSTurnoverRatio() {
        return this.psTurnoverRatio;
    }


    public void setPSTurnoverRatio(final String value) {
        this.psTurnoverRatio = value;
    }


    public String getPSCategoryTurnoverRatio() {
        return this.psCategoryTurnoverRatio;
    }


    public void setPSCategoryTurnoverRatio(final String value) {
        this.psCategoryTurnoverRatio = value;
    }


    public String getPSPriceToEarnings() {
        return this.psPriceToEarnings;
    }


    public void setPSPriceToEarnings(final String value) {
        this.psPriceToEarnings = value;
    }


    public String getPSCategoryPriceToEarnings() {
        return this.psCategoryPriceToEarnings;
    }


    public void setPSCategoryPriceToEarnings(final String value) {
        this.psCategoryPriceToEarnings = value;
    }


    public String getPSPriceToBook() {
        return this.psPriceToBook;
    }


    public void setPSPriceToBook(final String value) {
        this.psPriceToBook = value;
    }


    public String getPSCategoryPriceToBook() {
        return this.psCategoryPriceToBook;
    }


    public void setPSCategoryPriceToBook(final String value) {
        this.psCategoryPriceToBook = value;
    }


    public String getPSROA() {
        return this.psroa;
    }


    public void setPSROA(final String value) {
        this.psroa = value;
    }


    public String getPSCategoryROA() {
        return this.psCategoryROA;
    }


    public void setPSCategoryROA(final String value) {
        this.psCategoryROA = value;
    }


    public String getPSROE() {
        return this.psroe;
    }


    public void setPSROE(final String value) {
        this.psroe = value;
    }


    public String getPSCategoryROE() {
        return this.psCategoryROE;
    }


    public void setPSCategoryROE(final String value) {
        this.psCategoryROE = value;
    }


    public String getYLDYield1Yr() {
        return this.yldYield1Yr;
    }


    public void setYLDYield1Yr(final String value) {
        this.yldYield1Yr = value;
    }


    public String getPSAverageCreditQuality() {
        return this.psAverageCreditQuality;
    }


    public void setPSAverageCreditQuality(final String value) {
        this.psAverageCreditQuality = value;
    }


    public String getPSCategoryAverageCreditQuality() {
        return this.psCategoryAverageCreditQuality;
    }


    public void setPSCategoryAverageCreditQuality(final String value) {
        this.psCategoryAverageCreditQuality = value;
    }


    public String getPSYieldToMaturity() {
        return this.psYieldToMaturity;
    }


    public void setPSYieldToMaturity(final String value) {
        this.psYieldToMaturity = value;
    }


    public String getPSCategoryYieldToMaturity() {
        return this.psCategoryYieldToMaturity;
    }


    public void setPSCategoryYieldToMaturity(final String value) {
        this.psCategoryYieldToMaturity = value;
    }


    public String getPSEffectiveMaturity() {
        return this.psEffectiveMaturity;
    }


    public void setPSEffectiveMaturity(final String value) {
        this.psEffectiveMaturity = value;
    }


    public String getPSRPPortfolioDate() {
        return this.psrpPortfolioDate;
    }


    public void setPSRPPortfolioDate(final String value) {
        this.psrpPortfolioDate = value;
    }


    public String getId() {
        return this.id;
    }


    public void setId(final String value) {
        this.id = value;
    }

}
