swagger: "2.0"
info:
  description: "Query - CN Market"
  version: "1.0.0"
  title: "Market Data Service"
  termsOfService: "https://wpb-confluence.systems.uk.hhhh/display/HASEWP/HASE+Wealth+Platform+Home"

basePath: "/wealth/api/v1/market-data/equity"
tags:
- name: "Quote"
  description: ""
schemes:
- "http"
- "https"
paths:
  /quotes:
    get:
      tags:
      - "Quote"
      summary: "Query quotes"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "param"
        in: "query"
        description: "request payload"
        required: true
        type: "string"
        example: "{\"market\": \"CN\",\"productKeys\": [{\"productType\": \"SEC\",\"prodCdeAltClassCde\": \"M\",\"prodAltNum\": \"000858\"}],\"delay\": true,\"requestType\": \"0\"}"
      responses:
        "200":
          description: "successful"
      security:
      - X-hhhh-Function-Id: [ ]
      - X-hhhh-User-Id: [ ]
      - X-hhhh-Session-Correlation-Id: [ ]
      - X-hhhh-Chnl-CountryCode: [ ]
      - X-hhhh-Chnl-Group-Member: [ ]
      - X-hhhh-Channel-Id: [ ]
      - X-hhhh-Locale: [ ]
      - X-hhhh-App-Code: [ ]
      - X-hhhh-Saml3: [ ]
securityDefinitions:
  X-hhhh-Function-Id:
    type: "apiKey"
    name: "X-hhhh-Function-Id"
    in: "header"
  X-hhhh-User-Id:
    type: "apiKey"
    name: "X-hhhh-User-Id"
    in: "header"
  X-hhhh-Session-Correlation-Id:
    type: "apiKey"
    name: "X-hhhh-Session-Correlation-Id"
    in: "header"
  X-hhhh-Chnl-CountryCode:
    type: "apiKey"
    name: "X-hhhh-Chnl-CountryCode"
    in: "header"
  X-hhhh-Chnl-Group-Member:
    type: "apiKey"
    name: "X-hhhh-Chnl-Group-Member"
    in: "header"
  X-hhhh-Channel-Id:
    type: "apiKey"
    name: "X-hhhh-Channel-Id"
    in: "header"
  X-hhhh-Locale:
    type: "apiKey"
    name: "X-hhhh-Locale"
    in: "header"
  X-hhhh-App-Code:
    type: "apiKey"
    name: "X-hhhh-App-Code"
    in: "header"
  X-hhhh-Saml3:
    type: "apiKey"
    name: "X-hhhh-Saml3"
    in: "header"
