-- =====================================================
-- Cognos Tables Schema for MySQL
-- 转换自PostgreSQL DDL: create_cognos_tables_schema.sql
-- 创建时间: 2025-01-04 14:30:30
-- 数据库: nl2sql
-- =====================================================

-- 设置字符集和排序规则
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- =====================================================
-- 1. 参考数据表 - CDE_DESC_VALUE
-- =====================================================
DROP TABLE IF EXISTS `CDE_DESC_VALUE`;
CREATE TABLE `CDE_DESC_VALUE` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `CTRY_REC_CDE` CHAR(2) NOT NULL COMMENT '国家记录代码',
    `GRP_MEMBR_REC_CDE` CHAR(4) NOT NULL COMMENT '集团成员记录代码',
    `CDV_TYPE_CDE` VARCHAR(15) NOT NULL COMMENT '代码值类型代码',
    `CDV_CDE` VARCHAR(30) NOT NULL COMMENT '代码值代码',
    `CDV_DESC` VARCHAR(100) NULL COMMENT '代码值描述',
    `CDV_PLL_DESC` VARCHAR(300) NULL COMMENT '代码值并行语言描述',
    `CDV_SLL_DESC` VARCHAR(300) NULL COMMENT '代码值第二语言描述',
    `CDV_DISP_SEQ_NUM` DECIMAL(38,0) NULL COMMENT '代码值显示序号',
    `CDV_PARNT_TYPE_CDE` VARCHAR(15) NULL COMMENT '代码值父类型代码',
    `CDV_PARNT_CDE` VARCHAR(30) NULL COMMENT '代码值父代码',
    `REC_CMNT_TEXT` VARCHAR(100) NULL COMMENT '记录注释文本',
    `REC_CREAT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
    `REC_UPDT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `CDE_DESC_VALUE_UK1` (`CTRY_REC_CDE`, `GRP_MEMBR_REC_CDE`, `CDV_TYPE_CDE`, `CDV_CDE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='代码描述值表';

-- =====================================================
-- 2. 产品主表 - TB_PROD
-- =====================================================
DROP TABLE IF EXISTS `TB_PROD`;
CREATE TABLE `TB_PROD` (
    `CTRY_REC_CDE` CHAR(2) NOT NULL COMMENT '国家记录代码',
    `GRP_MEMBR_REC_CDE` CHAR(4) NOT NULL COMMENT '集团成员记录代码',
    `PROD_ID` DECIMAL(38,0) NOT NULL COMMENT '产品ID',
    `PROD_TYPE` CHAR(10) NULL COMMENT '产品类型',
    `PROD_TYPE_CDE` VARCHAR(15) NULL COMMENT '产品类型代码',
    `PROD_SUBTP_CDE` VARCHAR(30) NULL COMMENT '产品子类型代码',
    `PROD_CDE` VARCHAR(30) NOT NULL COMMENT '产品代码',
    `PROD_ALT_PRIM_NUM` VARCHAR(30) NULL COMMENT '产品替代主编号',
    `PROD_NAME` VARCHAR(100) NULL COMMENT '产品名称',
    `PROD_PLL_NAME` VARCHAR(300) NULL COMMENT '产品并行语言名称',
    `PROD_SLL_NAME` VARCHAR(300) NULL COMMENT '产品第二语言名称',
    `PROD_SHRT_NAME` VARCHAR(30) NULL COMMENT '产品简称',
    `PROD_SHRT_PLL_NAME` VARCHAR(90) NULL COMMENT '产品简称并行语言',
    `PROD_SHRT_SLL_NAME` VARCHAR(90) NULL COMMENT '产品简称第二语言',
    `PROD_DESC` VARCHAR(300) NULL COMMENT '产品描述',
    `PROD_PLL_DESC` VARCHAR(900) NULL COMMENT '产品描述并行语言',
    `PROD_SLL_DESC` VARCHAR(900) NULL COMMENT '产品描述第二语言',
    `ASET_CLASS_CDE` VARCHAR(15) NULL COMMENT '资产类别代码',
    `PROD_STAT_CDE` CHAR(1) NULL COMMENT '产品状态代码',
    `CCY_PROD_CDE` CHAR(3) NULL COMMENT '产品货币代码',
    `RISK_LVL_CDE` CHAR(1) NULL COMMENT '风险等级代码',
    `PRD_PROD_CDE` VARCHAR(15) NULL COMMENT '周期产品代码',
    `PRD_PROD_NUM` DECIMAL(38,0) NULL COMMENT '周期产品编号',
    `TERM_REMAIN_DAY_CNT` DECIMAL(38,0) NULL COMMENT '剩余期限天数',
    `PROD_LNCH_DT` DATE NULL COMMENT '产品发布日期',
    `PROD_MTUR_DT` DATE NULL COMMENT '产品到期日期',
    `MKT_INVST_CDE` VARCHAR(5) NULL COMMENT '市场投资代码',
    `SECT_INVST_CDE` VARCHAR(10) NULL COMMENT '行业投资代码',
    `ALLOW_BUY_PROD_IND` CHAR(1) NULL COMMENT '允许买入产品指示',
    `ALLOW_SELL_PROD_IND` CHAR(1) NULL COMMENT '允许卖出产品指示',
    `ALLOW_BUY_UT_PROD_IND` CHAR(1) NULL COMMENT '允许按单位买入产品指示',
    `ALLOW_BUY_AMT_PROD_IND` CHAR(1) NULL COMMENT '允许按金额买入产品指示',
    `ALLOW_SELL_UT_PROD_IND` CHAR(1) NULL COMMENT '允许按单位卖出产品指示',
    `ALLOW_SELL_AMT_PROD_IND` CHAR(1) NULL COMMENT '允许按金额卖出产品指示',
    `ALLOW_SELL_MIP_PROD_IND` CHAR(1) NULL COMMENT '允许卖出MIP产品指示',
    `ALLOW_SELL_MIP_UT_PROD_IND` CHAR(1) NULL COMMENT '允许按单位卖出MIP产品指示',
    `ALLOW_SELL_MIP_AMT_PROD_IND` CHAR(1) NULL COMMENT '允许按金额卖出MIP产品指示',
    `ALLOW_SW_IN_PROD_IND` CHAR(1) NULL COMMENT '允许转入产品指示',
    `ALLOW_SW_IN_UT_PROD_IND` CHAR(1) NULL COMMENT '允许按单位转入产品指示',
    `ALLOW_SW_IN_AMT_PROD_IND` CHAR(1) NULL COMMENT '允许按金额转入产品指示',
    `ALLOW_SW_OUT_PROD_IND` CHAR(1) NULL COMMENT '允许转出产品指示',
    `ALLOW_SW_OUT_UT_PROD_IND` CHAR(1) NULL COMMENT '允许按单位转出产品指示',
    `ALLOW_SW_OUT_AMT_PROD_IND` CHAR(1) NULL COMMENT '允许按金额转出产品指示',
    `INCM_CHAR_PROD_IND` CHAR(1) NULL COMMENT '收入特征产品指示',
    `CPTL_GURNT_PROD_IND` CHAR(1) NULL COMMENT '资本保证产品指示',
    `YIELD_ENHN_PROD_IND` CHAR(1) NULL COMMENT '收益增强产品指示',
    `GRWTH_CHAR_PROD_IND` CHAR(1) NULL COMMENT '成长特征产品指示',
    `PRTY_PROD_SRCH_RSULT_NUM` DECIMAL(38,0) NULL COMMENT '优先产品搜索结果编号',
    `AVAIL_MKT_INFO_IND` CHAR(1) NULL COMMENT '可用市场信息指示',
    `PRD_RTRN_AVG_NUM` DECIMAL(13,5) NULL COMMENT '周期回报平均数',
    `RTRN_VOLTL_AVG_PCT` DECIMAL(13,5) NULL COMMENT '回报波动平均百分比',
    `DMY_PROD_SUBTP_REC_IND` CHAR(1) NULL COMMENT '虚拟产品子类型记录指示',
    `DISP_COM_PROD_SRCH_IND` CHAR(1) NULL COMMENT '显示通用产品搜索指示',
    `MRK_TO_MKT_IND` CHAR(1) NULL COMMENT '按市价计价指示',
    `PROD_NARR_TEXT` VARCHAR(1200) NULL COMMENT '产品叙述文本',
    `CTRY_PROD_TRADE_1_CDE` CHAR(2) NULL COMMENT '国家产品交易1代码',
    `CTRY_PROD_TRADE_2_CDE` CHAR(2) NULL COMMENT '国家产品交易2代码',
    `CTRY_PROD_TRADE_3_CDE` CHAR(2) NULL COMMENT '国家产品交易3代码',
    `CTRY_PROD_TRADE_4_CDE` CHAR(2) NULL COMMENT '国家产品交易4代码',
    `CTRY_PROD_TRADE_5_CDE` CHAR(2) NULL COMMENT '国家产品交易5代码',
    `BUS_START_TM` TIMESTAMP(6) NULL COMMENT '业务开始时间',
    `BUS_END_TM` TIMESTAMP(6) NULL COMMENT '业务结束时间',
    `INTRO_PROD_CURR_PRD_IND` CHAR(1) NULL COMMENT '介绍产品当前周期指示',
    `PROD_TOP_SELL_RANK_NUM` DECIMAL(38,0) NULL COMMENT '产品热销排名编号',
    `PROD_TOP_PERFM_RANK_NUM` DECIMAL(38,0) NULL COMMENT '产品顶级表现排名编号',
    `PROD_TOP_YIELD_RANK_NUM` DECIMAL(38,0) NULL COMMENT '产品顶级收益排名编号',
    `PROD_ISSUE_CROS_REFER_DT` DATE NULL COMMENT '产品发行交叉参考日期',
    `PROD_CMNT_TEXT` VARCHAR(500) NULL COMMENT '产品注释文本',
    `CCY_INVST_CDE` CHAR(3) NULL COMMENT '投资货币代码',
    `BCHMK_NAME` VARCHAR(100) NULL COMMENT '基准名称',
    `BCHMK_PLL_NAME` VARCHAR(300) NULL COMMENT '基准并行语言名称',
    `BCHMK_SLL_NAME` VARCHAR(300) NULL COMMENT '基准第二语言名称',
    `TRD_FIRST_DT` DATE NULL COMMENT '首次交易日期',
    `LOAN_PROD_OD_MRGN_PCT` DECIMAL(20,6) NULL COMMENT '贷款产品透支保证金百分比',
    `QTY_UNIT_PROD_CDE` CHAR(3) NULL COMMENT '数量单位产品代码',
    `PROD_LOC_CDE` CHAR(3) NULL COMMENT '产品位置代码',
    `PROD_TAX_FREE_WRAP_ACT_STA_CDE` CHAR(1) NULL COMMENT '产品免税包装账户状态代码',
    `PRC_EFF_DT` DATE NULL COMMENT '价格生效日期',
    `CCY_PROD_MKT_PRC_CDE` CHAR(3) NULL COMMENT '产品市场价格货币代码',
    `PROD_BID_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品买入价格金额',
    `PROD_OFFR_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品卖出价格金额',
    `PROD_MKT_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品市场价格金额',
    `PROD_NAV_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品净值价格金额',
    `PROD_PRC_UPDT_DT_TM` TIMESTAMP(6) NULL COMMENT '产品价格更新时间',
    `DCML_PLACE_TRADE_UNIT_NUM` DECIMAL(38,0) NULL COMMENT '小数位交易单位数',
    `PROD_OFFR_CHANL_UPDT_DT_TM` TIMESTAMP(6) NULL COMMENT '产品提供渠道更新时间',
    `PLDG_LIMIT_ASSOC_ACCT_IND` CHAR(1) NULL COMMENT '质押限制关联账户指示',
    `PROD_OWN_CDE` CHAR(1) NULL COMMENT '产品拥有代码',
    `FORGN_PROD_IND` CHAR(1) NULL COMMENT '外国产品指示',
    `PROD_STAT_UPDT_DT_TM` TIMESTAMP(6) NULL COMMENT '产品状态更新时间',
    `ASET_CAT_EXTNL_CDE` VARCHAR(10) NULL COMMENT '资产类别外部代码',
    `PROD_MKT_PRICE_PREV_AMT` DECIMAL(21,6) NULL COMMENT '产品市场价格前一金额',
    `REC_CREAT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
    `REC_UPDT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
    `REC_ONLN_UPDT_DT_TM` TIMESTAMP(6) NULL COMMENT '记录在线更新时间',
    `PRC_INP_DT` DATE NULL COMMENT '价格输入日期',
    `CHRG_CAT_CDE` VARCHAR(15) NULL COMMENT '收费类别代码',
    `SUPT_RCBL_CASH_PROD_IND` CHAR(1) NULL COMMENT '支持应收现金产品指示',
    `SUPT_RCBL_SCRIP_PROD_IND` CHAR(1) NULL COMMENT '支持应收股票产品指示',
    `ASET_UNDER_MGMT_CHRG_PROD_IND` CHAR(1) NULL COMMENT '管理资产收费产品指示',
    `INVST_IMIG_PROD_IND` CHAR(1) NULL COMMENT '投资移民产品指示',
    `RESTR_INVSTR_PROD_IND` CHAR(1) NULL COMMENT '限制投资者产品指示',
    `PROD_INVST_OBJ_TEXT` VARCHAR(300) NULL COMMENT '产品投资目标文本',
    `INVST_INIT_MIN_AMT` DECIMAL(21,6) NULL COMMENT '投资初始最小金额',
    `NO_SCRIB_FEE_PROD_IND` CHAR(1) NULL COMMENT '无认购费产品指示',
    `TOP_SELL_PROD_IND` CHAR(1) NULL COMMENT '热销产品指示',
    `TOP_PERFM_PROD_IND` CHAR(1) NULL COMMENT '顶级表现产品指示',
    `INVST_INIT_MAX_AMT` DECIMAL(21,6) NULL COMMENT '投资初始最大金额',
    `RCMND_PROD_DECSN_CDE` VARCHAR(20) NULL COMMENT '推荐产品决策代码',
    `ASET_TEXT` VARCHAR(50) NULL COMMENT '资产文本',
    `PROD_DERVT_CDE` CHAR(1) NULL COMMENT '产品衍生品代码',
    `PROD_DERVT_RVS_CDE` CHAR(1) NULL COMMENT '产品衍生品逆向代码',
    `PRD_DERV_RVS_EFF_DT` DATE NULL COMMENT '周期衍生品逆向生效日期',
    `EQTY_UNDL_IND` CHAR(1) NULL COMMENT '股票标的指示',
    `WLTH_ACCUM_GOAL_IND` CHAR(1) NULL COMMENT '财富积累目标指示',
    `PRTY_WLTH_ACCUM_GOAL_CDE` CHAR(1) NULL COMMENT '优先财富积累目标代码',
    `PLAN_FOR_RTIRE_GOAL_IND` CHAR(1) NULL COMMENT '退休规划目标指示',
    `PRTY_PLN_FOR_RTIRE_CDE` CHAR(1) NULL COMMENT '优先退休规划代码',
    `EDUC_GOAL_IND` CHAR(1) NULL COMMENT '教育目标指示',
    `PRTY_EDUC_CDE` CHAR(1) NULL COMMENT '优先教育代码',
    `LIVE_IN_RTIRE_GOAL_IND` CHAR(1) NULL COMMENT '退休生活目标指示',
    `PRTY_LIVE_IN_RTIRE_CDE` CHAR(1) NULL COMMENT '优先退休生活代码',
    `PROTC_GOAL_IND` CHAR(1) NULL COMMENT '保护目标指示',
    `PRTY_PROTC_CDE` CHAR(1) NULL COMMENT '优先保护代码',
    `MNG_SOLN_IND` CHAR(1) NULL COMMENT '管理解决方案指示',
    `PRD_INVST_TNOR_NUM` DECIMAL(38,0) NULL COMMENT '周期投资期限数',
    `GEO_RISK_IND` CHAR(1) NULL COMMENT '地理风险指示',
    `PROD_LQDY_IND` CHAR(1) NULL COMMENT '产品流动性指示',
    `RVRSE_ENQ_PROD_IND` CHAR(1) NULL COMMENT '逆向查询产品指示',
    `PROD_INVST_TYPE_CDE` CHAR(3) NULL COMMENT '产品投资类型代码',
    `DIVR_NUM` DECIMAL(21,6) NULL COMMENT '分散数',
    `PRICE_HIST_SRCE_RDY_STAT_CDE` CHAR(10) NULL COMMENT '价格历史来源准备状态代码',
    `PRICE_HIST_DELVR_DT_TM` TIMESTAMP(6) NULL COMMENT '价格历史交付时间',
    `ISLM_PROD_IND` CHAR(1) NULL COMMENT '伊斯兰产品指示',
    `CNTL_ADVC_IND` CHAR(1) NULL COMMENT '控制建议指示',
    `ASET_VOLTL_CLASS_MAJR_PRNT_CDE` VARCHAR(30) NULL COMMENT '资产波动类别主要父代码',
    `REC_STGC_FIN_PLN_UPDT_DT_TM` TIMESTAMP(6) NULL COMMENT '记录战略财务计划更新时间',
    `PROD_PARNT_ID` DECIMAL(38,0) NULL COMMENT '产品父ID',
    PRIMARY KEY (`PROD_ID`),
    UNIQUE KEY `PROD_UK1` (`PROD_CDE`),
    KEY `PROD_IDX1` (`GRP_MEMBR_REC_CDE`, `CTRY_REC_CDE`, `PROD_ID`),
    KEY `PROD_IDX2` (`ASET_CLASS_CDE`, `PROD_ID`),
    KEY `PROD_IDX3` (`MKT_INVST_CDE`, `PROD_ID`),
    KEY `PROD_IDX4` (`TERM_REMAIN_DAY_CNT`, `PROD_ID`),
    KEY `PROD_IDX5` (`PROD_ALT_PRIM_NUM`, `GRP_MEMBR_REC_CDE`, `CTRY_REC_CDE`, `PROD_ID`),
    KEY `PROD_IDX6` (`PROD_PARNT_ID`),
    KEY `PROD_IDX7` (`PROD_STAT_CDE`, `PROD_TYPE_CDE`),
    KEY `PROD_IDX8` (`PROD_PRC_UPDT_DT_TM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品主表';

-- =====================================================
-- 3. 产品用户自定义扩展字段表 - TB_PROD_USER_DEFIN_EXT_FIELD
-- =====================================================
DROP TABLE IF EXISTS `TB_PROD_USER_DEFIN_EXT_FIELD`;
CREATE TABLE `TB_PROD_USER_DEFIN_EXT_FIELD` (
    `ROWID` VARCHAR(100) NOT NULL COMMENT '行ID',
    `PROD_ID` DECIMAL(38,0) NOT NULL COMMENT '产品ID',
    `FIELD_TYPE_CDE` CHAR(1) NOT NULL COMMENT '字段类型代码',
    `FIELD_CDE` VARCHAR(30) NOT NULL COMMENT '字段代码',
    `FIELD_SEQ_NUM` DECIMAL(38,0) NOT NULL COMMENT '字段序号',
    `CTRY_REC_CDE` CHAR(2) NOT NULL COMMENT '国家记录代码',
    `GRP_MEMBR_REC_CDE` CHAR(4) NOT NULL COMMENT '集团成员记录代码',
    `FIELD_DATA_TYPE_TEXT` VARCHAR(15) NOT NULL COMMENT '字段数据类型文本',
    `FIELD_CHAR_VALUE_TEXT` CHAR(1) NULL COMMENT '字段字符值文本',
    `FIELD_STRNG_VALUE_TEXT` VARCHAR(4000) NULL COMMENT '字段字符串值文本',
    `FIELD_INTG_VALUE_NUM` DECIMAL(38,0) NULL COMMENT '字段整数值',
    `FIELD_DCML_VALUE_NUM` DECIMAL(21,6) NULL COMMENT '字段小数值',
    `FIELD_DT_VALUE_DT` DATE NULL COMMENT '字段日期值',
    `FIELD_TS_VALUE_DT_TM` TIMESTAMP(6) NULL COMMENT '字段时间戳值',
    `REC_CREAT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
    `REC_UPDT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
    PRIMARY KEY (`ROWID`),
    UNIQUE KEY `PROD_USER_DEFIN_EXT_FIELD_UK1` (`PROD_ID`, `FIELD_TYPE_CDE`, `FIELD_CDE`, `FIELD_SEQ_NUM`),
    KEY `PROD_USER_DEFIN_EXT_FIELD_IDX1` (`PROD_ID`),
    KEY `PROD_USER_DEFIN_EXT_FIELD_IDX2` (`FIELD_TYPE_CDE`, `FIELD_CDE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品用户自定义扩展字段表';

-- =====================================================
-- 4. 债券工具表 - TB_DEBT_INSTM
-- =====================================================
DROP TABLE IF EXISTS `TB_DEBT_INSTM`;
CREATE TABLE `TB_DEBT_INSTM` (
    `PROD_ID_DEBT_INSTM` DECIMAL(38,0) NOT NULL COMMENT '债券工具产品ID',
    `ISR_BOND_NAME` VARCHAR(70) NULL COMMENT '发行人债券名称',
    `ISSUE_NUM` VARCHAR(40) NULL COMMENT '发行编号',
    `PROD_ISS_DT` DATE NULL COMMENT '产品发行日期',
    `PDCY_COUPN_PYMT_CDE` CHAR(1) NULL COMMENT '周期性票息支付代码',
    `COUPN_ANNL_RATE` DECIMAL(20,6) NULL COMMENT '票息年利率',
    `COUPN_EXT_INSTM_RATE` DECIMAL(20,6) NULL COMMENT '票息外部工具利率',
    `PYMT_COUPN_NEXT_DT` DATE NULL COMMENT '下次票息支付日期',
    `FLEX_MAT_OPT_IND` CHAR(1) NULL COMMENT '灵活到期选择指示',
    `INT_IND_ACCR_AMT` DECIMAL(25,10) NULL COMMENT '利息指示应计金额',
    `INVST_INCRM_MIN_AMT` DECIMAL(21,6) NULL COMMENT '投资增量最小金额',
    `PROD_BOD_LOT_QTY_CNT` DECIMAL(20,6) NULL COMMENT '产品董事会批量数量',
    `MTUR_EXT_DT` DATE NULL COMMENT '到期延期日期',
    `SUB_DEBT_IND` CHAR(1) NULL COMMENT '次级债务指示',
    `BOND_STAT_CDE` CHAR(1) NULL COMMENT '债券状态代码',
    `CTRY_BOND_ISSUE_CDE` CHAR(2) NULL COMMENT '债券发行国家代码',
    `GRNTR_NAME` VARCHAR(100) NULL COMMENT '担保人名称',
    `CPTL_TIER_TEXT` VARCHAR(100) NULL COMMENT '资本层级文本',
    `COUPN_TYPE` VARCHAR(20) NULL COMMENT '票息类型',
    `COUPN_PREV_RATE` DECIMAL(20,6) NULL COMMENT '票息前一利率',
    `INDEX_FLT_RATE_NAME` VARCHAR(50) NULL COMMENT '指数浮动利率名称',
    `BOND_FLT_SPRD_RATE` DECIMAL(20,4) NULL COMMENT '债券浮动利差率',
    `COUPN_CURR_START_DT` DATE NULL COMMENT '票息当前开始日期',
    `COUPN_PREV_START_DT` DATE NULL COMMENT '票息前一开始日期',
    `BOND_CALL_NEXT_DT` DATE NULL COMMENT '债券下次赎回日期',
    `INT_BASIS_CALC_TEXT` VARCHAR(100) NULL COMMENT '利息基础计算文本',
    `INT_ACCR_DAY_CNT` DECIMAL(20,6) NULL COMMENT '利息应计天数',
    `INVST_SOLD_LEST_AMT` DECIMAL(21,6) NULL COMMENT '投资卖出最少金额',
    `INVST_INCRM_SOLD_AMT` DECIMAL(21,6) NULL COMMENT '投资增量卖出金额',
    `SHR_BID_CNT` DECIMAL(20,6) NULL COMMENT '股份买入数量',
    `SHR_OFFR_CNT` DECIMAL(20,6) NULL COMMENT '股份卖出数量',
    `PROD_CLOSE_BID_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品收盘买入价格金额',
    `PROD_CLOSE_OFFR_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品收盘卖出价格金额',
    `BOND_CLOSE_DT` DATE NULL COMMENT '债券收盘日期',
    `BOND_SETL_DT` DATE NULL COMMENT '债券结算日期',
    `DSCNT_MRGN_BSEL_PCT` DECIMAL(20,4) NULL COMMENT '折扣保证金基础卖出百分比',
    `DSCNT_MRGN_BBUY_PCT` DECIMAL(20,4) NULL COMMENT '折扣保证金基础买入百分比',
    `PRC_BOND_RECV_DT_TM` TIMESTAMP(6) NULL COMMENT '债券价格接收时间',
    `YIELD_OFFER_TEXT` VARCHAR(100) NULL COMMENT '收益率报价文本',
    `COUPN_ANNL_TEXT` VARCHAR(100) NULL COMMENT '票息年度文本',
    `YIELD_EFF_DT` DATE NULL COMMENT '收益率生效日期',
    `YIELD_BID_PCT` DECIMAL(20,6) NULL COMMENT '收益率买入百分比',
    `YIELD_TO_CALL_BID_PCT` DECIMAL(20,6) NULL COMMENT '到期赎回收益率买入百分比',
    `YIELD_TO_MTUR_BID_PCT` DECIMAL(20,6) NULL COMMENT '到期收益率买入百分比',
    `YIELD_BID_CLOSE_PCT` DECIMAL(20,6) NULL COMMENT '收益率买入收盘百分比',
    `YIELD_OFFER_PCT` DECIMAL(20,6) NULL COMMENT '收益率卖出百分比',
    `YIELD_TO_CALL_OFFER_PCT` DECIMAL(20,6) NULL COMMENT '到期赎回收益率卖出百分比',
    `YIELD_TO_MTUR_OFFER_TEXT` VARCHAR(100) NULL COMMENT '到期收益率卖出文本',
    `YIELD_OFFER_CLOSE_PCT` DECIMAL(20,6) NULL COMMENT '收益率卖出收盘百分比',
    `YIELD_DT` DATE NULL COMMENT '收益率日期',
    `ISR_DESC` VARCHAR(300) NULL COMMENT '发行人描述',
    `SR_TYPE_CDE` VARCHAR(6) NULL COMMENT '高级类型代码',
    `PROD_GBM_BID_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品GBM买入价格金额',
    `PROD_GBM_OFFR_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品GBM卖出价格金额',
    PRIMARY KEY (`PROD_ID_DEBT_INSTM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='债券工具表';

-- =====================================================
-- 5. 股票挂钩投资表 - TB_EQTY_LINK_INVST
-- =====================================================
DROP TABLE IF EXISTS `TB_EQTY_LINK_INVST`;
CREATE TABLE `TB_EQTY_LINK_INVST` (
    `PROD_ID_EQTY_LINK_INVST` DECIMAL(38,0) NOT NULL COMMENT '股票挂钩投资产品ID',
    `PROD_EXTNL_CDE` VARCHAR(30) NULL COMMENT '产品外部代码',
    `PROD_EXTNL_TYPE_CDE` VARCHAR(30) NULL COMMENT '产品外部类型代码',
    `EQTY_LINK_INVST_TYPE_CDE` VARCHAR(30) NULL COMMENT '股票挂钩投资类型代码',
    `TRD_DT` DATE NULL COMMENT '交易日期',
    `DSCNT_BUY_PCT` DECIMAL(20,4) NULL COMMENT '折扣买入百分比',
    `DSCNT_SELL_PCT` DECIMAL(20,4) NULL COMMENT '折扣卖出百分比',
    `YIELD_TO_MTUR_PCT` DECIMAL(20,6) NULL COMMENT '到期收益率百分比',
    `DEN_AMT` DECIMAL(18,3) NULL COMMENT '面额金额',
    `TRD_MIN_AMT` DECIMAL(18,3) NULL COMMENT '交易最小金额',
    `SUPT_AON_IND` CHAR(1) NULL COMMENT '支持全部或无指示',
    `PYMT_DT` DATE NULL COMMENT '支付日期',
    `VALN_DT` DATE NULL COMMENT '估值日期',
    `OFFER_TYPE_CDE` VARCHAR(15) NULL COMMENT '报价类型代码',
    `CUST_SELL_QTA_CNT` DECIMAL(38,0) NULL COMMENT '客户卖出配额数量',
    `RULE_QTA_ALTMT_CDE` VARCHAR(15) NULL COMMENT '规则配额分配代码',
    `SETL_DT` DATE NULL COMMENT '结算日期',
    `LNCH_PROD_IND` CHAR(1) NULL COMMENT '发布产品指示',
    `RTRV_PROD_EXTNL_IND` CHAR(1) NULL COMMENT '检索产品外部指示',
    `PROD_EXTNL_CAT_CDE` VARCHAR(10) NULL COMMENT '产品外部类别代码',
    `PDCY_CALL_CDE` CHAR(1) NULL COMMENT '周期性赎回代码',
    `PDCY_KNOCK_IN_CDE` CHAR(1) NULL COMMENT '周期性敲入代码',
    PRIMARY KEY (`PROD_ID_EQTY_LINK_INVST`),
    KEY `EQTY_LINK_INVST_IDX1` (`YIELD_TO_MTUR_PCT`, `PROD_ID_EQTY_LINK_INVST`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='股票挂钩投资表';

-- =====================================================
-- 6. 产品表单要求表 - PROD_FORM_REQMT
-- =====================================================
DROP TABLE IF EXISTS `PROD_FORM_REQMT`;
CREATE TABLE `PROD_FORM_REQMT` (
    `ROWID` VARCHAR(100) NOT NULL COMMENT '行ID',
    `PROD_ID` DECIMAL(38,0) NOT NULL COMMENT '产品ID',
    `FORM_REQ_CDE` VARCHAR(30) NOT NULL COMMENT '表单要求代码',
    `REC_CREAT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
    PRIMARY KEY (`ROWID`),
    UNIQUE KEY `PROD_FORM_REQMT_UK1` (`PROD_ID`, `FORM_REQ_CDE`),
    KEY `PROD_FORM_REQMT_IDX1` (`PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品表单要求表';

-- =====================================================
-- 7. 产品限制客户国家表 - PROD_RESTR_CUST_CTRY
-- =====================================================
DROP TABLE IF EXISTS `PROD_RESTR_CUST_CTRY`;
CREATE TABLE `PROD_RESTR_CUST_CTRY` (
    `ROWID` VARCHAR(100) NOT NULL COMMENT '行ID',
    `PROD_ID` DECIMAL(38,0) NOT NULL COMMENT '产品ID',
    `CTRY_ISO_CDE` CHAR(2) NOT NULL COMMENT '国家ISO代码',
    `RESTR_CTRY_TYPE_CDE` CHAR(1) NOT NULL COMMENT '限制国家类型代码',
    `RESTR_CDE` CHAR(1) NULL COMMENT '限制代码',
    `REC_CREAT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
    `REC_UPDT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
    PRIMARY KEY (`ROWID`),
    UNIQUE KEY `PROD_RESTR_CUST_CTRY_UK1` (`PROD_ID`, `CTRY_ISO_CDE`, `RESTR_CTRY_TYPE_CDE`),
    KEY `PROD_RESTR_CUST_CTRY_IDX1` (`PROD_ID`),
    KEY `PROD_RESTR_CUST_CTRY_IDX2` (`CTRY_ISO_CDE`, `RESTR_CTRY_TYPE_CDE`, `RESTR_CDE`, `PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品限制客户国家表';

-- =====================================================
-- 8. 产品替代ID表 - TB_PROD_ALT_ID
-- =====================================================
DROP TABLE IF EXISTS `TB_PROD_ALT_ID`;
CREATE TABLE `TB_PROD_ALT_ID` (
    `ROWID` VARCHAR(100) NOT NULL COMMENT '行ID',
    `CTRY_REC_CDE` CHAR(2) NOT NULL COMMENT '国家记录代码',
    `GRP_MEMBR_REC_CDE` CHAR(4) NOT NULL COMMENT '集团成员记录代码',
    `PROD_ID` DECIMAL(38,0) NOT NULL COMMENT '产品ID',
    `PROD_CDE_ALT_CLASS_CDE` CHAR(1) NOT NULL COMMENT '产品代码替代类别代码',
    `PROD_TYPE_CDE` VARCHAR(15) NOT NULL COMMENT '产品类型代码',
    `PROD_ALT_NUM` VARCHAR(30) NOT NULL COMMENT '产品替代编号',
    `REC_CREAT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
    `REC_UPDT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
    PRIMARY KEY (`ROWID`),
    UNIQUE KEY `PROD_ALT_ID_UK1` (`PROD_ID`, `PROD_CDE_ALT_CLASS_CDE`),
    KEY `PROD_ALT_ID_IDX1` (`PROD_ID`),
    KEY `PROD_ALT_ID_IDX2` (`PROD_ALT_NUM`, `PROD_CDE_ALT_CLASS_CDE`, `GRP_MEMBR_REC_CDE`, `CTRY_REC_CDE`, `PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品替代ID表';

-- =====================================================
-- 9. 股票挂钩投资标的股票表 - TB_EQTY_LINK_INVST_UNDL_STOCK
-- =====================================================
DROP TABLE IF EXISTS `TB_EQTY_LINK_INVST_UNDL_STOCK`;
CREATE TABLE `TB_EQTY_LINK_INVST_UNDL_STOCK` (
    `ROWID` VARCHAR(100) NOT NULL COMMENT '行ID',
    `PROD_ID_EQTY_LINK_INVST` DECIMAL(38,0) NOT NULL COMMENT '股票挂钩投资产品ID',
    `INSTM_UNDL_CDE` VARCHAR(30) NOT NULL COMMENT '工具标的代码',
    `INSTM_UNDL_TEXT` VARCHAR(80) NULL COMMENT '工具标的文本',
    `CRNCY_INSTM_UNDL_PRICE_CDE` CHAR(3) NULL COMMENT '工具标的价格货币代码',
    `PROD_STRK_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品行权价格金额',
    `PROD_STRK_CALL_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品行权看涨价格金额',
    `PROD_STRK_PUT_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品行权看跌价格金额',
    `PROD_CLOSE_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品收盘价格金额',
    `PROD_CLOSE_LOW_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品收盘最低价格金额',
    `PROD_CLOSE_UPPR_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品收盘最高价格金额',
    `PROD_CLOSE_PUT_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品收盘看跌价格金额',
    `PROD_CLOSE_CALL_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品收盘看涨价格金额',
    `PROD_EXER_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品行使价格金额',
    `PROD_BREAK_EVEN_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品盈亏平衡价格金额',
    `PROD_BREAK_EVEN_LOW_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品盈亏平衡最低价格金额',
    `PROD_BREAK_EVEN_UPPR_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品盈亏平衡最高价格金额',
    `PROD_BREAK_EVEN_PUT_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品盈亏平衡看跌价格金额',
    `PROD_BREAK_EVEN_CALL_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品盈亏平衡看涨价格金额',
    `SPRD_CNT` DECIMAL(38,0) NULL COMMENT '价差数量',
    `INSTM_ENTL_CNT` DECIMAL(16,4) NULL COMMENT '工具权利数量',
    `PROD_KNOCK_IN_PRICE_AMT` DECIMAL(21,6) NULL COMMENT '产品敲入价格金额',
    `PROD_STRK_PRICE_INIT_PCT` DECIMAL(13,5) NULL COMMENT '产品行权价格初始百分比',
    `PROD_STRK_CALL_PRICE_INIT_PCT` DECIMAL(13,5) NULL COMMENT '产品行权看涨价格初始百分比',
    `PROD_KNOCK_IN_PRICE_INIT_PCT` DECIMAL(13,5) NULL COMMENT '产品敲入价格初始百分比',
    `REC_CREAT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
    `REC_UPDT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '记录更新时间',
    `PROD_ID_UNDL_INSTM` DECIMAL(38,0) NOT NULL COMMENT '标的工具产品ID',
    `PROD_INIT_SPOT_PRICE_AMT` DECIMAL(21,6) NULL COMMENT '产品初始现货价格金额',
    `PROD_FLR_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品底价金额',
    `PROD_BAR_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品障碍价格金额',
    `PROD_KNOCK_IN_TRIG_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品敲入触发价格金额',
    `PROD_EARL_CALL_TRIG_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品提前赎回触发价格金额',
    `PROD_EXPI_CLOSE_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品到期收盘价格金额',
    `PROD_DOWN_OUT_BAR_PRC_AMT` DECIMAL(21,6) NULL COMMENT '产品向下敲出障碍价格金额',
    PRIMARY KEY (`ROWID`),
    UNIQUE KEY `EQTY_LINK_INVST_UNDL_STOCK_UK1` (`PROD_ID_EQTY_LINK_INVST`, `INSTM_UNDL_CDE`),
    KEY `EQTY_LINK_INVST_UNDL_STOCK_IDX1` (`PROD_ID_EQTY_LINK_INVST`),
    KEY `EQTY_LINK_INVST_UNDL_STOCK_IDX2` (`PROD_ID_UNDL_INSTM`, `PROD_ID_EQTY_LINK_INVST`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='股票挂钩投资标的股票表';

-- =====================================================
-- 10. 股票挂钩投资日志表 - LOG_EQTY_LINK_INVST
-- =====================================================
DROP TABLE IF EXISTS `LOG_EQTY_LINK_INVST`;
CREATE TABLE `LOG_EQTY_LINK_INVST` (
    `ROWID` VARCHAR(100) NOT NULL COMMENT '行ID',
    `LOG_ID` DECIMAL(38,0) NOT NULL COMMENT '日志ID',
    `PROC_NAME` VARCHAR(30) NOT NULL COMMENT '过程名称',
    `LOG_LEVEL` VARCHAR(10) NOT NULL COMMENT '日志级别',
    `LOG_MSG` VARCHAR(4000) NOT NULL COMMENT '日志消息',
    `SQL_ERRM` VARCHAR(1000) NULL COMMENT 'SQL错误消息',
    `ERRM_STAT` VARCHAR(10) NULL COMMENT '错误消息状态',
    `CTRY_CDE` VARCHAR(2) NULL COMMENT '国家代码',
    `ORGN_CDE` VARCHAR(4) NULL COMMENT '组织代码',
    `PROD_ID` VARCHAR(30) NULL COMMENT '产品ID',
    `LOG_DATE` TIMESTAMP(6) NULL COMMENT '日志日期',
    PRIMARY KEY (`ROWID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='股票挂钩投资日志表';

-- =====================================================
-- 11. 产品覆盖字段表 - PROD_OVRID_FIELD
-- =====================================================
DROP TABLE IF EXISTS `PROD_OVRID_FIELD`;
CREATE TABLE `PROD_OVRID_FIELD` (
    `ROWID` VARCHAR(100) NOT NULL COMMENT '行ID',
    `PROD_ID` DECIMAL(38,0) NOT NULL COMMENT '产品ID',
    `FIELD_CDE` VARCHAR(30) NOT NULL COMMENT '字段代码',
    `REC_CREAT_DT_TM` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '记录创建时间',
    PRIMARY KEY (`ROWID`),
    UNIQUE KEY `PROD_OVRID_FIELD_UK1` (`PROD_ID`, `FIELD_CDE`),
    KEY `PROD_OVRID_FIELD_IDX1` (`PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品覆盖字段表';

-- =====================================================
-- 外键约束
-- =====================================================
-- 添加外键约束
ALTER TABLE `TB_PROD_USER_DEFIN_EXT_FIELD`
ADD CONSTRAINT `FK_PROD_USER_DEFIN_EXT_FIELD_PROD`
FOREIGN KEY (`PROD_ID`) REFERENCES `TB_PROD` (`PROD_ID`) ON DELETE CASCADE;

ALTER TABLE `TB_DEBT_INSTM`
ADD CONSTRAINT `FK_DEBT_INSTM_PROD`
FOREIGN KEY (`PROD_ID_DEBT_INSTM`) REFERENCES `TB_PROD` (`PROD_ID`) ON DELETE CASCADE;

ALTER TABLE `TB_EQTY_LINK_INVST`
ADD CONSTRAINT `FK_EQTY_LINK_INVST_PROD`
FOREIGN KEY (`PROD_ID_EQTY_LINK_INVST`) REFERENCES `TB_PROD` (`PROD_ID`) ON DELETE CASCADE;

ALTER TABLE `PROD_FORM_REQMT`
ADD CONSTRAINT `FK_PROD_FORM_REQMT_PROD`
FOREIGN KEY (`PROD_ID`) REFERENCES `TB_PROD` (`PROD_ID`) ON DELETE CASCADE;

ALTER TABLE `PROD_RESTR_CUST_CTRY`
ADD CONSTRAINT `FK_PROD_RESTR_CUST_CTRY_PROD`
FOREIGN KEY (`PROD_ID`) REFERENCES `TB_PROD` (`PROD_ID`) ON DELETE CASCADE;

ALTER TABLE `TB_PROD_ALT_ID`
ADD CONSTRAINT `FK_PROD_ALT_ID_PROD`
FOREIGN KEY (`PROD_ID`) REFERENCES `TB_PROD` (`PROD_ID`) ON DELETE CASCADE;

ALTER TABLE `TB_EQTY_LINK_INVST_UNDL_STOCK`
ADD CONSTRAINT `FK_EQTY_LINK_INVST_UNDL_STOCK_EQTY`
FOREIGN KEY (`PROD_ID_EQTY_LINK_INVST`) REFERENCES `TB_EQTY_LINK_INVST` (`PROD_ID_EQTY_LINK_INVST`) ON DELETE CASCADE;

ALTER TABLE `TB_EQTY_LINK_INVST_UNDL_STOCK`
ADD CONSTRAINT `FK_EQTY_LINK_INVST_UNDL_STOCK_UNDL`
FOREIGN KEY (`PROD_ID_UNDL_INSTM`) REFERENCES `TB_PROD` (`PROD_ID`);

ALTER TABLE `PROD_OVRID_FIELD`
ADD CONSTRAINT `FK_PROD_OVRID_FIELD_PROD`
FOREIGN KEY (`PROD_ID`) REFERENCES `TB_PROD` (`PROD_ID`) ON DELETE CASCADE;

-- 产品父子关系外键
ALTER TABLE `TB_PROD`
ADD CONSTRAINT `FK_PROD_PARENT`
FOREIGN KEY (`PROD_PARNT_ID`) REFERENCES `TB_PROD` (`PROD_ID`);

-- 恢复外键检查
SET FOREIGN_KEY_CHECKS = 1;

-- =====================================================
-- 创建完成提示
-- =====================================================
SELECT 'Cognos Tables Created Successfully in MySQL!' AS STATUS;
