market-hour:
  session-info:
    SHAS:
      1: 09:30:00-11:30:00,13:00:00-15:00:00
      2: 09:30:00-11:30:00,13:00:00-15:00:00
      3: 09:30:00-11:30:00,13:00:00-15:00:00
      4: 09:30:00-11:30:00,13:00:00-15:00:00
      5: 09:30:00-11:30:00,13:00:00-15:00:00
    SZAS:
      1: 09:30:00-11:30:00,13:00:00-15:00:00
      2: 09:30:00-11:30:00,13:00:00-15:00:00
      3: 09:30:00-11:30:00,13:00:00-15:00:00
      4: 09:30:00-11:30:00,13:00:00-15:00:00
      5: 09:30:00-11:30:00,13:00:00-15:00:00
    SEHK:
      1: 09:00:00-12:15:00,13:00:00-16:25:00
      2: 09:00:00-12:15:00,13:00:00-16:25:00
      3: 09:00:00-12:15:00,13:00:00-16:25:00
      4: 09:00:00-12:15:00,13:00:00-16:25:00
      5: 09:00:00-12:15:00,13:00:00-16:25:00
  timezone:
    DEFAULT: GMT+8
    SHAS: Asia/Shanghai
    SZAS: Asia/Shanghai
    SEHK: Asia/Shanghai
  marketDelayClose:
    DEFAULT: 0
    SHAS: 15
    SZAS: 15
  holiday:
    DEFAULT:
      DEFAULT:
        DEFAULT:
          DEFAULT:
    SHAS:
      2022:
        20220103:
          tradinghour:
          desc:
        20220131:
          tradinghour:
          desc:
        20220201:
          tradinghour:
          desc:
        20220202:
          tradinghour:
          desc:
        20220203:
          tradinghour:
          desc:
        20220204:
          tradinghour:
          desc:
        20220404:
          tradinghour:
          desc:
        20220405:
          tradinghour:
          desc:
        20220502:
          tradinghour:
          desc:
        20220503:
          tradinghour:
          desc:
        20220504:
          tradinghour:
          desc:
        20220603:
          tradinghour:
          desc:
        20220912:
          tradinghour:
          desc:
        20221003:
          tradinghour:
          desc:
        20221004:
          tradinghour:
          desc:
        20221005:
          tradinghour:
          desc:
        20221006:
          tradinghour:
          desc:
        20221007:
          tradinghour:
          desc:
      2023:
        20230102:
          tradinghour:
          desc:
        20230123:
          tradinghour:
          desc:
        20230124:
          tradinghour:
          desc:
        20230125:
          tradinghour:
          desc:
        20230126:
          tradinghour:
          desc:
        20230127:
          tradinghour:
          desc:
        20230405:
          tradinghour:
          desc:
        20230501:
          tradinghour:
          desc:
        20230502:
          tradinghour:
          desc:
        20230503:
          tradinghour:
          desc:
        20230622:
          tradinghour:
          desc:
        20230623:
          tradinghour:
          desc:
        20230929:
          tradinghour:
          desc:
        20231002:
          tradinghour:
          desc:
        20231003:
          tradinghour:
          desc:
        20231004:
          tradinghour:
          desc:
        20231005:
          tradinghour:
          desc:
        20231006:
          tradinghour:
          desc:
      2024:
        20240101:
          tradinghour:
          desc:
        20240209:
          tradinghour:
          desc:
        20240212:
          tradinghour:
          desc:
        20240213:
          tradinghour:
          desc:
        20240214:
          tradinghour:
          desc:
        20240215:
          tradinghour:
          desc:
        20240216:
          tradinghour:
          desc:
        20240404:
          tradinghour:
          desc:
        20240405:
          tradinghour:
          desc:
        20240501:
          tradinghour:
          desc:
        20240502:
          tradinghour:
          desc:
        20240503:
          tradinghour:
          desc:
        20240610:
          tradinghour:
          desc:
        20240916:
          tradinghour:
          desc:
        20240917:
          tradinghour:
          desc:
        20241001:
          tradinghour:
          desc:
        20241002:
          tradinghour:
          desc:
        20241003:
          tradinghour:
          desc:
        20241004:
          tradinghour:
          desc:
        20241007:
          tradinghour:
          desc:
      2025:
        20250101:
          tradinghour:
          desc:
        20250128:
          tradinghour:
          desc:
        20250129:
          tradinghour:
          desc:
        20250130:
          tradinghour:
          desc:
        20250131:
          tradinghour:
          desc:
        20250203:
          tradinghour:
          desc:
        20250204:
          tradinghour:
          desc:
        20250404:
          tradinghour:
          desc:
        20250501:
          tradinghour:
          desc:
        20250502:
          tradinghour:
          desc:
        20250505:
          tradinghour:
          desc:
        20250602:
          tradinghour:
          desc:
        20251001:
          tradinghour:
          desc:
        20251002:
          tradinghour:
          desc:
        20251003:
          tradinghour:
          desc:
        20251006:
          tradinghour:
          desc:
        20251007:
          tradinghour:
          desc:
        20251008:
          tradinghour:
          desc:
    SZAS:
      2022:
        20220103:
          tradinghour:
          desc:
        20220131:
          tradinghour:
          desc:
        20220201:
          tradinghour:
          desc:
        20220202:
          tradinghour:
          desc:
        20220203:
          tradinghour:
          desc:
        20220204:
          tradinghour:
          desc:
        20220404:
          tradinghour:
          desc:
        20220405:
          tradinghour:
          desc:
        20220502:
          tradinghour:
          desc:
        20220503:
          tradinghour:
          desc:
        20220504:
          tradinghour:
          desc:
        20220603:
          tradinghour:
          desc:
        20220912:
          tradinghour:
          desc:
        20221003:
          tradinghour:
          desc:
        20221004:
          tradinghour:
          desc:
        20221005:
          tradinghour:
          desc:
        20221006:
          tradinghour:
          desc:
        20221007:
          tradinghour:
          desc:
      2023:
        20230102:
          tradinghour:
          desc:
        20230123:
          tradinghour:
          desc:
        20230124:
          tradinghour:
          desc:
        20230125:
          tradinghour:
          desc:
        20230126:
          tradinghour:
          desc:
        20230127:
          tradinghour:
          desc:
        20230405:
          tradinghour:
          desc:
        20230501:
          tradinghour:
          desc:
        20230502:
          tradinghour:
          desc:
        20230503:
          tradinghour:
          desc:
        20230622:
          tradinghour:
          desc:
        20230623:
          tradinghour:
          desc:
        20230929:
          tradinghour:
          desc:
        20231002:
          tradinghour:
          desc:
        20231003:
          tradinghour:
          desc:
        20231004:
          tradinghour:
          desc:
        20231005:
          tradinghour:
          desc:
        20231006:
          tradinghour:
          desc:
      2024:
        20240101:
          tradinghour:
          desc:
        20240209:
          tradinghour:
          desc:
        20240212:
          tradinghour:
          desc:
        20240213:
          tradinghour:
          desc:
        20240214:
          tradinghour:
          desc:
        20240215:
          tradinghour:
          desc:
        20240216:
          tradinghour:
          desc:
        20240404:
          tradinghour:
          desc:
        20240405:
          tradinghour:
          desc:
        20240501:
          tradinghour:
          desc:
        20240502:
          tradinghour:
          desc:
        20240503:
          tradinghour:
          desc:
        20240610:
          tradinghour:
          desc:
        20240916:
          tradinghour:
          desc:
        20240917:
          tradinghour:
          desc:
        20241001:
          tradinghour:
          desc:
        20241002:
          tradinghour:
          desc:
        20241003:
          tradinghour:
          desc:
        20241004:
          tradinghour:
          desc:
        20241007:
          tradinghour:
          desc:
      2025:
        20250101:
          tradinghour:
          desc:
        20250128:
          tradinghour:
          desc:
        20250129:
          tradinghour:
          desc:
        20250130:
          tradinghour:
          desc:
        20250131:
          tradinghour:
          desc:
        20250203:
          tradinghour:
          desc:
        20250204:
          tradinghour:
          desc:
        20250404:
          tradinghour:
          desc:
        20250501:
          tradinghour:
          desc:
        20250502:
          tradinghour:
          desc:
        20250505:
          tradinghour:
          desc:
        20250602:
          tradinghour:
          desc:
        20251001:
          tradinghour:
          desc:
        20251002:
          tradinghour:
          desc:
        20251003:
          tradinghour:
          desc:
        20251006:
          tradinghour:
          desc:
        20251007:
          tradinghour:
          desc:
        20251008:
          tradinghour:
          desc:
  special:
    DEFAULT:
      DEFAULT:
        DEFAULT:
          DEFAULT:
  delayed:
    DEFAULT:
      DEFAULT: DEFAULT



