jasypt:
  encryptor:
    password: "HaSe?StMaPS7RTQ,TwPnO+ct4fbt6c-TEZQw3T8q.5OSN0k="
##########
spring:
  datasource: 
    name: oracle-equity-hase-stma
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@xp02-scan.gss4.hk.hhhh:2000/mdb02po1_onl.hk.hhhh
#    url: jdbc:oracle:thin:@(DESCRIPTION_LIST=(LOAD_BALANCE=off)(FAILOVER=on)(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xp02-scan.gss4.hk.hhhh)(PORT=2000)))(CONNECT_DATA=(SERVICE_NAME=mdb02po1_onl.hk.hhhh)))(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xc0201-scan.gss4.hk.hhhh)(PORT=2000)))(CONNECT_DATA=(SERVICE_NAME=mdb02po1_onl.hk.hhhh))))
#    url: jdbc:oracle:thin:@xu01-scan.p2g.netd.hk.hhhh:2000/mkd02uo1.hk.hhhh
#    username: MKD01UA2_APPUSER
#    password: ENC(8i//Vo3QnDc19LMxALvYydabSurLhXSoUg49bECgE2M=)
    # PROD VIP DB
#    url: jdbc:oracle:thin:@(DESCRIPTION_LIST=(LOAD_BALANCE=off)(FAILOVER=on)(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xp0201-vip.hk.hhhh)(PORT=2000)))(CONNECT_DATA=(SERVICE_NAME=mdb02po1_onl.hk.hhhh)))(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=xc0202-vip.hk.hhhh)(PORT=2000)))(CONNECT_DATA=(SERVICE_NAME=mdb02po1_onl.hk.hhhh))))
    # AWS PROD DB
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=hase-prod-wporcl01.wealth-platform-hase.ape1.prod.aws.cloud.hhhh)(PORT=2001)))(CONNECT_DATA=(SID=PHSEWP01)))
    username: MDB02PA1_APPUSER02
    password: ENC(BG/QKa6CPs2P2uvsNVMvddKzjG14hm8L)
  profiles:
    include: hase_stma_marketHour,hase_stma_api_support


##########
name: 
  id: 
    enable: false


connection:
  NON_PROXY:
    maxTotal: 500
    maxPerRoute: 300
    connectTimeout: 3000
    socketTimeout: 5000
    enableProxy: false
    proxyHostname:
    proxyPort:
    retryCount: 5
    enableGzip: true
  ETNET_PROXY:
    maxTotal: 500
    maxPerRoute: 300
    connectTimeout: 3000
    socketTimeout: 5000
    enableProxy: true
    proxyHostname: intpxy6.hk.hhhh
    proxyPort: 18084
    retryCount: 5
    enableGzip: false
  HK_PRD_PROXY:
    maxTotal: 500
    maxPerRoute: 300
    connectTimeout: 3000
    socketTimeout: 5000
    enableProxy: true
    proxyHostname: apxy1.hk.hhhh
    proxyPort: 18084
    retryCount: 5
    enableGzip: false


httpclient:
  defaultHttpClientName: NON_PROXY
  etNetHttpClientName: ETNET_PROXY

com:
  hhhh:
    wmd:
      itt:
        security:
          filter:
            url-patterns: /wealth/api/v1/market-data/*
            digital:
              enable: false
              verify-date: false
              saml3-certificates:
              - certificate-source: ldap
                ldap:
                  #todo
                  provider: ldap://ldap-hbap-prod.hk.hhhh:1636/uid=SAAS_AP01.E2E_TRUST_PublicKey,ou=E2ETrustPublic,ou=GLOBAL_CONFIG,c=hk,dc=hhhh,dc=com
                  username: uid=SAAS_AP01.E2E_TRUST_PublicKey,ou=E2ETrustPublic,ou=GLOBAL_CONFIG,c=hk,dc=hhhh,dc=com
                  password: ENC(FNqtuEu1MVD98LaXRvKoPsN922H9sa6Q)
#                  password: ENC(hBUKgoNw7n18HENiHQq3eGbxna4N8tvQ)
                  timeout: 1000

healthcheck:
  predictive-search-health-check-url: http://mds-hase-pred-search-service/healthcheck/probing
  header:
    channelId: OHI
    countryCode: CN,HK
    groupMember: HASE
  service: IDN_RDF
  item:
    - 1037.HK
    - GOOG.O
  filter:
    - TRADE_DATE
    - TRDPRC_1
    - TURNOVER

cache:
  distribute:
    enabled: true
#    uri: https://distributed-cache-system-hk-hase-v1-dt2.cf.cloud.hk.hhhh/cache/
    aws-uri: http://distributed-cache-system-hk-hase-service/cache/
    connection:
      socketTimeout: 1000
      retryCount: 5

multi-predsrch: 
  url: http://mds-hase-pred-search-service/wealth/api/v1/market-data/product/multi-predictive-search
  body-prefix: param=
  request-params:
    assetClasses: ALL
    searchFields: symbol
    sortingFields: symbol
    isPreciseSrch: true

etnet:
  proxy-name: HK_PRD_PROXY
  headers-for-etnet-auth:
    Authorization: Basic aHMxMXVzZXI6aHNldDEyMzQ=
  get-token-url: https://hsp2gp.etnet.com.hk/HSAPI/Auth/GetToken
  validate-token-url: https://hsp2gp.etnet.com.hk/HSAPI/Auth/ValidateToken
  chart-data-url: https://hsp2gp.etnet.com.hk/HSAPI/GetData/RawChart
  quote-url: https://hsp2gp.etnet.com.hk/HSAPI/GetData/Quote
  indices-url: https://hsp2gp.etnet.com.hk/HSAPI/GetData/IndicesQuote
  topmovers-url: https://hsp2gp.etnet.com.hk/HSAPI/GetData/TopMovers
  news-detail-url: https://hsp2gp.etnet.com.hk/HSAPI/GetData/NewsContent
  news-headlines-url: https://hsp2gp.etnet.com.hk/HSAPI/GetData/NewsHeadline
  listedipo-url: https://hsp2gp.etnet.com.hk/HSAPI/GetData/ListedIPO
  currentipo-url: https://hsp2gp.etnet.com.hk/HSAPI/GetData/CurrentIPO
  ashares-stock-url: https://hsp2gp.etnet.com.hk/HSAPI/GetData/ASharesStock

tris:
  closure:
    DEFAULT: app_tris_rbwm_stockconnect_sat
  token-keystore:
    DEFAULT:
      keystore-file-path: '/keystore/tris/sit_sgh_utb/tris_keystore.dat'
      keystore-password-file-path: '/keystore/tris/sit_sgh_utb/tris_password.dat'
      initialisation-vector: 12,34,56,78,90,87,65,43
  url: http://hktrisu11.hk.hhhh:30000/ids-rest/json/quote
  news-headlines-url: http://hktrisu11.hk.hhhh:30000/tris/news/headline
  news-detail-url: http://hktrisu11.hk.hhhh:30000/tris/news/story
  same-sector-url: http://hktrisu11.hk.hhhh:30000/srbp/getSameSectorStocks

labci:
  proxy_name: HK_PRD_PROXY
  token-keystore:
    DEFAULT:
      keystore-file-path: '/keystore/labci/prod/labci_hase_stma_keystore.dat'
      keystore-password-file-path: '/keystore/labci/prod/labci_hase_stma_keystore_password.dat'
      initialisation-vector: 52,69,04,00,14,10,96,49
  url: https://caching-hase-mds.hk.hhhh:30001/servlet/Watchlist
  nb-url: https://caching-hase-mds.hk.hhhh:30001/servlet_nb/Watchlist
  luld-url: https://caching-hase-mds.hk.hhhh:30001/servlet/Watchlist
  midfs-bmp-url: http://midfs-hase.hk.hhhh:31012/stock/bmpquote
  midfs-list-url: http://midfs-hase.hk.hhhh:31012/stock/quotelist
  midfs-detail-url: http://midfs-hase.hk.hhhh:31012/stock/quotedetail
  chart-data-url: https://mkdlc.ebanking.hhhh.com.hk/hase/chart/data
  trading-day-url: 'http://srbp-api-hk-hase-service/asset-class-code/SEC/country-product-exchange-market-code/HK/message-enquiry-date/tradeDay/trade-dates'
  trading-param-prefix: 'applicationCommon='
  trading-param: '{"channelId":"OHI","countryCode":"HK","groupMember":"HASE","lineOfBusiness":"PFS"}'


#for us market
labci-protal:
  proxy-name: HK_PRD_PROXY
  token-timezone:
    DEFAULT: GMT
#  trading-day-url: 'https://srbp-api-v1-hk-hase-prod.cf.cloud.hk.hhhh/asset-class-code/SEC/country-product-exchange-market-code/US/message-enquiry-date/tradeDay/trade-dates'
#  trading-hour-url: 'https://srbp-api-v1-hk-hase-prod.cf.cloud.hk.hhhh/asset-class-code/SEC/country-product-exchange-market-code/US/message-enquiry-date/tradeDay/trade-hours'
  trading-day-url: 'http://srbp-api-hk-hase-service/asset-class-code/SEC/country-product-exchange-market-code/US/message-enquiry-date/tradeDay/trade-dates'
  trading-hour-url: 'http://srbp-api-hk-hase-service/asset-class-code/SEC/country-product-exchange-market-code/US/message-enquiry-date/tradeDay/trade-hours'
  trading-param-prefix: 'applicationCommon='
  trading-param: '{"channelId":"OHI","countryCode":"HK","groupMember":"HASE","lineOfBusiness":"PFS"}'
  token-keystore:
    DEFAULT:
      keystore-file-path: '/keystore/labci/prod/labci_hase_stma_keystore.dat'
      keystore-password-file-path: '/keystore/labci/prod/labci_hase_stma_keystore_password.dat'
      initialisation-vector: 52,69,04,00,14,10,96,49
  query-url: https://mkdlc.ebanking.hhhh.com.hk/hase-moveapi/query
  chart-data-url: https://mkdlc.ebanking.hhhh.com.hk/hase-lciapi/chart/data
  past-performance-url: https://mkdlc.ebanking.hhhh.com.hk/hase-lciapi/performance
  stock-info-url: https://mkdlc.ebanking.hhhh.com.hk/hase-lciapi/stockinfo
  response-status:
    code-key: stsCode
    text-key: stsTxt
    correct-status: '000'

#for us market
labci-protal-cmb:
  proxy-name: HK_PRD_PROXY
  token-timezone:
    DEFAULT: GMT
#  trading-day-url: 'https://srbp-api-v1-hk-hase-prod.cf.cloud.hk.hhhh/asset-class-code/SEC/country-product-exchange-market-code/US/message-enquiry-date/tradeDay/trade-dates'
#  trading-hour-url: 'https://srbp-api-v1-hk-hase-prod.cf.cloud.hk.hhhh/asset-class-code/SEC/country-product-exchange-market-code/US/message-enquiry-date/tradeDay/trade-hours'
  trading-day-url: 'http://srbp-api-hk-hase-service/asset-class-code/SEC/country-product-exchange-market-code/US/message-enquiry-date/tradeDay/trade-dates'
  trading-hour-url: 'http://srbp-api-hk-hase-service/asset-class-code/SEC/country-product-exchange-market-code/US/message-enquiry-date/tradeDay/trade-hours'
  trading-param-prefix: 'applicationCommon='
  trading-param: '{"channelId":"OHI","countryCode":"HK","groupMember":"HASE","lineOfBusiness":"PFS"}'
  token-keystore:
    DEFAULT:
      keystore-file-path: '/keystore/labci/prod/labci_hase_stma_keystore.dat'
      keystore-password-file-path: '/keystore/labci/prod/labci_hase_stma_keystore_password.dat'
      initialisation-vector: 52,69,04,00,14,10,96,49
  query-url: https://mkdlc.ebanking.hhhh.com.hk/hase-cmb-moveapi/query
  chart-data-url: https://mkdlc.ebanking.hhhh.com.hk/hase-cmb-lciapi/chart/data
  past-performance-url: https://mkdlc.ebanking.hhhh.com.hk/hase-cmb-lciapi/performance
  stock-info-url: https://mkdlc.ebanking.hhhh.com.hk/hase-cmb-lciapi/stockinfo
  response-status:
    code-key: stsCode
    text-key: stsTxt
    correct-status: '000'

swagger:
  disabled: true