//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.01.11 at 04:02:36 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.quotesummary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"countryHeadquarters"})
@XmlRootElement(name = "AMCB-ProviderCompanyCountryHeadquarters")
public class AMCBProviderCompanyCountryHeadquarters {

    @XmlElement(name = "CountryHeadquarters", required = true)
    protected CountryHeadquarters countryHeadquarters;

    
    public CountryHeadquarters getCountryHeadquarters() {
        return this.countryHeadquarters;
    }

    
    public void setCountryHeadquarters(final CountryHeadquarters value) {
        this.countryHeadquarters = value;
    }

}
