//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.25 at 03:58:04 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.quotesummary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"tsDayEndBidPrice", "tsnav52WkLow", "tsnav52WkHigh", "tsDayEndOfferPrice", "cyrYear1", "cyrYear2",
    "cyrYear3", "cyrYear4", "cyrYear5", "cyrYear6", "cyrYear7", "cyrYear8", "cyrYear9", "cyrBestFitIndexYear1",
    "cyrBestFitIndexYear2", "cyrBestFitIndexYear3", "cyrBestFitIndexYear4", "cyrBestFitIndexYear5", "cyrBestFitIndexYear6",
    "cyrBestFitIndexYear7", "cyrBestFitIndexYear8", "cyrBestFitIndexYear9", "cyrCategoryYear1", "cyrCategoryYear2",
    "cyrCategoryYear3", "cyrCategoryYear4", "cyrCategoryYear5", "cyrCategoryYear6", "cyrCategoryYear7", "cyrCategoryYear8",
    "cyrCategoryYear9", "cyrCategoryYear10", "mptpiIndexName", "mptbfIndexID", "dpCategoryCode", "dpCategoryName",
    "fscbiProviderCompanyName", "amcbAdministratorCompanies", "amcbSubAdvisorCompanies", "kdInceptionDate", "icInvestmentStrategy",
    "icMultilingualInvestmentStrategies", "naShareClassNetAssets", "psTurnoverRatio", "psEquityStylebox", "psFixedIncomeStylebox",
    "dmpSharesOutstanding", "fscbiCurrencyId", "dpDayEndNAV", "dpPremiumDiscount", "psPriceToEarnings", "yldYield1Yr", "dpDividend",
    "dpCurrency", "dpDividendDate", "rmbacBeta3Yr", "piMinimumInitial", "piMinimumSubsequent", "piMinimumIRA", "piSubsequentIRA",
    "piPurchaseCurrencyId", "piMinimumInitialInvestmentUnit", "piMinimumSubsequentUnit", "piClosedToInvestors",
    "lsMaximumFrontLoad", "lsMaximumDeferLoad", "pfActualManagementFee", "prospectusCustodianFee", "arfmer", "fscbiFundServDetails",
    "fscbiShareClassType", "arfAnnualReportDate", "mrRatingOverall", "mrRating3Year", "mrRating5Year", "mrRating10Year",
    "tarRatingOverall", "tarRating3Yr", "tarRating5Yr", "tarRating10Yr", "mrRatingDate", "amcbDistributorCompanies",
    "fscbiLocalPhone", "amcbFax", "fscbiProviderCompanyWebsite", "fmManagers", "fm2Managers",
    "amcbProviderCompanyCountryHeadquarters", "onGoingCharge", "mptpiIndexID", "cyrPrimaryIndexYear1", "cyrPrimaryIndexYear10",
    "cyrPrimaryIndexYear2", "cyrPrimaryIndexYear3", "cyrPrimaryIndexYear4", "cyrPrimaryIndexYear5", "cyrPrimaryIndexYear6",
    "cyrPrimaryIndexYear7", "cyrPrimaryIndexYear8", "cyrPrimaryIndexYear9", "ttrReturnYTD", "ttrBestFitIndexReturnYTD",
    "ttrCategoryReturnYTD", "cyrPrimaryIndexYTD", "aabrpAssetAllocBondNet", "aabrpPreferredStockNet", "aabrpAssetAllocCashNet",
    "aabrpOtherNet", "aabrpAssetAllocEquityNet", "cqbrpCreditQualA", "cqbrpCreditQualAA", "cqbrpCreditQualAAA", "cqbrpCreditQualB",
    "cqbrpCreditQualBB", "cqbrpCreditQualBBB", "cqbrpCreditQualBelowB", "cqbrpCreditQualNotRated", "cqbrpCreditQualDate",
    "ttrReturn1Mth", "ttrReturn3Mth", "ttrReturn6Mth", "ttrReturn1Yr", "ttrReturn3Yr", "ttrReturn5Yr", "ttrReturn10Yr",
    "ttrMonthEndDate", "ttrBestFitIndexReturn1Mth", "ttrBestFitIndexReturn3Mth", "ttrBestFitIndexReturn6Mth",
    "ttrBestFitIndexReturn1Yr", "ttrBestFitIndexReturn3Yr", "ttrBestFitIndexReturn5Yr", "ttrBestFitIndexReturn10Yr",
    "ttrCategoryReturn1Mth", "ttrCategoryReturn3Mth", "ttrCategoryReturn6Mth", "ttrCategoryReturn1Yr", "ttrCategoryReturn3Yr",
    "ttrCategoryReturn5Yr", "ttrCategoryReturn10Yr", "dpReturn1Mth", "dpReturn3Mth", "dpReturn6Mth", "dpReturnYTD", "dpReturn1Yr",
    "dpReturn3Yr", "dpReturn5Yr", "dpReturn10Yr", "dpDayEndDate", "srStubYearEndReturnEndDate", "srStubYearEndReturn",
    "dpCategoryReturn1Mth", "dpCategoryReturn3Mth", "dpCategoryReturn6Mth", "dpCategoryReturn1Yr", "dpCategoryReturn3Yr",
    "dpCategoryReturn5Yr", "dpCategoryReturn10Yr", "dpCategoryReturnYTD", "ttrPrimaryIndexReturn1Mth", "ttrPrimaryIndexReturn3Mth",
    "ttrPrimaryIndexReturn6Mth", "ttrPrimaryIndexReturn1Yr", "ttrPrimaryIndexReturn3Yr", "ttrPrimaryIndexReturn5Yr",
    "ttrPrimaryIndexReturn10Yr", "ttrPrimaryIndexReturnYTD", "fbPrimaryProspectusBenchmarks", "tsDayEndBidOfferPricesDate",
    "tsDayEndNAVDate", "atActualFrontLoad"})
@XmlRootElement(name = "api")
public class Api {

    @XmlElement(name = "TS-DayEndBidPrice", required = true)
    protected String tsDayEndBidPrice;
    @XmlElement(name = "TS-NAV52wkLow", required = true)
    protected String tsnav52WkLow;
    @XmlElement(name = "TS-NAV52wkHigh", required = true)
    protected String tsnav52WkHigh;
    @XmlElement(name = "TS-DayEndOfferPrice", required = true)
    protected String tsDayEndOfferPrice;
    @XmlElement(name = "CYR-Year1", required = true)
    protected String cyrYear1;
    @XmlElement(name = "CYR-Year2", required = true)
    protected String cyrYear2;
    @XmlElement(name = "CYR-Year3", required = true)
    protected String cyrYear3;
    @XmlElement(name = "CYR-Year4", required = true)
    protected String cyrYear4;
    @XmlElement(name = "CYR-Year5", required = true)
    protected String cyrYear5;
    @XmlElement(name = "CYR-Year6", required = true)
    protected String cyrYear6;
    @XmlElement(name = "CYR-Year7", required = true)
    protected String cyrYear7;
    @XmlElement(name = "CYR-Year8", required = true)
    protected String cyrYear8;
    @XmlElement(name = "CYR-Year9", required = true)
    protected String cyrYear9;

    @XmlElement(name = "CYR-BestFitIndexYear1", required = true)
    protected String cyrBestFitIndexYear1;
    @XmlElement(name = "CYR-BestFitIndexYear2", required = true)
    protected String cyrBestFitIndexYear2;
    @XmlElement(name = "CYR-BestFitIndexYear3", required = true)
    protected String cyrBestFitIndexYear3;
    @XmlElement(name = "CYR-BestFitIndexYear4", required = true)
    protected String cyrBestFitIndexYear4;
    @XmlElement(name = "CYR-BestFitIndexYear5", required = true)
    protected String cyrBestFitIndexYear5;
    @XmlElement(name = "CYR-BestFitIndexYear6", required = true)
    protected String cyrBestFitIndexYear6;
    @XmlElement(name = "CYR-BestFitIndexYear7", required = true)
    protected String cyrBestFitIndexYear7;
    @XmlElement(name = "CYR-BestFitIndexYear8", required = true)
    protected String cyrBestFitIndexYear8;
    @XmlElement(name = "CYR-BestFitIndexYear9", required = true)
    protected String cyrBestFitIndexYear9;
    @XmlElement(name = "MPTBF-IndexID", required = true)
    protected String mptbfIndexID;
    @XmlElement(name = "DP-CategoryCode", required = true)
    protected String dpCategoryCode;
    @XmlElement(name = "DP-CategoryName", required = true)
    protected String dpCategoryName;
    @XmlElement(name = "FSCBI-ProviderCompanyName", required = true)
    protected String fscbiProviderCompanyName;
    @XmlElement(name = "AMCB-AdministratorCompanies", required = true)
    protected AMCBAdministratorCompanies amcbAdministratorCompanies;
    @XmlElement(name = "AMCB-SubAdvisorCompanies", required = true)
    protected AMCBSubAdvisorCompanies amcbSubAdvisorCompanies;
    @XmlElement(name = "KD-InceptionDate", required = true)
    protected String kdInceptionDate;
    @XmlElement(name = "IC-InvestmentStrategy", required = true)
    protected String icInvestmentStrategy;
    @XmlElement(name = "IC-MultilingualInvestmentStrategies", required = true)
    protected ICMultilingualInvestmentStrategies icMultilingualInvestmentStrategies;
    @XmlElement(name = "NA-ShareClassNetAssets", required = true)
    protected String naShareClassNetAssets;
    @XmlElement(name = "PS-TurnoverRatio", required = true)
    protected String psTurnoverRatio;
    @XmlElement(name = "PS-EquityStylebox", required = true)
    protected String psEquityStylebox;
    @XmlElement(name = "PS-FixedIncomeStylebox", required = true)
    protected String psFixedIncomeStylebox;
    @XmlElement(name = "DMP-SharesOutstanding", required = true)
    protected String dmpSharesOutstanding;
    @XmlElement(name = "FSCBI-CurrencyId", required = true)
    protected String fscbiCurrencyId;
    @XmlElement(name = "DP-DayEndNAV", required = true)
    protected String dpDayEndNAV;
    @XmlElement(name = "DP-PremiumDiscount", required = true)
    protected String dpPremiumDiscount;
    @XmlElement(name = "PS-PriceToEarnings", required = true)
    protected String psPriceToEarnings;
    @XmlElement(name = "YLD-Yield1Yr", required = true)
    protected String yldYield1Yr;
    @XmlElement(name = "DP-Dividend", required = true)
    protected String dpDividend;
    @XmlElement(name = "DP-Currency", required = true)
    protected String dpCurrency;
    @XmlElement(name = "DP-DividendDate", required = true)
    protected String dpDividendDate;
    @XmlElement(name = "RMBAC-Beta3Yr", required = true)
    protected String rmbacBeta3Yr;
    @XmlElement(name = "PI-MinimumInitial", required = true)
    protected String piMinimumInitial;
    @XmlElement(name = "PI-MinimumSubsequent", required = true)
    protected String piMinimumSubsequent;
    @XmlElement(name = "PI-MinimumIRA", required = true)
    protected String piMinimumIRA;
    @XmlElement(name = "PI-SubsequentIRA", required = true)
    protected String piSubsequentIRA;
    @XmlElement(name = "PI-PurchaseCurrencyId", required = true)
    protected String piPurchaseCurrencyId;
    @XmlElement(name = "PI-MinimumInitialInvestmentUnit", required = true)
    protected String piMinimumInitialInvestmentUnit;
    @XmlElement(name = "PI-MinimumSubsequentUnit", required = true)
    protected String piMinimumSubsequentUnit;
    @XmlElement(name = "PI-ClosedToInvestors", required = true)
    protected PIClosedToInvestors piClosedToInvestors;
    @XmlElement(name = "LS-MaximumFrontLoad", required = true)
    protected String lsMaximumFrontLoad;
    @XmlElement(name = "LS-MaximumDeferLoad", required = true)
    protected String lsMaximumDeferLoad;
    @XmlElement(name = "PF-ActualManagementFee", required = true)
    protected String pfActualManagementFee;
    @XmlElement(name = "LS-ProspectusCustodianFee", required = true)
    protected ProspectusCustodianFee prospectusCustodianFee;
    @XmlElement(name = "ARF-MER", required = true)
    protected String arfmer;
    @XmlElement(name = "FSCBI-FundServDetails", required = true)
    protected FSCBIFundServDetails fscbiFundServDetails;
    @XmlElement(name = "FSCBI-ShareClassType", required = true)
    protected String fscbiShareClassType;
    @XmlElement(name = "ARF-AnnualReportDate", required = true)
    protected String arfAnnualReportDate;
    @XmlElement(name = "MR-RatingOverall", required = true)
    protected String mrRatingOverall;
    @XmlElement(name = "MR-Rating3Year", required = true)
    protected String mrRating3Year;
    @XmlElement(name = "MR-Rating5Year", required = true)
    protected String mrRating5Year;
    @XmlElement(name = "MR-Rating10Year", required = true)
    protected String mrRating10Year;
    @XmlElement(name = "TAR-RatingOverall", required = true)
    protected String tarRatingOverall;
    @XmlElement(name = "TAR-Rating3Yr", required = true)
    protected String tarRating3Yr;
    @XmlElement(name = "TAR-Rating5Yr", required = true)
    protected String tarRating5Yr;
    @XmlElement(name = "TAR-Rating10Yr", required = true)
    protected String tarRating10Yr;
    @XmlElement(name = "MR-RatingDate", required = true)
    protected String mrRatingDate;
    @XmlElement(name = "AMCB-DistributorCompanies", required = true)
    protected AMCBDistributorCompanies amcbDistributorCompanies;
    @XmlElement(name = "FSCBI-LocalPhone", required = true)
    protected String fscbiLocalPhone;
    @XmlElement(name = "AMCB-Fax", required = true)
    protected String amcbFax;
    @XmlElement(name = "FSCBI-ProviderCompanyWebsite", required = true)
    protected String fscbiProviderCompanyWebsite;
    @XmlElement(name = "FM-Managers", required = true)
    protected FMManagers fmManagers;
    @XmlElement(name = "FM2-Managers", required = true)
    protected FM2Managers fm2Managers;
    @XmlElement(name = "AMCB-ProviderCompanyCountryHeadquarters", required = true)
    protected AMCBProviderCompanyCountryHeadquarters amcbProviderCompanyCountryHeadquarters;
    @XmlElement(name = "ARF-AnnualReportOngoingCharge")
    protected String onGoingCharge;
    @XmlAttribute(name = "_id")
    protected String id;
    @XmlElement(name = "CYR-CategoryYear1", required = true)
    protected String cyrCategoryYear1;
    @XmlElement(name = "CYR-CategoryYear2", required = true)
    protected String cyrCategoryYear2;
    @XmlElement(name = "CYR-CategoryYear3", required = true)
    protected String cyrCategoryYear3;
    @XmlElement(name = "CYR-CategoryYear4", required = true)
    protected String cyrCategoryYear4;
    @XmlElement(name = "CYR-CategoryYear5", required = true)
    protected String cyrCategoryYear5;
    @XmlElement(name = "CYR-CategoryYear6", required = true)
    protected String cyrCategoryYear6;
    @XmlElement(name = "CYR-CategoryYear7", required = true)
    protected String cyrCategoryYear7;
    @XmlElement(name = "CYR-CategoryYear8", required = true)
    protected String cyrCategoryYear8;
    @XmlElement(name = "CYR-CategoryYear9", required = true)
    protected String cyrCategoryYear9;
    @XmlElement(name = "CYR-CategoryYear10", required = true)
    protected String cyrCategoryYear10;
    @XmlElement(name = "MPTPI-IndexName", required = true)
    protected String mptpiIndexName;
    @XmlElement(name = "MPTPI-IndexID", required = true)
    protected String mptpiIndexID;
    @XmlElement(name = "CYR-PrimaryIndexYear1")
    protected String cyrPrimaryIndexYear1;
    @XmlElement(name = "CYR-PrimaryIndexYear10")
    protected String cyrPrimaryIndexYear10;
    @XmlElement(name = "CYR-PrimaryIndexYear2")
    protected String cyrPrimaryIndexYear2;
    @XmlElement(name = "CYR-PrimaryIndexYear3")
    protected String cyrPrimaryIndexYear3;
    @XmlElement(name = "CYR-PrimaryIndexYear4")
    protected String cyrPrimaryIndexYear4;
    @XmlElement(name = "CYR-PrimaryIndexYear5")
    protected String cyrPrimaryIndexYear5;
    @XmlElement(name = "CYR-PrimaryIndexYear6")
    protected String cyrPrimaryIndexYear6;
    @XmlElement(name = "CYR-PrimaryIndexYear7")
    protected String cyrPrimaryIndexYear7;
    @XmlElement(name = "CYR-PrimaryIndexYear8")
    protected String cyrPrimaryIndexYear8;
    @XmlElement(name = "CYR-PrimaryIndexYear9")
    protected String cyrPrimaryIndexYear9;
    @XmlElement(name = "TTR-ReturnYTD", required = true)
    protected String ttrReturnYTD;
    @XmlElement(name = "TTR-BestFitIndexReturnYTD", required = true)
    protected String ttrBestFitIndexReturnYTD;
    @XmlElement(name = "TTR-CategoryReturnYTD", required = true)
    protected String ttrCategoryReturnYTD;
    @XmlElement(name = "CYR-PrimaryIndexYTD")
    protected String cyrPrimaryIndexYTD;
    @XmlElement(name = "AABRP-AssetAllocBondNet")
    protected String aabrpAssetAllocBondNet;
    @XmlElement(name = "AABRP-PreferredStockNet")
    protected String aabrpPreferredStockNet;
    @XmlElement(name = "AABRP-AssetAllocCashNet")
    protected String aabrpAssetAllocCashNet;
    @XmlElement(name = "AABRP-OtherNet")
    protected String aabrpOtherNet;
    @XmlElement(name = "AABRP-AssetAllocEquityNet")
    protected String aabrpAssetAllocEquityNet;
    @XmlElement(name = "CQBRP-CreditQualA")
    protected String cqbrpCreditQualA;
    @XmlElement(name = "CQBRP-CreditQualAA")
    protected String cqbrpCreditQualAA;
    @XmlElement(name = "CQBRP-CreditQualAAA")
    protected String cqbrpCreditQualAAA;
    @XmlElement(name = "CQBRP-CreditQualB")
    protected String cqbrpCreditQualB;
    @XmlElement(name = "CQBRP-CreditQualBB")
    protected String cqbrpCreditQualBB;
    @XmlElement(name = "CQBRP-CreditQualBBB")
    protected String cqbrpCreditQualBBB;
    @XmlElement(name = "CQBRP-CreditQualBelowB")
    protected String cqbrpCreditQualBelowB;
    @XmlElement(name = "CQBRP-CreditQualNotRated")
    protected String cqbrpCreditQualNotRated;
    @XmlElement(name = "CQBRP-CreditQualDate")
    protected String cqbrpCreditQualDate;

    // Monthly Return
    @XmlElement(name = "TTR-Return1Mth")
    protected String ttrReturn1Mth;
    @XmlElement(name = "TTR-Return3Mth")
    protected String ttrReturn3Mth;
    @XmlElement(name = "TTR-Return6Mth")
    protected String ttrReturn6Mth;
    @XmlElement(name = "TTR-Return1Yr")
    protected String ttrReturn1Yr;
    @XmlElement(name = "TTR-Return3Yr")
    protected String ttrReturn3Yr;
    @XmlElement(name = "TTR-Return5Yr")
    protected String ttrReturn5Yr;
    @XmlElement(name = "TTR-Return10Yr")
    protected String ttrReturn10Yr;
    @XmlElement(name = "TTR-MonthEndDate")
    protected String ttrMonthEndDate;

    @XmlElement(name = "TTR-BestFitIndexReturn1Mth")
    protected String ttrBestFitIndexReturn1Mth;
    @XmlElement(name = "TTR-BestFitIndexReturn3Mth")
    protected String ttrBestFitIndexReturn3Mth;
    @XmlElement(name = "TTR-BestFitIndexReturn6Mth")
    protected String ttrBestFitIndexReturn6Mth;
    @XmlElement(name = "TTR-BestFitIndexReturn1Yr")
    protected String ttrBestFitIndexReturn1Yr;
    @XmlElement(name = "TTR-BestFitIndexReturn3Yr")
    protected String ttrBestFitIndexReturn3Yr;
    @XmlElement(name = "TTR-BestFitIndexReturn5Yr")
    protected String ttrBestFitIndexReturn5Yr;
    @XmlElement(name = "TTR-BestFitIndexReturn10Yr")
    protected String ttrBestFitIndexReturn10Yr;
    @XmlElement(name = "TTR-CategoryReturn1Mth")
    protected String ttrCategoryReturn1Mth;
    @XmlElement(name = "TTR-CategoryReturn3Mth")
    protected String ttrCategoryReturn3Mth;
    @XmlElement(name = "TTR-CategoryReturn6Mth")
    protected String ttrCategoryReturn6Mth;
    @XmlElement(name = "TTR-CategoryReturn1Yr")
    protected String ttrCategoryReturn1Yr;
    @XmlElement(name = "TTR-CategoryReturn3Yr")
    protected String ttrCategoryReturn3Yr;
    @XmlElement(name = "TTR-CategoryReturn5Yr")
    protected String ttrCategoryReturn5Yr;
    @XmlElement(name = "TTR-CategoryReturn10Yr")
    protected String ttrCategoryReturn10Yr;

    // Daily Return
    @XmlElement(name = "DP-Return1Mth")
    protected String dpReturn1Mth;
    @XmlElement(name = "DP-Return3Mth")
    protected String dpReturn3Mth;
    @XmlElement(name = "DP-Return6Mth")
    protected String dpReturn6Mth;
    @XmlElement(name = "DP-ReturnYTD")
    protected String dpReturnYTD;
    @XmlElement(name = "DP-Return1Yr")
    protected String dpReturn1Yr;
    @XmlElement(name = "DP-Return3Yr")
    protected String dpReturn3Yr;
    @XmlElement(name = "DP-Return5Yr")
    protected String dpReturn5Yr;
    @XmlElement(name = "DP-Return10Yr")
    protected String dpReturn10Yr;
    @XmlElement(name = "DP-DayEndDate")
    protected String dpDayEndDate;

    @XmlElement(name = "SR-StubYearEndReturnEndDate")
    protected String srStubYearEndReturnEndDate;
    @XmlElement(name = "SR-StubYearEndReturn")
    protected String srStubYearEndReturn;

    @XmlElement(name = "DP-CategoryReturn1Mth")
    protected String dpCategoryReturn1Mth;
    @XmlElement(name = "DP-CategoryReturn3Mth")
    protected String dpCategoryReturn3Mth;
    @XmlElement(name = "DP-CategoryReturn6Mth")
    protected String dpCategoryReturn6Mth;
    @XmlElement(name = "DP-CategoryReturn1Yr")
    protected String dpCategoryReturn1Yr;
    @XmlElement(name = "DP-CategoryReturn3Yr")
    protected String dpCategoryReturn3Yr;
    @XmlElement(name = "DP-CategoryReturn5Yr")
    protected String dpCategoryReturn5Yr;
    @XmlElement(name = "DP-CategoryReturn10Yr")
    protected String dpCategoryReturn10Yr;
    @XmlElement(name = "DP-CategoryReturnYTD")
    protected String dpCategoryReturnYTD;

    @XmlElement(name = "TTR-PrimaryIndexReturn1Mth")
    protected String ttrPrimaryIndexReturn1Mth;
    @XmlElement(name = "TTR-PrimaryIndexReturn3Mth")
    protected String ttrPrimaryIndexReturn3Mth;
    @XmlElement(name = "TTR-PrimaryIndexReturn6Mth")
    protected String ttrPrimaryIndexReturn6Mth;
    @XmlElement(name = "TTR-PrimaryIndexReturn1Yr")
    protected String ttrPrimaryIndexReturn1Yr;
    @XmlElement(name = "TTR-PrimaryIndexReturn3Yr")
    protected String ttrPrimaryIndexReturn3Yr;
    @XmlElement(name = "TTR-PrimaryIndexReturn5Yr")
    protected String ttrPrimaryIndexReturn5Yr;
    @XmlElement(name = "TTR-PrimaryIndexReturn10Yr")
    protected String ttrPrimaryIndexReturn10Yr;
    @XmlElement(name = "TTR-PrimaryIndexReturnYTD")
    protected String ttrPrimaryIndexReturnYTD;
    @XmlElement(name = "TS-DayEndBidOfferPricesDate")
    protected String tsDayEndBidOfferPricesDate;
    @XmlElement(name = "TS-DayEndNAVDate")
    protected String tsDayEndNAVDate;

    @XmlElement(name = "FB-PrimaryProspectusBenchmarks", required = true)
    protected FBPrimaryProspectusBenchmarks fbPrimaryProspectusBenchmarks;
    @XmlElement(name = "AT-ActualFrontLoad")
    protected String atActualFrontLoad;

    
    public String getTSDayEndBidPrice() {
        return this.tsDayEndBidPrice;
    }

    
    public void setTSDayEndBidPrice(final String value) {
        this.tsDayEndBidPrice = value;
    }

    
    public String getTSNAV52WkLow() {
        return this.tsnav52WkLow;
    }

    
    public void setTSNAV52WkLow(final String value) {
        this.tsnav52WkLow = value;
    }

    
    public String getTSNAV52WkHigh() {
        return this.tsnav52WkHigh;
    }

    
    public void setTSNAV52WkHigh(final String value) {
        this.tsnav52WkHigh = value;
    }

    
    public String getTSDayEndOfferPrice() {
        return this.tsDayEndOfferPrice;
    }

    
    public void setTSDayEndOfferPrice(final String value) {
        this.tsDayEndOfferPrice = value;
    }

    
    public String getTTRReturnYTD() {
        return this.ttrReturnYTD;
    }

    
    public void setTTRReturnYTD(final String ttrReturnYTD) {
        this.ttrReturnYTD = ttrReturnYTD;
    }

    
    public String getCYRYear1() {
        return this.cyrYear1;
    }

    
    public void setCYRYear1(final String value) {
        this.cyrYear1 = value;
    }

    
    public String getCYRYear2() {
        return this.cyrYear2;
    }

    
    public void setCYRYear2(final String value) {
        this.cyrYear2 = value;
    }

    
    public String getCYRYear3() {
        return this.cyrYear3;
    }

    
    public void setCYRYear3(final String value) {
        this.cyrYear3 = value;
    }

    
    public String getCYRYear4() {
        return this.cyrYear4;
    }

    
    public void setCYRYear4(final String value) {
        this.cyrYear4 = value;
    }

    
    public String getCYRYear5() {
        return this.cyrYear5;
    }

    
    public void setCYRYear5(final String value) {
        this.cyrYear5 = value;
    }

    
    public String getCYRYear6() {
        return this.cyrYear6;
    }

    
    public void setCYRYear6(final String value) {
        this.cyrYear6 = value;
    }

    
    public String getCYRYear7() {
        return this.cyrYear7;
    }

    
    public void setCYRYear7(final String value) {
        this.cyrYear7 = value;
    }

    
    public String getCYRYear8() {
        return this.cyrYear8;
    }

    
    public void setCYRYear8(final String value) {
        this.cyrYear8 = value;
    }

    
    public String getCYRYear9() {
        return this.cyrYear9;
    }

    
    public void setCYRYear9(final String value) {
        this.cyrYear9 = value;
    }

    
    public String getTTRBestFitIndexReturnYTD() {
        return this.ttrBestFitIndexReturnYTD;
    }

    
    public void setTTRBestFitIndexReturnYTD(final String ttrBestFitIndexReturnYTD) {
        this.ttrBestFitIndexReturnYTD = ttrBestFitIndexReturnYTD;
    }

    
    public String getCYRBestFitIndexYear1() {
        return this.cyrBestFitIndexYear1;
    }

    
    public void setCYRBestFitIndexYear1(final String value) {
        this.cyrBestFitIndexYear1 = value;
    }

    
    public String getCYRBestFitIndexYear2() {
        return this.cyrBestFitIndexYear2;
    }

    
    public void setCYRBestFitIndexYear2(final String value) {
        this.cyrBestFitIndexYear2 = value;
    }

    
    public String getCYRBestFitIndexYear3() {
        return this.cyrBestFitIndexYear3;
    }

    
    public void setCYRBestFitIndexYear3(final String value) {
        this.cyrBestFitIndexYear3 = value;
    }

    
    public String getCYRBestFitIndexYear4() {
        return this.cyrBestFitIndexYear4;
    }

    
    public void setCYRBestFitIndexYear4(final String value) {
        this.cyrBestFitIndexYear4 = value;
    }

    
    public String getCYRBestFitIndexYear5() {
        return this.cyrBestFitIndexYear5;
    }

    
    public void setCYRBestFitIndexYear5(final String value) {
        this.cyrBestFitIndexYear5 = value;
    }

    
    public String getCYRBestFitIndexYear6() {
        return this.cyrBestFitIndexYear6;
    }

    
    public void setCYRBestFitIndexYear6(final String value) {
        this.cyrBestFitIndexYear6 = value;
    }

    
    public String getCYRBestFitIndexYear7() {
        return this.cyrBestFitIndexYear7;
    }

    
    public void setCYRBestFitIndexYear7(final String value) {
        this.cyrBestFitIndexYear7 = value;
    }

    
    public String getCYRBestFitIndexYear8() {
        return this.cyrBestFitIndexYear8;
    }

    
    public void setCYRBestFitIndexYear8(final String value) {
        this.cyrBestFitIndexYear8 = value;
    }

    
    public String getCYRBestFitIndexYear9() {
        return this.cyrBestFitIndexYear9;
    }

    
    public void setCYRBestFitIndexYear9(final String value) {
        this.cyrBestFitIndexYear9 = value;
    }

    
    public String getTTRCategoryReturnYTD() {
        return this.ttrCategoryReturnYTD;
    }

    
    public void setTTRCategoryReturnYTD(final String ttrCategoryReturnYTD) {
        this.ttrCategoryReturnYTD = ttrCategoryReturnYTD;
    }

    
    public String getCYRCategoryYear1() {
        return this.cyrCategoryYear1;
    }

    
    public void setCYRCategoryYear1(final String value) {
        this.cyrCategoryYear1 = value;
    }

    
    public String getCYRCategoryYear2() {
        return this.cyrCategoryYear2;
    }

    
    public void setCYRCategoryYear2(final String value) {
        this.cyrCategoryYear2 = value;
    }

    
    public String getCYRCategoryYear3() {
        return this.cyrCategoryYear3;
    }

    
    public void setCYRCategoryYear3(final String value) {
        this.cyrCategoryYear3 = value;
    }

    
    public String getCYRCategoryYear4() {
        return this.cyrCategoryYear4;
    }

    
    public void setCYRCategoryYear4(final String value) {
        this.cyrCategoryYear4 = value;
    }

    
    public String getCYRCategoryYear5() {
        return this.cyrCategoryYear5;
    }

    
    public void setCYRCategoryYear5(final String value) {
        this.cyrCategoryYear5 = value;
    }

    
    public String getCYRCategoryYear6() {
        return this.cyrCategoryYear6;
    }

    
    public void setCYRCategoryYear6(final String value) {
        this.cyrCategoryYear6 = value;
    }

    
    public String getCYRCategoryYear7() {
        return this.cyrCategoryYear7;
    }

    
    public void setCYRCategoryYear7(final String value) {
        this.cyrCategoryYear7 = value;
    }

    
    public String getCYRCategoryYear8() {
        return this.cyrCategoryYear8;
    }

    
    public void setCYRCategoryYear8(final String value) {
        this.cyrCategoryYear8 = value;
    }

    
    public String getCYRCategoryYear9() {
        return this.cyrCategoryYear9;
    }

    
    public void setCYRCategoryYear9(final String value) {
        this.cyrCategoryYear9 = value;
    }

    
    public String getCYRCategoryYear10() {
        return this.cyrCategoryYear10;
    }

    
    public void setCYRCategoryYear10(final String value) {
        this.cyrCategoryYear10 = value;
    }

    
    public String getMptpiIndexName() {
        return this.mptpiIndexName;
    }

    
    public void setMptpiIndexName(final String mptpiIndexName) {
        this.mptpiIndexName = mptpiIndexName;
    }

    
    public String getMPTBFIndexID() {
        return this.mptbfIndexID;
    }

    
    public void setMPTBFIndexID(final String value) {
        this.mptbfIndexID = value;
    }

    
    public String getDPCategoryCode() {
        return this.dpCategoryCode;
    }

    
    public void setDPCategoryCode(final String value) {
        this.dpCategoryCode = value;
    }

    
    public String getDPCategoryName() {
        return this.dpCategoryName;
    }

    
    public void setDPCategoryName(final String value) {
        this.dpCategoryName = value;
    }

    
    public String getFSCBIProviderCompanyName() {
        return this.fscbiProviderCompanyName;
    }

    
    public void setFSCBIProviderCompanyName(final String value) {
        this.fscbiProviderCompanyName = value;
    }

    
    public AMCBAdministratorCompanies getAMCBAdministratorCompanies() {
        return this.amcbAdministratorCompanies;
    }

    
    public void setAMCBAdministratorCompanies(final AMCBAdministratorCompanies value) {
        this.amcbAdministratorCompanies = value;
    }

    
    public AMCBSubAdvisorCompanies getAMCBSubAdvisorCompanies() {
        return this.amcbSubAdvisorCompanies;
    }

    
    public void setAMCBSubAdvisorCompanies(final AMCBSubAdvisorCompanies value) {
        this.amcbSubAdvisorCompanies = value;
    }

    
    public String getKDInceptionDate() {
        return this.kdInceptionDate;
    }

    
    public void setKDInceptionDate(final String value) {
        this.kdInceptionDate = value;
    }

    
    public String getICInvestmentStrategy() {
        return this.icInvestmentStrategy;
    }

    
    public void setICInvestmentStrategy(final String value) {
        this.icInvestmentStrategy = value;
    }

    
    public ICMultilingualInvestmentStrategies getICMultilingualInvestmentStrategies() {
        return this.icMultilingualInvestmentStrategies;
    }

    
    public void setICMultilingualInvestmentStrategies(final ICMultilingualInvestmentStrategies value) {
        this.icMultilingualInvestmentStrategies = value;
    }

    
    public String getNAShareClassNetAssets() {
        return this.naShareClassNetAssets;
    }

    
    public void setNAShareClassNetAssets(final String value) {
        this.naShareClassNetAssets = value;
    }

    
    public String getPSTurnoverRatio() {
        return this.psTurnoverRatio;
    }

    
    public void setPSTurnoverRatio(final String value) {
        this.psTurnoverRatio = value;
    }

    
    public String getPSEquityStylebox() {
        return this.psEquityStylebox;
    }

    
    public void setPSEquityStylebox(final String value) {
        this.psEquityStylebox = value;
    }

    
    public String getPSFixedIncomeStylebox() {
        return this.psFixedIncomeStylebox;
    }

    
    public void setPSFixedIncomeStylebox(final String value) {
        this.psFixedIncomeStylebox = value;
    }

    
    public String getDMPSharesOutstanding() {
        return this.dmpSharesOutstanding;
    }

    
    public void setDMPSharesOutstanding(final String value) {
        this.dmpSharesOutstanding = value;
    }

    
    public String getFscbiCurrencyId() {
        return this.fscbiCurrencyId;
    }

    
    public void setFscbiCurrencyId(final String fscbiCurrencyId) {
        this.fscbiCurrencyId = fscbiCurrencyId;
    }

    
    public String getDPDayEndNAV() {
        return this.dpDayEndNAV;
    }

    
    public void setDPDayEndNAV(final String value) {
        this.dpDayEndNAV = value;
    }

    
    public String getDPPremiumDiscount() {
        return this.dpPremiumDiscount;
    }

    
    public void setDPPremiumDiscount(final String value) {
        this.dpPremiumDiscount = value;
    }

    
    public String getPSPriceToEarnings() {
        return this.psPriceToEarnings;
    }

    
    public void setPSPriceToEarnings(final String value) {
        this.psPriceToEarnings = value;
    }

    
    public String getYLDYield1Yr() {
        return this.yldYield1Yr;
    }

    
    public void setYLDYield1Yr(final String value) {
        this.yldYield1Yr = value;
    }

    
    public String getDPDividend() {
        return this.dpDividend;
    }

    
    public void setDPDividend(final String value) {
        this.dpDividend = value;
    }

    
    public String getDPCurrency() {
        return this.dpCurrency;
    }

    
    public void setDPCurrency(final String value) {
        this.dpCurrency = value;
    }

    
    public String getDPDividendDate() {
        return this.dpDividendDate;
    }

    
    public void setDPDividendDate(final String value) {
        this.dpDividendDate = value;
    }

    
    public String getRMBACBeta3Yr() {
        return this.rmbacBeta3Yr;
    }

    
    public void setRMBACBeta3Yr(final String value) {
        this.rmbacBeta3Yr = value;
    }

    
    public String getPIMinimumInitial() {
        return this.piMinimumInitial;
    }

    
    public void setPIMinimumInitial(final String value) {
        this.piMinimumInitial = value;
    }

    
    public String getPIMinimumSubsequent() {
        return this.piMinimumSubsequent;
    }

    
    public void setPIMinimumSubsequent(final String value) {
        this.piMinimumSubsequent = value;
    }

    
    public String getPIMinimumIRA() {
        return this.piMinimumIRA;
    }

    
    public void setPIMinimumIRA(final String value) {
        this.piMinimumIRA = value;
    }

    
    public String getPISubsequentIRA() {
        return this.piSubsequentIRA;
    }

    
    public void setPISubsequentIRA(final String value) {
        this.piSubsequentIRA = value;
    }

    
    public String getPIPurchaseCurrencyId() {
        return this.piPurchaseCurrencyId;
    }

    
    public void setPIPurchaseCurrencyId(final String value) {
        this.piPurchaseCurrencyId = value;
    }

    
    public String getPIMinimumInitialInvestmentUnit() {
        return this.piMinimumInitialInvestmentUnit;
    }

    
    public void setPIMinimumInitialInvestmentUnit(final String value) {
        this.piMinimumInitialInvestmentUnit = value;
    }

    
    public String getPIMinimumSubsequentUnit() {
        return this.piMinimumSubsequentUnit;
    }

    
    public void setPIMinimumSubsequentUnit(final String value) {
        this.piMinimumSubsequentUnit = value;
    }

    
    public PIClosedToInvestors getPIClosedToInvestors() {
        return this.piClosedToInvestors;
    }

    
    public void setPIClosedToInvestors(final PIClosedToInvestors value) {
        this.piClosedToInvestors = value;
    }

    
    public String getLSMaximumFrontLoad() {
        return this.lsMaximumFrontLoad;
    }

    
    public void setLSMaximumFrontLoad(final String value) {
        this.lsMaximumFrontLoad = value;
    }

    
    public String getLSMaximumDeferLoad() {
        return this.lsMaximumDeferLoad;
    }

    
    public void setLSMaximumDeferLoad(final String value) {
        this.lsMaximumDeferLoad = value;
    }

    
    public String getPFActualManagementFee() {
        return this.pfActualManagementFee;
    }

    
    public void setPFActualManagementFee(final String value) {
        this.pfActualManagementFee = value;
    }

    
    public ProspectusCustodianFee getProspectusCustodianFee() {
        return this.prospectusCustodianFee;
    }

    
    public void setProspectusCustodianFee(final ProspectusCustodianFee prospectusCustodianFee) {
        this.prospectusCustodianFee = prospectusCustodianFee;
    }

    
    public String getARFMER() {
        return this.arfmer;
    }

    
    public void setARFMER(final String value) {
        this.arfmer = value;
    }

    
    public FSCBIFundServDetails getFSCBIFundServDetails() {
        return this.fscbiFundServDetails;
    }

    
    public void setFSCBIFundServDetails(final FSCBIFundServDetails value) {
        this.fscbiFundServDetails = value;
    }

    
    public String getFscbiShareClassType() {
        return this.fscbiShareClassType;
    }

    
    public void setFscbiShareClassType(final String fscbiShareClassType) {
        this.fscbiShareClassType = fscbiShareClassType;
    }

    
    public String getARFAnnualReportDate() {
        return this.arfAnnualReportDate;
    }

    
    public void setARFAnnualReportDate(final String value) {
        this.arfAnnualReportDate = value;
    }

    
    public String getMRRatingOverall() {
        return this.mrRatingOverall;
    }

    
    public void setMRRatingOverall(final String value) {
        this.mrRatingOverall = value;
    }

    
    public String getMRRating3Year() {
        return this.mrRating3Year;
    }

    
    public void setMRRating3Year(final String value) {
        this.mrRating3Year = value;
    }

    
    public String getMRRating5Year() {
        return this.mrRating5Year;
    }

    
    public void setMRRating5Year(final String value) {
        this.mrRating5Year = value;
    }

    
    public String getMRRating10Year() {
        return this.mrRating10Year;
    }

    
    public void setMRRating10Year(final String value) {
        this.mrRating10Year = value;
    }

    
    public String getTARRatingOverall() {
        return this.tarRatingOverall;
    }

    
    public void setTARRatingOverall(final String value) {
        this.tarRatingOverall = value;
    }

    
    public String getTARRating3Yr() {
        return this.tarRating3Yr;
    }

    
    public void setTARRating3Yr(final String value) {
        this.tarRating3Yr = value;
    }

    
    public String getTARRating5Yr() {
        return this.tarRating5Yr;
    }

    
    public void setTARRating5Yr(final String value) {
        this.tarRating5Yr = value;
    }

    
    public String getTARRating10Yr() {
        return this.tarRating10Yr;
    }

    
    public void setTARRating10Yr(final String value) {
        this.tarRating10Yr = value;
    }

    
    public String getMRRatingDate() {
        return this.mrRatingDate;
    }

    
    public void setMRRatingDate(final String value) {
        this.mrRatingDate = value;
    }

    
    public AMCBDistributorCompanies getAMCBDistributorCompanies() {
        return this.amcbDistributorCompanies;
    }

    
    public void setAMCBDistributorCompanies(final AMCBDistributorCompanies value) {
        this.amcbDistributorCompanies = value;
    }

    
    public String getFSCBILocalPhone() {
        return this.fscbiLocalPhone;
    }

    
    public void setFSCBILocalPhone(final String value) {
        this.fscbiLocalPhone = value;
    }

    
    public String getAMCBFax() {
        return this.amcbFax;
    }

    
    public void setAMCBFax(final String value) {
        this.amcbFax = value;
    }

    
    public String getFSCBIProviderCompanyWebsite() {
        return this.fscbiProviderCompanyWebsite;
    }

    
    public void setFSCBIProviderCompanyWebsite(final String value) {
        this.fscbiProviderCompanyWebsite = value;
    }

    
    public FMManagers getFMManagers() {
        return this.fmManagers;
    }

    
    public void setFMManagers(final FMManagers value) {
        this.fmManagers = value;
    }

    
    public FM2Managers getFM2Managers() {
        return this.fm2Managers;
    }

    
    public void setFM2Managers(final FM2Managers fm2Managers) {
        this.fm2Managers = fm2Managers;
    }

    
    public AMCBProviderCompanyCountryHeadquarters getAMCBProviderCompanyCountryHeadquarters() {
        return this.amcbProviderCompanyCountryHeadquarters;
    }

    
    public void setAMCBProviderCompanyCountryHeadquarters(final AMCBProviderCompanyCountryHeadquarters value) {
        this.amcbProviderCompanyCountryHeadquarters = value;
    }

    
    public String getOnGoingCharge() {
        return this.onGoingCharge;
    }

    
    public void setOnGoingCharge(final String onGoingCharge) {
        this.onGoingCharge = onGoingCharge;
    }

    
    public String getId() {
        return this.id;
    }

    
    public void setId(final String value) {
        this.id = value;
    }

    
    public String getMPTPIIndexID() {
        return this.mptpiIndexID;
    }

    
    public void setMPTPIIndexID(final String value) {
        this.mptpiIndexID = value;
    }

    
    public String getCYRPrimaryIndexYTD() {
        return this.cyrPrimaryIndexYTD;
    }

    
    public void setCYRPrimaryIndexYTD(final String cyrPrimaryIndexYTD) {
        this.cyrPrimaryIndexYTD = cyrPrimaryIndexYTD;
    }

    
    public String getCYRPrimaryIndexYear1() {
        return this.cyrPrimaryIndexYear1;
    }

    
    public void setCYRPrimaryIndexYear1(final String value) {
        this.cyrPrimaryIndexYear1 = value;
    }

    
    public String getCYRPrimaryIndexYear10() {
        return this.cyrPrimaryIndexYear10;
    }

    
    public void setCYRPrimaryIndexYear10(final String value) {
        this.cyrPrimaryIndexYear10 = value;
    }

    
    public String getCYRPrimaryIndexYear2() {
        return this.cyrPrimaryIndexYear2;
    }

    
    public void setCYRPrimaryIndexYear2(final String value) {
        this.cyrPrimaryIndexYear2 = value;
    }

    
    public String getCYRPrimaryIndexYear3() {
        return this.cyrPrimaryIndexYear3;
    }

    
    public void setCYRPrimaryIndexYear3(final String value) {
        this.cyrPrimaryIndexYear3 = value;
    }

    
    public String getCYRPrimaryIndexYear4() {
        return this.cyrPrimaryIndexYear4;
    }

    
    public void setCYRPrimaryIndexYear4(final String value) {
        this.cyrPrimaryIndexYear4 = value;
    }

    
    public String getCYRPrimaryIndexYear5() {
        return this.cyrPrimaryIndexYear5;
    }

    
    public void setCYRPrimaryIndexYear5(final String value) {
        this.cyrPrimaryIndexYear5 = value;
    }

    
    public String getCYRPrimaryIndexYear6() {
        return this.cyrPrimaryIndexYear6;
    }

    
    public void setCYRPrimaryIndexYear6(final String value) {
        this.cyrPrimaryIndexYear6 = value;
    }

    
    public String getCYRPrimaryIndexYear7() {
        return this.cyrPrimaryIndexYear7;
    }

    
    public void setCYRPrimaryIndexYear7(final String value) {
        this.cyrPrimaryIndexYear7 = value;
    }

    
    public String getCYRPrimaryIndexYear8() {
        return this.cyrPrimaryIndexYear8;
    }

    
    public void setCYRPrimaryIndexYear8(final String value) {
        this.cyrPrimaryIndexYear8 = value;
    }

    
    public String getCYRPrimaryIndexYear9() {
        return this.cyrPrimaryIndexYear9;
    }

    
    public void setCYRPrimaryIndexYear9(final String value) {
        this.cyrPrimaryIndexYear9 = value;
    }

    
    public String getAabrpAssetAllocBondNet() {
        return this.aabrpAssetAllocBondNet;
    }

    
    public void setAabrpAssetAllocBondNet(final String aabrpAssetAllocBondNet) {
        this.aabrpAssetAllocBondNet = aabrpAssetAllocBondNet;
    }

    
    public String getAabrpPreferredStockNet() {
        return this.aabrpPreferredStockNet;
    }

    
    public void setAabrpPreferredStockNet(final String aabrpPreferredStockNet) {
        this.aabrpPreferredStockNet = aabrpPreferredStockNet;
    }

    
    public String getAabrpAssetAllocCashNet() {
        return this.aabrpAssetAllocCashNet;
    }

    
    public void setAabrpAssetAllocCashNet(final String aabrpAssetAllocCashNet) {
        this.aabrpAssetAllocCashNet = aabrpAssetAllocCashNet;
    }

    
    public String getAabrpOtherNet() {
        return this.aabrpOtherNet;
    }

    
    public void setAabrpOtherNet(final String aabrpOtherNet) {
        this.aabrpOtherNet = aabrpOtherNet;
    }

    
    public String getAabrpAssetAllocEquityNet() {
        return this.aabrpAssetAllocEquityNet;
    }

    
    public void setAabrpAssetAllocEquityNet(final String aabrpAssetAllocEquityNet) {
        this.aabrpAssetAllocEquityNet = aabrpAssetAllocEquityNet;
    }

    
    public String getCqbrpCreditQualA() {
        return this.cqbrpCreditQualA;
    }

    
    public void setCqbrpCreditQualA(final String cqbrpCreditQualA) {
        this.cqbrpCreditQualA = cqbrpCreditQualA;
    }

    
    public String getCqbrpCreditQualAA() {
        return this.cqbrpCreditQualAA;
    }

    
    public void setCqbrpCreditQualAA(final String cqbrpCreditQualAA) {
        this.cqbrpCreditQualAA = cqbrpCreditQualAA;
    }

    
    public String getCqbrpCreditQualAAA() {
        return this.cqbrpCreditQualAAA;
    }

    
    public void setCqbrpCreditQualAAA(final String cqbrpCreditQualAAA) {
        this.cqbrpCreditQualAAA = cqbrpCreditQualAAA;
    }

    
    public String getCqbrpCreditQualB() {
        return this.cqbrpCreditQualB;
    }

    
    public void setCqbrpCreditQualB(final String cqbrpCreditQualB) {
        this.cqbrpCreditQualB = cqbrpCreditQualB;
    }

    
    public String getCqbrpCreditQualBB() {
        return this.cqbrpCreditQualBB;
    }

    
    public void setCqbrpCreditQualBB(final String cqbrpCreditQualBB) {
        this.cqbrpCreditQualBB = cqbrpCreditQualBB;
    }

    
    public String getCqbrpCreditQualBBB() {
        return this.cqbrpCreditQualBBB;
    }

    
    public void setCqbrpCreditQualBBB(final String cqbrpCreditQualBBB) {
        this.cqbrpCreditQualBBB = cqbrpCreditQualBBB;
    }

    
    public String getCqbrpCreditQualBelowB() {
        return this.cqbrpCreditQualBelowB;
    }

    
    public void setCqbrpCreditQualBelowB(final String cqbrpCreditQualBelowB) {
        this.cqbrpCreditQualBelowB = cqbrpCreditQualBelowB;
    }

    
    public String getCqbrpCreditQualNotRated() {
        return this.cqbrpCreditQualNotRated;
    }

    
    public void setCqbrpCreditQualNotRated(final String cqbrpCreditQualNotRated) {
        this.cqbrpCreditQualNotRated = cqbrpCreditQualNotRated;
    }

    
    public String getCqbrpCreditQualDate() {
        return this.cqbrpCreditQualDate;
    }

    
    public void setCqbrpCreditQualDate(final String cqbrpCreditQualDate) {
        this.cqbrpCreditQualDate = cqbrpCreditQualDate;
    }

    
    public String getTtrReturn1Mth() {
        return this.ttrReturn1Mth;
    }

    
    public void setTtrReturn1Mth(final String ttrReturn1Mth) {
        this.ttrReturn1Mth = ttrReturn1Mth;
    }

    
    public String getTtrReturn3Mth() {
        return this.ttrReturn3Mth;
    }

    
    public void setTtrReturn3Mth(final String ttrReturn3Mth) {
        this.ttrReturn3Mth = ttrReturn3Mth;
    }

    
    public String getTtrReturn6Mth() {
        return this.ttrReturn6Mth;
    }

    
    public void setTtrReturn6Mth(final String ttrReturn6Mth) {
        this.ttrReturn6Mth = ttrReturn6Mth;
    }

    
    public String getTtrReturn1Yr() {
        return this.ttrReturn1Yr;
    }

    
    public void setTtrReturn1Yr(final String ttrReturn1Yr) {
        this.ttrReturn1Yr = ttrReturn1Yr;
    }

    
    public String getTtrReturn3Yr() {
        return this.ttrReturn3Yr;
    }

    
    public void setTtrReturn3Yr(final String ttrReturn3Yr) {
        this.ttrReturn3Yr = ttrReturn3Yr;
    }

    
    public String getTtrReturn5Yr() {
        return this.ttrReturn5Yr;
    }

    
    public void setTtrReturn5Yr(final String ttrReturn5Yr) {
        this.ttrReturn5Yr = ttrReturn5Yr;
    }

    
    public String getTtrReturn10Yr() {
        return this.ttrReturn10Yr;
    }

    
    public void setTtrReturn10Yr(final String ttrReturn10Yr) {
        this.ttrReturn10Yr = ttrReturn10Yr;
    }

    
    public String getTtrBestFitIndexReturn1Mth() {
        return this.ttrBestFitIndexReturn1Mth;
    }

    
    public void setTtrBestFitIndexReturn1Mth(final String ttrBestFitIndexReturn1Mth) {
        this.ttrBestFitIndexReturn1Mth = ttrBestFitIndexReturn1Mth;
    }

    
    public String getTtrBestFitIndexReturn3Mth() {
        return this.ttrBestFitIndexReturn3Mth;
    }

    
    public void setTtrBestFitIndexReturn3Mth(final String ttrBestFitIndexReturn3Mth) {
        this.ttrBestFitIndexReturn3Mth = ttrBestFitIndexReturn3Mth;
    }

    
    public String getTtrBestFitIndexReturn6Mth() {
        return this.ttrBestFitIndexReturn6Mth;
    }

    
    public void setTtrBestFitIndexReturn6Mth(final String ttrBestFitIndexReturn6Mth) {
        this.ttrBestFitIndexReturn6Mth = ttrBestFitIndexReturn6Mth;
    }

    
    public String getTtrBestFitIndexReturn1Yr() {
        return this.ttrBestFitIndexReturn1Yr;
    }

    
    public void setTtrBestFitIndexReturn1Yr(final String ttrBestFitIndexReturn1Yr) {
        this.ttrBestFitIndexReturn1Yr = ttrBestFitIndexReturn1Yr;
    }

    
    public String getTtrBestFitIndexReturn3Yr() {
        return this.ttrBestFitIndexReturn3Yr;
    }

    
    public void setTtrBestFitIndexReturn3Yr(final String ttrBestFitIndexReturn3Yr) {
        this.ttrBestFitIndexReturn3Yr = ttrBestFitIndexReturn3Yr;
    }

    
    public String getTtrBestFitIndexReturn5Yr() {
        return this.ttrBestFitIndexReturn5Yr;
    }

    
    public void setTtrBestFitIndexReturn5Yr(final String ttrBestFitIndexReturn5Yr) {
        this.ttrBestFitIndexReturn5Yr = ttrBestFitIndexReturn5Yr;
    }

    
    public String getTtrBestFitIndexReturn10Yr() {
        return this.ttrBestFitIndexReturn10Yr;
    }

    
    public void setTtrBestFitIndexReturn10Yr(final String ttrBestFitIndexReturn10Yr) {
        this.ttrBestFitIndexReturn10Yr = ttrBestFitIndexReturn10Yr;
    }

    
    public String getTtrCategoryReturn1Mth() {
        return this.ttrCategoryReturn1Mth;
    }

    
    public void setTtrCategoryReturn1Mth(final String ttrCategoryReturn1Mth) {
        this.ttrCategoryReturn1Mth = ttrCategoryReturn1Mth;
    }

    
    public String getTtrCategoryReturn3Mth() {
        return this.ttrCategoryReturn3Mth;
    }

    
    public void setTtrCategoryReturn3Mth(final String ttrCategoryReturn3Mth) {
        this.ttrCategoryReturn3Mth = ttrCategoryReturn3Mth;
    }

    
    public String getTtrCategoryReturn6Mth() {
        return this.ttrCategoryReturn6Mth;
    }

    
    public void setTtrCategoryReturn6Mth(final String ttrCategoryReturn6Mth) {
        this.ttrCategoryReturn6Mth = ttrCategoryReturn6Mth;
    }

    
    public String getTtrCategoryReturn1Yr() {
        return this.ttrCategoryReturn1Yr;
    }

    
    public void setTtrCategoryReturn1Yr(final String ttrCategoryReturn1Yr) {
        this.ttrCategoryReturn1Yr = ttrCategoryReturn1Yr;
    }

    
    public String getTtrCategoryReturn3Yr() {
        return this.ttrCategoryReturn3Yr;
    }

    
    public void setTtrCategoryReturn3Yr(final String ttrCategoryReturn3Yr) {
        this.ttrCategoryReturn3Yr = ttrCategoryReturn3Yr;
    }

    
    public String getTtrCategoryReturn5Yr() {
        return this.ttrCategoryReturn5Yr;
    }

    
    public void setTtrCategoryReturn5Yr(final String ttrCategoryReturn5Yr) {
        this.ttrCategoryReturn5Yr = ttrCategoryReturn5Yr;
    }

    
    public String getTtrCategoryReturn10Yr() {
        return this.ttrCategoryReturn10Yr;
    }

    
    public void setTtrCategoryReturn10Yr(final String ttrCategoryReturn10Yr) {
        this.ttrCategoryReturn10Yr = ttrCategoryReturn10Yr;
    }

    
    public String getDpReturn1Mth() {
        return this.dpReturn1Mth;
    }

    
    public void setDpReturn1Mth(final String dpReturn1Mth) {
        this.dpReturn1Mth = dpReturn1Mth;
    }

    
    public String getDpReturn3Mth() {
        return this.dpReturn3Mth;
    }

    
    public void setDpReturn3Mth(final String dpReturn3Mth) {
        this.dpReturn3Mth = dpReturn3Mth;
    }

    
    public String getDpReturn6Mth() {
        return this.dpReturn6Mth;
    }

    
    public void setDpReturn6Mth(final String dpReturn6Mth) {
        this.dpReturn6Mth = dpReturn6Mth;
    }

    
    public String getDpReturnYTD() {
        return this.dpReturnYTD;
    }

    
    public void setDpReturnYTD(final String dpReturnYTD) {
        this.dpReturnYTD = dpReturnYTD;
    }

    
    public String getDpReturn1Yr() {
        return this.dpReturn1Yr;
    }

    
    public void setDpReturn1Yr(final String dpReturn1Yr) {
        this.dpReturn1Yr = dpReturn1Yr;
    }

    
    public String getDpReturn3Yr() {
        return this.dpReturn3Yr;
    }

    
    public void setDpReturn3Yr(final String dpReturn3Yr) {
        this.dpReturn3Yr = dpReturn3Yr;
    }

    
    public String getDpReturn5Yr() {
        return this.dpReturn5Yr;
    }

    
    public void setDpReturn5Yr(final String dpReturn5Yr) {
        this.dpReturn5Yr = dpReturn5Yr;
    }

    
    public String getDpReturn10Yr() {
        return this.dpReturn10Yr;
    }

    
    public void setDpReturn10Yr(final String dpReturn10Yr) {
        this.dpReturn10Yr = dpReturn10Yr;
    }

    
    public String getDpDayEndDate() {
        return this.dpDayEndDate;
    }

    
    public void setDpDayEndDate(final String dpDayEndDate) {
        this.dpDayEndDate = dpDayEndDate;
    }

    
    public String getTtrMonthEndDate() {
        return this.ttrMonthEndDate;
    }

    
    public void setTtrMonthEndDate(final String ttrMonthEndDate) {
        this.ttrMonthEndDate = ttrMonthEndDate;
    }

    
    public String getSrStubYearEndReturnEndDate() {
        return this.srStubYearEndReturnEndDate;
    }

    
    public void setSrStubYearEndReturnEndDate(final String srStubYearEndReturnEndDate) {
        this.srStubYearEndReturnEndDate = srStubYearEndReturnEndDate;
    }

    
    public String getSrStubYearEndReturn() {
        return this.srStubYearEndReturn;
    }

    
    public void setSrStubYearEndReturn(final String srStubYearEndReturn) {
        this.srStubYearEndReturn = srStubYearEndReturn;
    }

    
    public String getDpCategoryReturn1Mth() {
        return this.dpCategoryReturn1Mth;
    }

    
    public void setDpCategoryReturn1Mth(final String dpCategoryReturn1Mth) {
        this.dpCategoryReturn1Mth = dpCategoryReturn1Mth;
    }

    
    public String getDpCategoryReturn3Mth() {
        return this.dpCategoryReturn3Mth;
    }

    
    public void setDpCategoryReturn3Mth(final String dpCategoryReturn3Mth) {
        this.dpCategoryReturn3Mth = dpCategoryReturn3Mth;
    }

    
    public String getDpCategoryReturn6Mth() {
        return this.dpCategoryReturn6Mth;
    }

    
    public void setDpCategoryReturn6Mth(final String dpCategoryReturn6Mth) {
        this.dpCategoryReturn6Mth = dpCategoryReturn6Mth;
    }

    
    public String getDpCategoryReturn1Yr() {
        return this.dpCategoryReturn1Yr;
    }

    
    public void setDpCategoryReturn1Yr(final String dpCategoryReturn1Yr) {
        this.dpCategoryReturn1Yr = dpCategoryReturn1Yr;
    }

    
    public String getDpCategoryReturn3Yr() {
        return this.dpCategoryReturn3Yr;
    }

    
    public void setDpCategoryReturn3Yr(final String dpCategoryReturn3Yr) {
        this.dpCategoryReturn3Yr = dpCategoryReturn3Yr;
    }

    
    public String getDpCategoryReturn5Yr() {
        return this.dpCategoryReturn5Yr;
    }

    
    public void setDpCategoryReturn5Yr(final String dpCategoryReturn5Yr) {
        this.dpCategoryReturn5Yr = dpCategoryReturn5Yr;
    }

    
    public String getDpCategoryReturn10Yr() {
        return this.dpCategoryReturn10Yr;
    }

    
    public void setDpCategoryReturn10Yr(final String dpCategoryReturn10Yr) {
        this.dpCategoryReturn10Yr = dpCategoryReturn10Yr;
    }

    
    public String getDpCategoryReturnYTD() {
        return this.dpCategoryReturnYTD;
    }

    
    public void setDpCategoryReturnYTD(final String dpCategoryReturnYTD) {
        this.dpCategoryReturnYTD = dpCategoryReturnYTD;
    }

    
    public String getTtrPrimaryIndexReturn1Mth() {
        return this.ttrPrimaryIndexReturn1Mth;
    }

    
    public void setTtrPrimaryIndexReturn1Mth(final String ttrPrimaryIndexReturn1Mth) {
        this.ttrPrimaryIndexReturn1Mth = ttrPrimaryIndexReturn1Mth;
    }

    
    public String getTtrPrimaryIndexReturn3Mth() {
        return this.ttrPrimaryIndexReturn3Mth;
    }

    
    public void setTtrPrimaryIndexReturn3Mth(final String ttrPrimaryIndexReturn3Mth) {
        this.ttrPrimaryIndexReturn3Mth = ttrPrimaryIndexReturn3Mth;
    }

    
    public String getTtrPrimaryIndexReturn6Mth() {
        return this.ttrPrimaryIndexReturn6Mth;
    }

    
    public void setTtrPrimaryIndexReturn6Mth(final String ttrPrimaryIndexReturn6Mth) {
        this.ttrPrimaryIndexReturn6Mth = ttrPrimaryIndexReturn6Mth;
    }

    
    public String getTtrPrimaryIndexReturn1Yr() {
        return this.ttrPrimaryIndexReturn1Yr;
    }

    
    public void setTtrPrimaryIndexReturn1Yr(final String ttrPrimaryIndexReturn1Yr) {
        this.ttrPrimaryIndexReturn1Yr = ttrPrimaryIndexReturn1Yr;
    }

    
    public String getTtrPrimaryIndexReturn3Yr() {
        return this.ttrPrimaryIndexReturn3Yr;
    }

    
    public void setTtrPrimaryIndexReturn3Yr(final String ttrPrimaryIndexReturn3Yr) {
        this.ttrPrimaryIndexReturn3Yr = ttrPrimaryIndexReturn3Yr;
    }

    
    public String getTtrPrimaryIndexReturn5Yr() {
        return this.ttrPrimaryIndexReturn5Yr;
    }

    
    public void setTtrPrimaryIndexReturn5Yr(final String ttrPrimaryIndexReturn5Yr) {
        this.ttrPrimaryIndexReturn5Yr = ttrPrimaryIndexReturn5Yr;
    }

    
    public String getTtrPrimaryIndexReturn10Yr() {
        return this.ttrPrimaryIndexReturn10Yr;
    }

    
    public void setTtrPrimaryIndexReturn10Yr(final String ttrPrimaryIndexReturn10Yr) {
        this.ttrPrimaryIndexReturn10Yr = ttrPrimaryIndexReturn10Yr;
    }

    
    public String getTtrPrimaryIndexReturnYTD() {
        return this.ttrPrimaryIndexReturnYTD;
    }

    
    public void setTtrPrimaryIndexReturnYTD(final String ttrPrimaryIndexReturnYTD) {
        this.ttrPrimaryIndexReturnYTD = ttrPrimaryIndexReturnYTD;
    }

    public String getTsDayEndBidOfferPricesDate() {
        return this.tsDayEndBidOfferPricesDate;
    }

    public void setTsDayEndBidOfferPricesDate(final String tsDayEndBidOfferPricesDate) {
        this.tsDayEndBidOfferPricesDate = tsDayEndBidOfferPricesDate;
    }

    public String getTsDayEndNAVDate() {
        return this.tsDayEndNAVDate;
    }

    public void setTsDayEndNAVDate(final String tsDayEndNAVDate) {
        this.tsDayEndNAVDate = tsDayEndNAVDate;
    }

    
    public FBPrimaryProspectusBenchmarks getFbPrimaryProspectusBenchmarks() {
        return this.fbPrimaryProspectusBenchmarks;
    }

    
    public void setFbPrimaryProspectusBenchmarks(final FBPrimaryProspectusBenchmarks fbPrimaryProspectusBenchmarks) {
        this.fbPrimaryProspectusBenchmarks = fbPrimaryProspectusBenchmarks;
    }

    
    public String getAtActualFrontLoad() {
        return this.atActualFrontLoad;
    }

    
    public void setAtActualFrontLoad(final String atActualFrontLoad) {
        this.atActualFrontLoad = atActualFrontLoad;
    }
}
