//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.25 at 03:58:04 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.quotesummary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"country", "closedToAllDate", "closedToNewDate"})
@XmlRootElement(name = "ClosedToInvestor")
public class ClosedToInvestor {

    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "ClosedToAllDate", required = true)
    protected String closedToAllDate;
    @XmlElement(name = "ClosedToNewDate", required = true)
    protected String closedToNewDate;


    public String getCountry() {
        return this.country;
    }


    public void setCountry(final String value) {
        this.country = value;
    }


    public String getClosedToAllDate() {
        return this.closedToAllDate;
    }


    public void setClosedToAllDate(final String value) {
        this.closedToAllDate = value;
    }


    public String getClosedToNewDate() {
        return this.closedToNewDate;
    }


    public void setClosedToNewDate(final String value) {
        this.closedToNewDate = value;
    }

}
