//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.01.11 at 04:02:36 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.quotesummary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"countryId", "countryName", "primaryHeadquarter", "companyCity", "companyProvince",
    "companyPostalCode", "companyAddress", "companyFax", "companyPhone"})
@XmlRootElement(name = "CountryHeadquarters")
public class CountryHeadquarters {

    @XmlElement(name = "CountryId", required = true)
    protected String countryId;
    @XmlElement(name = "CountryName", required = true)
    protected String countryName;
    @XmlElement(name = "PrimaryHeadquarter", required = true)
    protected String primaryHeadquarter;
    @XmlElement(name = "CompanyCity", required = true)
    protected String companyCity;
    @XmlElement(name = "CompanyProvince", required = true)
    protected String companyProvince;
    @XmlElement(name = "CompanyPostalCode", required = true)
    protected String companyPostalCode;
    @XmlElement(name = "CompanyAddress", required = true)
    protected String companyAddress;
    @XmlElement(name = "CompanyFax", required = true)
    protected String companyFax;
    @XmlElement(name = "CompanyPhone", required = true)
    protected String companyPhone;


    public String getCountryId() {
        return this.countryId;
    }


    public void setCountryId(final String value) {
        this.countryId = value;
    }


    public String getCountryName() {
        return this.countryName;
    }


    public void setCountryName(final String value) {
        this.countryName = value;
    }


    public String getPrimaryHeadquarter() {
        return this.primaryHeadquarter;
    }


    public void setPrimaryHeadquarter(final String value) {
        this.primaryHeadquarter = value;
    }


    public String getCompanyCity() {
        return this.companyCity;
    }


    public void setCompanyCity(final String value) {
        this.companyCity = value;
    }


    public String getCompanyProvince() {
        return this.companyProvince;
    }


    public void setCompanyProvince(final String value) {
        this.companyProvince = value;
    }


    public String getCompanyPostalCode() {
        return this.companyPostalCode;
    }


    public void setCompanyPostalCode(final String value) {
        this.companyPostalCode = value;
    }


    public String getCompanyAddress() {
        return this.companyAddress;
    }


    public void setCompanyAddress(final String value) {
        this.companyAddress = value;
    }


    public String getCompanyFax() {
        return this.companyFax;
    }


    public void setCompanyFax(final String value) {
        this.companyFax = value;
    }


    public String getCompanyPhone() {
        return this.companyPhone;
    }


    public void setCompanyPhone(final String value) {
        this.companyPhone = value;
    }

}
