//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.12 at 10:43:42 AM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.quotesummary;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"fundServDetail"})
@XmlRootElement(name = "FSCBI-FundServDetails")
public class FSCBIFundServDetails {

    @XmlElement(name = "FundServDetail", required = true)
    protected List<FundServDetail> fundServDetail;

    
    public List<FundServDetail> getFundServDetail() {
        return this.fundServDetail;
    }

    
    public void setFundServDetail(final List<FundServDetail> value) {
        this.fundServDetail = value;
    }

}
