//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.12 at 10:43:42 AM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.quotesummary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"fundServ", "classType", "currencyId"})
@XmlRootElement(name = "FundServDetail")
public class FundServDetail {

    @XmlElement(name = "FundServ", required = true)
    protected String fundServ;
    @XmlElement(name = "ClassType", required = true)
    protected String classType;
    @XmlElement(name = "CurrencyId", required = true)
    protected String currencyId;


    public String getFundServ() {
        return this.fundServ;
    }


    public void setFundServ(final String value) {
        this.fundServ = value;
    }


    public String getClassType() {
        return this.classType;
    }


    public void setClassType(final String value) {
        this.classType = value;
    }


    public String getCurrencyId() {
        return this.currencyId;
    }


    public void setCurrencyId(final String value) {
        this.currencyId = value;
    }

}
