//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.25 at 03:58:04 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.quotesummary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"closedToInvestor"})
@XmlRootElement(name = "PI-ClosedToInvestors")
public class PIClosedToInvestors {

    @XmlElement(name = "ClosedToInvestor", required = true)
    protected ClosedToInvestor closedToInvestor;


    public ClosedToInvestor getClosedToInvestor() {
        return this.closedToInvestor;
    }


    public void setClosedToInvestor(final ClosedToInvestor value) {
        this.closedToInvestor = value;
    }

}
