//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.12 at 10:43:42 AM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.quotesummary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"companyID", "companyName", "companyCity", "companyProvince", "companyCountry",
    "companyPostalCode", "companyAddress"})
@XmlRootElement(name = "SubAdvisorCompany")
public class SubAdvisorCompany {

    @XmlElement(name = "CompanyID", required = true)
    protected String companyID;
    @XmlElement(name = "CompanyName", required = true)
    protected String companyName;
    @XmlElement(name = "CompanyCity", required = true)
    protected String companyCity;
    @XmlElement(name = "CompanyProvince", required = true)
    protected String companyProvince;
    @XmlElement(name = "CompanyCountry", required = true)
    protected String companyCountry;
    @XmlElement(name = "CompanyPostalCode", required = true)
    protected String companyPostalCode;
    @XmlElement(name = "CompanyAddress", required = true)
    protected String companyAddress;


    public String getCompanyID() {
        return this.companyID;
    }


    public void setCompanyID(final String value) {
        this.companyID = value;
    }


    public String getCompanyName() {
        return this.companyName;
    }


    public void setCompanyName(final String value) {
        this.companyName = value;
    }


    public String getCompanyCity() {
        return this.companyCity;
    }


    public void setCompanyCity(final String value) {
        this.companyCity = value;
    }


    public String getCompanyProvince() {
        return this.companyProvince;
    }


    public void setCompanyProvince(final String value) {
        this.companyProvince = value;
    }


    public String getCompanyCountry() {
        return this.companyCountry;
    }


    public void setCompanyCountry(final String value) {
        this.companyCountry = value;
    }


    public String getCompanyPostalCode() {
        return this.companyPostalCode;
    }


    public void setCompanyPostalCode(final String value) {
        this.companyPostalCode = value;
    }


    public String getCompanyAddress() {
        return this.companyAddress;
    }


    public void setCompanyAddress(final String value) {
        this.companyAddress = value;
    }

}
