//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.11.01 at 03:40:17 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.fundcompare;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"fscbiFundName", "fscbiFundServs", "fscbiCurrencyId", "fscbiTicker", "fscbiFundServDetails",
    "dpCategoryName", "dpDayEndNAV", "dpNavChange", "dmpDayEndPrice", "dpReturn1Day", "fnaSurveyedFundNetAssets",
    "fnaAsOfOriginalReportedCurrencyId", "naShareClassNetAssets", "mrRatingOverall", "arfmer", "yldYield1Yr",
    "pfActualManagementFee", "kdInceptionDate", "psTurnoverRatio", "psEquityStylebox", "tarRatingOverall",
    "psAverageCreditQuality", "ttrrRank1YrQuartile", "ttrReturn1Mth", "ttrReturn3Mth", "ttrReturn6Mth", "ttrReturn1Yr",
    "ttrReturn3Yr", "ttrReturn5Yr", "ttrReturn10Yr", "ttrReturnSinceInception", "ttrReturnYTD", "cyrYear1", "cyrYear2", "cyrYear3",
    "cyrYear4", "cyrYear5", "rmbacBeta1Yr", "rmStdDev1Yr", "rmbacAlpha1Yr", "rmSharpeRatio1Yr", "rmbacRsquared1Yr", "rmbacBeta3Yr",
    "rmStdDev3Yr", "rmbacAlpha3Yr", "rmSharpeRatio3Yr", "rmbacRsquared3Yr", "rmbacBeta5Yr", "rmStdDev5Yr", "rmbacAlpha5Yr",
    "rmSharpeRatio5Yr", "rmbacRsquared5Yr", "rmbacBeta10Yr", "rmStdDev10Yr", "rmbacAlpha10Yr", "rmSharpeRatio10Yr",
    "rmbacRsquared10Yr", "piMinimumInitial", "piMinimumSubsequent", "piMinimumIRA", "piPurchaseCurrencyId", "atrrsp",
    "fscbiShareClassType", "fnaAsOfOriginalReported", "mrRatingDate", "ttrMonthEndDate", "rmbacEndDate", "rmEndDate",
    "dpDayEndDate"})
@XmlRootElement(name = "api")
public class Api {

    @XmlElement(name = "FSCBI-FundName", required = true)
    protected String fscbiFundName;
    @XmlElement(name = "FSCBI-FundServs", required = true)
    protected FSCBIFundServs fscbiFundServs;
    @XmlElement(name = "FSCBI-CurrencyId", required = true)
    protected String fscbiCurrencyId;
    @XmlElement(name = "FSCBI-Ticker", required = true)
    protected String fscbiTicker;
    @XmlElement(name = "FSCBI-FundServDetails", required = true)
    protected FSCBIFundServDetails fscbiFundServDetails;
    @XmlElement(name = "DP-CategoryName", required = true)
    protected String dpCategoryName;
    @XmlElement(name = "DP-DayEndNAV", required = true)
    protected String dpDayEndNAV;
    @XmlElement(name = "DP-NAVChange", required = true)
    protected String dpNavChange;
    @XmlElement(name = "DMP-DayEndPrice", required = true)
    protected String dmpDayEndPrice;
    @XmlElement(name = "DP-Return1Day", required = true)
    protected String dpReturn1Day;
    @XmlElement(name = "FNA-SurveyedFundNetAssets", required = true)
    protected String fnaSurveyedFundNetAssets;
    @XmlElement(name = "FNA-AsOfOriginalReportedCurrencyId", required = true)
    protected String fnaAsOfOriginalReportedCurrencyId;
    @XmlElement(name = "NA-ShareClassNetAssets", required = true)
    protected String naShareClassNetAssets;
    @XmlElement(name = "MR-RatingOverall", required = true)
    protected String mrRatingOverall;
    @XmlElement(name = "ARF-MER", required = true)
    protected String arfmer;
    @XmlElement(name = "YLD-Yield1Yr", required = true)
    protected String yldYield1Yr;
    @XmlElement(name = "PF-ActualManagementFee", required = true)
    protected String pfActualManagementFee;
    @XmlElement(name = "KD-InceptionDate", required = true)
    protected String kdInceptionDate;
    @XmlElement(name = "PS-TurnoverRatio", required = true)
    protected String psTurnoverRatio;
    @XmlElement(name = "PS-EquityStylebox", required = true)
    protected String psEquityStylebox;
    @XmlElement(name = "TAR-RatingOverall", required = true)
    protected String tarRatingOverall;
    @XmlElement(name = "PS-AverageCreditQuality", required = true)
    protected String psAverageCreditQuality;
    @XmlElement(name = "TTRR-Rank1YrQuartile", required = true)
    protected String ttrrRank1YrQuartile;
    @XmlElement(name = "TTR-Return1Mth", required = true)
    protected String ttrReturn1Mth;
    @XmlElement(name = "TTR-Return3Mth", required = true)
    protected String ttrReturn3Mth;
    @XmlElement(name = "TTR-Return6Mth", required = true)
    protected String ttrReturn6Mth;
    @XmlElement(name = "TTR-Return1Yr", required = true)
    protected String ttrReturn1Yr;
    @XmlElement(name = "TTR-Return3Yr", required = true)
    protected String ttrReturn3Yr;
    @XmlElement(name = "TTR-Return5Yr", required = true)
    protected String ttrReturn5Yr;
    @XmlElement(name = "TTR-Return10Yr", required = true)
    protected String ttrReturn10Yr;
    @XmlElement(name = "TTR-ReturnSinceInception", required = true)
    protected String ttrReturnSinceInception;
    @XmlElement(name = "TTR-ReturnYTD", required = true)
    protected String ttrReturnYTD;
    @XmlElement(name = "CYR-Year1", required = true)
    protected String cyrYear1;
    @XmlElement(name = "CYR-Year2", required = true)
    protected String cyrYear2;
    @XmlElement(name = "CYR-Year3", required = true)
    protected String cyrYear3;
    @XmlElement(name = "CYR-Year4", required = true)
    protected String cyrYear4;
    @XmlElement(name = "CYR-Year5", required = true)
    protected String cyrYear5;
    @XmlElement(name = "RMBAC-Beta1Yr", required = true)
    protected String rmbacBeta1Yr;
    @XmlElement(name = "RM-StdDev1Yr", required = true)
    protected String rmStdDev1Yr;
    @XmlElement(name = "RMBAC-Alpha1Yr", required = true)
    protected String rmbacAlpha1Yr;
    @XmlElement(name = "RM-SharpeRatio1Yr", required = true)
    protected String rmSharpeRatio1Yr;
    @XmlElement(name = "RMBAC-Rsquared1Yr", required = true)
    protected String rmbacRsquared1Yr;
    @XmlElement(name = "RMBAC-Beta3Yr", required = true)
    protected String rmbacBeta3Yr;
    @XmlElement(name = "RM-StdDev3Yr", required = true)
    protected String rmStdDev3Yr;
    @XmlElement(name = "RMBAC-Alpha3Yr", required = true)
    protected String rmbacAlpha3Yr;
    @XmlElement(name = "RM-SharpeRatio3Yr", required = true)
    protected String rmSharpeRatio3Yr;
    @XmlElement(name = "RMBAC-Rsquared3Yr", required = true)
    protected String rmbacRsquared3Yr;
    @XmlElement(name = "RMBAC-Beta5Yr", required = true)
    protected String rmbacBeta5Yr;
    @XmlElement(name = "RM-StdDev5Yr", required = true)
    protected String rmStdDev5Yr;
    @XmlElement(name = "RMBAC-Alpha5Yr", required = true)
    protected String rmbacAlpha5Yr;
    @XmlElement(name = "RM-SharpeRatio5Yr", required = true)
    protected String rmSharpeRatio5Yr;
    @XmlElement(name = "RMBAC-Rsquared5Yr", required = true)
    protected String rmbacRsquared5Yr;
    @XmlElement(name = "RMBAC-Beta10Yr", required = true)
    protected String rmbacBeta10Yr;
    @XmlElement(name = "RM-StdDev10Yr", required = true)
    protected String rmStdDev10Yr;
    @XmlElement(name = "RMBAC-Alpha10Yr", required = true)
    protected String rmbacAlpha10Yr;
    @XmlElement(name = "RM-SharpeRatio10Yr", required = true)
    protected String rmSharpeRatio10Yr;
    @XmlElement(name = "RMBAC-Rsquared10Yr", required = true)
    protected String rmbacRsquared10Yr;
    @XmlElement(name = "PI-MinimumInitial", required = true)
    protected String piMinimumInitial;
    @XmlElement(name = "PI-MinimumSubsequent", required = true)
    protected String piMinimumSubsequent;
    @XmlElement(name = "PI-MinimumIRA", required = true)
    protected String piMinimumIRA;
    @XmlElement(name = "PI-PurchaseCurrencyId", required = true)
    protected String piPurchaseCurrencyId;
    @XmlElement(name = "AT-RRSP", required = true)
    protected String atrrsp;
    @XmlElement(name = "FSCBI-ShareClassType", required = true)
    protected String fscbiShareClassType;
    @XmlAttribute(name = "_id")
    protected String id;
    @XmlElement(name = "FNA-AsOfOriginalReported", required = true)
    protected String fnaAsOfOriginalReported;
    @XmlElement(name = "MR-RatingDate", required = true)
    protected String mrRatingDate;
    @XmlElement(name = "TTR-MonthEndDate", required = true)
    protected String ttrMonthEndDate;
    @XmlElement(name = "RMBAC-EndDate", required = true)
    protected String rmbacEndDate;
    @XmlElement(name = "RM-EndDate", required = true)
    protected String rmEndDate;
    @XmlElement(name = "DP-DayEndDate", required = true)
    protected String dpDayEndDate;


    
    public String getFSCBIFundName() {
        return this.fscbiFundName;
    }

    
    public void setFSCBIFundName(final String value) {
        this.fscbiFundName = value;
    }

    
    public FSCBIFundServs getFSCBIFundServs() {
        return this.fscbiFundServs;
    }

    
    public void setFSCBIFundServs(final FSCBIFundServs value) {
        this.fscbiFundServs = value;
    }

    
    public String getFscbiCurrencyId() {
        return this.fscbiCurrencyId;
    }

    
    public void setFscbiCurrencyId(final String fscbiCurrencyId) {
        this.fscbiCurrencyId = fscbiCurrencyId;
    }

    
    public String getFSCBITicker() {
        return this.fscbiTicker;
    }

    
    public void setFSCBITicker(final String value) {
        this.fscbiTicker = value;
    }

    
    public FSCBIFundServDetails getFSCBIFundServDetails() {
        return this.fscbiFundServDetails;
    }

    
    public String getMrRatingDate() {
        return this.mrRatingDate;
    }

    
    public void setMrRatingDate(final String mrRatingDate) {
        this.mrRatingDate = mrRatingDate;
    }

    
    public String getTtrMonthEndDate() {
        return this.ttrMonthEndDate;
    }

    
    public void setTtrMonthEndDate(final String ttrMonthEndDate) {
        this.ttrMonthEndDate = ttrMonthEndDate;
    }

    
    public String getRmbacEndDate() {
        return this.rmbacEndDate;
    }

    
    public void setRmbacEndDate(final String rmbacEndDate) {
        this.rmbacEndDate = rmbacEndDate;
    }

    
    public String getRmEndDate() {
        return this.rmEndDate;
    }

    
    public void setRmEndDate(final String rmEndDate) {
        this.rmEndDate = rmEndDate;
    }

    
    public void setFSCBIFundServDetails(final FSCBIFundServDetails value) {
        this.fscbiFundServDetails = value;
    }

    
    public String getDPCategoryName() {
        return this.dpCategoryName;
    }

    
    public void setDPCategoryName(final String value) {
        this.dpCategoryName = value;
    }

    
    public String getDPDayEndNAV() {
        return this.dpDayEndNAV;
    }

    
    public void setDPDayEndNAV(final String value) {
        this.dpDayEndNAV = value;
    }

    
    public String getDpNavChange() {
        return this.dpNavChange;
    }

    
    public void setDpNavChange(final String dpNavChange) {
        this.dpNavChange = dpNavChange;
    }

    
    public String getDMPDayEndPrice() {
        return this.dmpDayEndPrice;
    }

    
    public void setDMPDayEndPrice(final String value) {
        this.dmpDayEndPrice = value;
    }

    
    public String getDPReturn1Day() {
        return this.dpReturn1Day;
    }

    
    public void setDPReturn1Day(final String value) {
        this.dpReturn1Day = value;
    }

    
    public String getFNASurveyedFundNetAssets() {
        return this.fnaSurveyedFundNetAssets;
    }

    
    public void setFNASurveyedFundNetAssets(final String value) {
        this.fnaSurveyedFundNetAssets = value;
    }

    
    public String getFnaAsOfOriginalReportedCurrencyId() {
        return this.fnaAsOfOriginalReportedCurrencyId;
    }

    
    public void setFnaAsOfOriginalReportedCurrencyId(final String fnaAsOfOriginalReportedCurrencyId) {
        this.fnaAsOfOriginalReportedCurrencyId = fnaAsOfOriginalReportedCurrencyId;
    }

    
    public String getNAShareClassNetAssets() {
        return this.naShareClassNetAssets;
    }

    
    public void setNAShareClassNetAssets(final String value) {
        this.naShareClassNetAssets = value;
    }

    
    public String getMRRatingOverall() {
        return this.mrRatingOverall;
    }

    
    public void setMRRatingOverall(final String value) {
        this.mrRatingOverall = value;
    }

    
    public String getARFMER() {
        return this.arfmer;
    }

    
    public void setARFMER(final String value) {
        this.arfmer = value;
    }

    
    public String getYLDYield1Yr() {
        return this.yldYield1Yr;
    }

    
    public void setYLDYield1Yr(final String value) {
        this.yldYield1Yr = value;
    }

    
    public String getPfActualManagementFee() {
        return this.pfActualManagementFee;
    }

    
    public void setPfActualManagementFee(final String pfActualManagementFee) {
        this.pfActualManagementFee = pfActualManagementFee;
    }

    
    public String getKDInceptionDate() {
        return this.kdInceptionDate;
    }

    
    public void setKDInceptionDate(final String value) {
        this.kdInceptionDate = value;
    }

    
    public String getPSTurnoverRatio() {
        return this.psTurnoverRatio;
    }

    
    public void setPSTurnoverRatio(final String value) {
        this.psTurnoverRatio = value;
    }

    
    public String getPSEquityStylebox() {
        return this.psEquityStylebox;
    }

    
    public void setPSEquityStylebox(final String value) {
        this.psEquityStylebox = value;
    }

    
    public String getTARRatingOverall() {
        return this.tarRatingOverall;
    }

    
    public void setTARRatingOverall(final String value) {
        this.tarRatingOverall = value;
    }

    
    public String getPSAverageCreditQuality() {
        return this.psAverageCreditQuality;
    }

    
    public void setPSAverageCreditQuality(final String value) {
        this.psAverageCreditQuality = value;
    }

    
    public String getTtrrRank1YrQuartile() {
        return this.ttrrRank1YrQuartile;
    }

    
    public void setTtrrRank1YrQuartile(final String ttrrRank1YrQuartile) {
        this.ttrrRank1YrQuartile = ttrrRank1YrQuartile;
    }

    
    public String getTTRReturn1Mth() {
        return this.ttrReturn1Mth;
    }

    
    public void setTTRReturn1Mth(final String value) {
        this.ttrReturn1Mth = value;
    }

    
    public String getTTRReturn3Mth() {
        return this.ttrReturn3Mth;
    }

    
    public void setTTRReturn3Mth(final String value) {
        this.ttrReturn3Mth = value;
    }

    
    public String getTTRReturn6Mth() {
        return this.ttrReturn6Mth;
    }

    
    public void setTTRReturn6Mth(final String value) {
        this.ttrReturn6Mth = value;
    }

    
    public String getTTRReturn1Yr() {
        return this.ttrReturn1Yr;
    }

    
    public void setTTRReturn1Yr(final String value) {
        this.ttrReturn1Yr = value;
    }

    
    public String getTTRReturn3Yr() {
        return this.ttrReturn3Yr;
    }

    
    public void setTTRReturn3Yr(final String value) {
        this.ttrReturn3Yr = value;
    }

    
    public String getTTRReturn5Yr() {
        return this.ttrReturn5Yr;
    }

    
    public void setTTRReturn5Yr(final String value) {
        this.ttrReturn5Yr = value;
    }

    
    public String getTTRReturn10Yr() {
        return this.ttrReturn10Yr;
    }

    
    public void setTTRReturn10Yr(final String value) {
        this.ttrReturn10Yr = value;
    }

    
    public String getTTRReturnSinceInception() {
        return this.ttrReturnSinceInception;
    }

    
    public void setTTRReturnSinceInception(final String value) {
        this.ttrReturnSinceInception = value;
    }

    
    public String getTTRReturnYTD() {
        return this.ttrReturnYTD;
    }

    
    public void setTTRReturnYTD(final String value) {
        this.ttrReturnYTD = value;
    }

    
    public String getCYRYear1() {
        return this.cyrYear1;
    }

    
    public void setCYRYear1(final String value) {
        this.cyrYear1 = value;
    }

    
    public String getCYRYear2() {
        return this.cyrYear2;
    }

    
    public void setCYRYear2(final String value) {
        this.cyrYear2 = value;
    }

    
    public String getCYRYear3() {
        return this.cyrYear3;
    }

    
    public void setCYRYear3(final String value) {
        this.cyrYear3 = value;
    }

    
    public String getCYRYear4() {
        return this.cyrYear4;
    }

    
    public void setCYRYear4(final String value) {
        this.cyrYear4 = value;
    }

    
    public String getCYRYear5() {
        return this.cyrYear5;
    }

    
    public void setCYRYear5(final String value) {
        this.cyrYear5 = value;
    }

    
    public String getRMBACBeta1Yr() {
        return this.rmbacBeta1Yr;
    }

    
    public void setRMBACBeta1Yr(final String value) {
        this.rmbacBeta1Yr = value;
    }

    
    public String getRMStdDev1Yr() {
        return this.rmStdDev1Yr;
    }

    
    public void setRMStdDev1Yr(final String value) {
        this.rmStdDev1Yr = value;
    }

    
    public String getRMBACAlpha1Yr() {
        return this.rmbacAlpha1Yr;
    }

    
    public void setRMBACAlpha1Yr(final String value) {
        this.rmbacAlpha1Yr = value;
    }

    
    public String getRMSharpeRatio1Yr() {
        return this.rmSharpeRatio1Yr;
    }

    
    public void setRMSharpeRatio1Yr(final String value) {
        this.rmSharpeRatio1Yr = value;
    }

    
    public String getRMBACRsquared1Yr() {
        return this.rmbacRsquared1Yr;
    }

    
    public void setRMBACRsquared1Yr(final String value) {
        this.rmbacRsquared1Yr = value;
    }

    
    public String getRMBACBeta3Yr() {
        return this.rmbacBeta3Yr;
    }

    
    public void setRMBACBeta3Yr(final String value) {
        this.rmbacBeta3Yr = value;
    }

    
    public String getRMStdDev3Yr() {
        return this.rmStdDev3Yr;
    }

    
    public void setRMStdDev3Yr(final String value) {
        this.rmStdDev3Yr = value;
    }

    
    public String getRMBACAlpha3Yr() {
        return this.rmbacAlpha3Yr;
    }

    
    public void setRMBACAlpha3Yr(final String value) {
        this.rmbacAlpha3Yr = value;
    }

    
    public String getRMSharpeRatio3Yr() {
        return this.rmSharpeRatio3Yr;
    }

    
    public void setRMSharpeRatio3Yr(final String value) {
        this.rmSharpeRatio3Yr = value;
    }

    
    public String getRMBACRsquared3Yr() {
        return this.rmbacRsquared3Yr;
    }

    
    public void setRMBACRsquared3Yr(final String value) {
        this.rmbacRsquared3Yr = value;
    }

    
    public String getRMBACBeta5Yr() {
        return this.rmbacBeta5Yr;
    }

    
    public void setRMBACBeta5Yr(final String value) {
        this.rmbacBeta5Yr = value;
    }

    
    public String getRMStdDev5Yr() {
        return this.rmStdDev5Yr;
    }

    
    public void setRMStdDev5Yr(final String value) {
        this.rmStdDev5Yr = value;
    }

    
    public String getRMBACAlpha5Yr() {
        return this.rmbacAlpha5Yr;
    }

    
    public void setRMBACAlpha5Yr(final String value) {
        this.rmbacAlpha5Yr = value;
    }

    
    public String getRMSharpeRatio5Yr() {
        return this.rmSharpeRatio5Yr;
    }

    
    public void setRMSharpeRatio5Yr(final String value) {
        this.rmSharpeRatio5Yr = value;
    }

    
    public String getRMBACRsquared5Yr() {
        return this.rmbacRsquared5Yr;
    }

    
    public void setRMBACRsquared5Yr(final String value) {
        this.rmbacRsquared5Yr = value;
    }

    
    public String getRMBACBeta10Yr() {
        return this.rmbacBeta10Yr;
    }

    
    public void setRMBACBeta10Yr(final String value) {
        this.rmbacBeta10Yr = value;
    }

    
    public String getRMStdDev10Yr() {
        return this.rmStdDev10Yr;
    }

    
    public void setRMStdDev10Yr(final String value) {
        this.rmStdDev10Yr = value;
    }

    
    public String getRMBACAlpha10Yr() {
        return this.rmbacAlpha10Yr;
    }

    
    public void setRMBACAlpha10Yr(final String value) {
        this.rmbacAlpha10Yr = value;
    }

    
    public String getRMSharpeRatio10Yr() {
        return this.rmSharpeRatio10Yr;
    }

    
    public void setRMSharpeRatio10Yr(final String value) {
        this.rmSharpeRatio10Yr = value;
    }

    
    public String getRMBACRsquared10Yr() {
        return this.rmbacRsquared10Yr;
    }

    
    public void setRMBACRsquared10Yr(final String value) {
        this.rmbacRsquared10Yr = value;
    }

    
    public String getPIMinimumInitial() {
        return this.piMinimumInitial;
    }

    
    public void setPIMinimumInitial(final String value) {
        this.piMinimumInitial = value;
    }

    
    public String getPIMinimumSubsequent() {
        return this.piMinimumSubsequent;
    }

    
    public void setPIMinimumSubsequent(final String value) {
        this.piMinimumSubsequent = value;
    }

    
    public String getPIMinimumIRA() {
        return this.piMinimumIRA;
    }

    
    public void setPIMinimumIRA(final String value) {
        this.piMinimumIRA = value;
    }

    
    public String getPiPurchaseCurrencyId() {
        return this.piPurchaseCurrencyId;
    }

    
    public void setPiPurchaseCurrencyId(final String piPurchaseCurrencyId) {
        this.piPurchaseCurrencyId = piPurchaseCurrencyId;
    }

    
    public String getATRRSP() {
        return this.atrrsp;
    }

    
    public void setATRRSP(final String value) {
        this.atrrsp = value;
    }

    
    public String getFscbiShareClassType() {
        return this.fscbiShareClassType;
    }

    
    public void setFscbiShareClassType(final String fscbiShareClassType) {
        this.fscbiShareClassType = fscbiShareClassType;
    }

    
    public String getId() {
        return this.id;
    }

    
    public void setId(final String value) {
        this.id = value;
    }

    
    public String getFnaAsOfOriginalReported() {
        return this.fnaAsOfOriginalReported;
    }

    
    public void setFnaAsOfOriginalReported(final String fnaAsOfOriginalReported) {
        this.fnaAsOfOriginalReported = fnaAsOfOriginalReported;
    }

    
    public String getDpDayEndDate() {
        return this.dpDayEndDate;
    }

    
    public void setDpDayEndDate(final String dpDayEndDate) {
        this.dpDayEndDate = dpDayEndDate;
    }


}
