//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.11.01 at 02:10:10 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.fundcompare;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"fundServ"})
@XmlRootElement(name = "FSCBI-FundServs")
public class FSCBIFundServs {

    @XmlElement(name = "FundServ", required = true)
    protected List<String> fundServ;

    
    public List<String> getFundServ() {
        if (this.fundServ == null) {
            this.fundServ = new ArrayList<String>();
        }
        return this.fundServ;
    }

}
