query productByFilter ($filter: JSON!) {
  productByFilter(filter: $filter, limit: 0) {
    prodId
    ctryRecCde
    grpMembrRecCde
    prodAltPrimNum
    prodTypeCde
    prodStatCde
    allowBuyProdInd
    altId {
      prodAltNum
      prodCdeAltClassCde
      prodTypeCde
    }
  }
}
