//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.05 at 05:27:33 PM CST 
//


package com.dummy.wpb.product.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tableObject", propOrder = {
    "columnDefinition",
    "rowData",
    "tableName"
})
public class TableObject {

    @XmlElement(nillable = true)
    protected List<ColumnDefinition> columnDefinition;
    @XmlElement(nillable = true)
    protected List<RowData> rowData;
    protected String tableName;

    public TableObject(List<ColumnDefinition> columnDefinition, List<RowData> rowData, String tableName) {
        this.columnDefinition = columnDefinition;
        this.rowData = rowData;
        this.tableName = tableName;
    }

    public TableObject() {
    }

    /**
     * Gets the value of the columnDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columnDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumnDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColumnDefinition }
     * 
     * 
     */
    public List<ColumnDefinition> getColumnDefinition() {
        if (columnDefinition == null) {
            columnDefinition = new ArrayList<>();
        }
        return this.columnDefinition;
    }

    /**
     * Gets the value of the rowData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rowData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRowData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RowData }
     * 
     * 
     */
    public List<RowData> getRowData() {
        if (rowData == null) {
            rowData = new ArrayList<>();
        }
        return this.rowData;
    }

    /**
     * Gets the value of the tableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * Sets the value of the tableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableName(String value) {
        this.tableName = value;
    }

}
