//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.05 at 05:27:33 PM CST 
//


package com.dummy.wpb.product.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for wpcDataEnquiryJsonResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wpcDataEnquiryJsonResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="snapshotTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="tableObjectJson" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wpcDataEnquiryJsonResponse", propOrder = {
    "snapshotTimestamp",
    "tableObjectJson"
})
public class WpcDataEnquiryJsonResponse {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar snapshotTimestamp;
    protected String tableObjectJson;

    /**
     * Gets the value of the snapshotTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSnapshotTimestamp() {
        return snapshotTimestamp;
    }

    /**
     * Sets the value of the snapshotTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSnapshotTimestamp(XMLGregorianCalendar value) {
        this.snapshotTimestamp = value;
    }

    /**
     * Gets the value of the tableObjectJson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableObjectJson() {
        return tableObjectJson;
    }

    /**
     * Sets the value of the tableObjectJson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableObjectJson(String value) {
        this.tableObjectJson = value;
    }

}
