//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.05 at 05:27:33 PM CST 
//


package com.dummy.wpb.product.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for wpcDataEnquiryResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wpcDataEnquiryResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="snapshotTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="tableObject" type="{http://impl.service.webservice.wpc.wmd.dummy.com/}tableObject" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wpcDataEnquiryResponse", propOrder = {
    "snapshotTimestamp",
    "tableObject"
})
public class WpcDataEnquiryResponse {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar snapshotTimestamp;
    @XmlElement(nillable = true)
    protected List<TableObject> tableObject;

    /**
     * Gets the value of the snapshotTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSnapshotTimestamp() {
        return snapshotTimestamp;
    }

    /**
     * Sets the value of the snapshotTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSnapshotTimestamp(XMLGregorianCalendar value) {
        this.snapshotTimestamp = value;
    }

    /**
     * Gets the value of the tableObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tableObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTableObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TableObject }
     * 
     * 
     */
    public List<TableObject> getTableObject() {
        if (tableObject == null) {
            tableObject = new ArrayList<TableObject>();
        }
        return this.tableObject;
    }

}
