//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.05 at 06:54:18 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.accesscode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"count"})
@XmlRootElement(name = "meta")
public class Meta {

    @XmlElement(required = true)
    protected Integer count;


    public Integer getCount() {
        return this.count;
    }


    public void setCount(final Integer value) {
        this.count = value;
    }

}
