//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.15 at 11:32:25 AM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.accesscode;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.hhhh.group.secwealth.mktdata.fund.beans.mstar.ResponseData;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "response")
public class MStarIDSearchData extends ResponseData {

    @XmlElement(required = true)
    protected Meta meta;

    @XmlElement(required = true)
    protected List<Data> data;


    public Meta getMeta() {
        return this.meta;
    }


    public void setMeta(final Meta value) {
        this.meta = value;
    }


    public List<Data> getData() {
        return this.data;
    }


    public void setData(final List<Data> data) {
        this.data = data;
    }

}
