//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.22 at 05:22:32 PM CST 
//


package com.dummy.wpb.product.model;


import lombok.Data;

/**
 * <p>Java class for productKey complex type.
 * 
 */
@Data
public class ProductKey {

    protected String ccyProdCde;
    protected String prodAltNum;
    protected String prodCdeAltClassCde;
    protected String ctryProdTradeCde;
    protected String prodTypeCde;

}
