package com.hhhh.group.secwealth.mktdata.common.dao.pojo;
import java.math.BigDecimal;
import java.util.Date;
import java.sql.Timestamp;
import com.hhhh.group.secwealth.mktdata.common.dao.pojo.UtProdInstmId;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.Silent.class)
public class UtProdInstmTest {
    @Test
    public void test(){
        UtProdInstm utProdInstm = new UtProdInstm();
        utProdInstm.setFundName("");
        utProdInstm.setCurrencyId("");
        utProdInstm.setUtProdInstmId(new UtProdInstmId());
        utProdInstm.setMarket("");
        utProdInstm.setProductType("");
        utProdInstm.setProductSubTypeCode("");
        utProdInstm.setSymbol("");
        utProdInstm.setPerformanceId("");
        utProdInstm.setFundserviceId("");
        utProdInstm.setProdName("");
        utProdInstm.setProdPllName("");
        utProdInstm.setProdSllName("");
        utProdInstm.setFamilyCode("");
        utProdInstm.setCcyProdTradeCde("");
        utProdInstm.setFundRtainMinAmt(new BigDecimal("0"));
        utProdInstm.setFundSwInMinAmt(new BigDecimal("0"));
        utProdInstm.setAllowSellMipProdInd("");
        utProdInstm.setAllowReguCntbInd("");
        utProdInstm.setCurrency("");
        utProdInstm.setRiskLvlCde("");
        utProdInstm.setInvstIncrmMinAmt(new BigDecimal("0"));
        utProdInstm.setClassType("");
        utProdInstm.setDayEndNAV(new BigDecimal("0"));
        utProdInstm.setChangeAmountNAV(new BigDecimal("0"));
        utProdInstm.setAssetsUnderManagement(new BigDecimal("0"));
        utProdInstm.setTotalNetAsset(0L);
        utProdInstm.setRatingOverall(0);
        utProdInstm.setMer(new BigDecimal("0"));
        utProdInstm.setYield1Yr(new BigDecimal("0"));
        utProdInstm.setInceptionDate(new Date());
        utProdInstm.setTurnoverRatio(new BigDecimal("0"));
        utProdInstm.setStdDev3Yr(new BigDecimal("0"));
        utProdInstm.setEquityStyle(0);
        utProdInstm.setFixIncomestyle(0);
        utProdInstm.setTaxAdjustedRating(0);
        utProdInstm.setAverageCreditQuality(0);
        utProdInstm.setRank1Yr(new BigDecimal("0"));
        utProdInstm.setReturnSinceInception(new BigDecimal("0"));
        utProdInstm.setReturnYTD(new BigDecimal("0"));
        utProdInstm.setYear1(new BigDecimal("0"));
        utProdInstm.setYear2(new BigDecimal("0"));
        utProdInstm.setYear3(new BigDecimal("0"));
        utProdInstm.setYear4(new BigDecimal("0"));
        utProdInstm.setYear5(new BigDecimal("0"));
        utProdInstm.setBeta1(new BigDecimal("0"));
        utProdInstm.setStdDev1(new BigDecimal("0"));
        utProdInstm.setAlpha1(new BigDecimal("0"));
        utProdInstm.setSharpeRatio1(new BigDecimal("0"));
        utProdInstm.setrSquared1(new BigDecimal("0"));
        utProdInstm.setBeta3(new BigDecimal("0"));
        utProdInstm.setAlpha3(new BigDecimal("0"));
        utProdInstm.setSharpeRatio3(new BigDecimal("0"));
        utProdInstm.setrSquared3(new BigDecimal("0"));
        utProdInstm.setBeta5(new BigDecimal("0"));
        utProdInstm.setStdDev5(new BigDecimal("0"));
        utProdInstm.setAlpha5(new BigDecimal("0"));
        utProdInstm.setSharpeRatio5(new BigDecimal("0"));
        utProdInstm.setrSquared5(new BigDecimal("0"));
        utProdInstm.setBeta10(new BigDecimal("0"));
        utProdInstm.setStdDev10(new BigDecimal("0"));
        utProdInstm.setAlpha10(new BigDecimal("0"));
        utProdInstm.setSharpeRatio10(new BigDecimal("0"));
        utProdInstm.setrSquared10(new BigDecimal("0"));
        utProdInstm.setRrspEligibility("");
        utProdInstm.setUpdatedBy("");
        utProdInstm.setUpdatedOn(new Timestamp(new java.util.Date().getTime()));
        utProdInstm.setMinInitInvst(new BigDecimal("0"));
        utProdInstm.setMinSubqInvst(new BigDecimal("0"));
        utProdInstm.setAsOfDate(new Date());
        utProdInstm.setFamilyName1("");
        utProdInstm.setFamilyName2("");
        utProdInstm.setFamilyName3("");
        utProdInstm.setCategoryCode("");
        utProdInstm.setCategoryName1("");
        utProdInstm.setCategoryName2("");
        utProdInstm.setCategoryName3("");
        utProdInstm.setCategoryLevel1Code("");
        utProdInstm.setCategoryLevel1SequencenNum(0);
        utProdInstm.setCategoryLevel1Name1("");
        utProdInstm.setCategoryLevel1Name2("");
        utProdInstm.setCategoryLevel1Name3("");
        utProdInstm.setMean5Yr(new BigDecimal("0"));
        utProdInstm.setTrackingError1Yr(0.0F);
        utProdInstm.setRisk3Yr("");
        utProdInstm.setMarketPriceChange(0.0F);
        utProdInstm.setDistributionFrequency("");
        utProdInstm.setRank3Yr(new BigDecimal("0"));
        utProdInstm.setRank5Yr(new BigDecimal("0"));
        utProdInstm.setRank10Yr(new BigDecimal("0"));
        utProdInstm.setMinimumIRA(0L);
        utProdInstm.setReturn1day(new BigDecimal("0"));
        utProdInstm.setReturn1mth(new BigDecimal("0"));
        utProdInstm.setReturn3mth(new BigDecimal("0"));
        utProdInstm.setReturn6mth(new BigDecimal("0"));
        utProdInstm.setReturn1yr(new BigDecimal("0"));
        utProdInstm.setReturn3yr(new BigDecimal("0"));
        utProdInstm.setReturn5yr(new BigDecimal("0"));
        utProdInstm.setReturn10yr(new BigDecimal("0"));
        utProdInstm.sethhhhMinInitInvst(new BigDecimal("0"));
        utProdInstm.sethhhhMinSubqInvst(new BigDecimal("0"));
        utProdInstm.setPurchaseCcy("");
        utProdInstm.setProductShortPrimaryLanguageName("");
        utProdInstm.setProductShortSecondLanguageName("");
        utProdInstm.setProductShortName("");
        utProdInstm.setCcyAsofRep("");
        utProdInstm.setAnnualReportOngoingCharge(new BigDecimal("0"));
        utProdInstm.setActualManagementFee(new BigDecimal("0"));
        utProdInstm.setAllowSwOutProdInd("");
        utProdInstm.setAllowSwInProdInd("");
        utProdInstm.setAllowTradeProdInd("");
        utProdInstm.setProdTaxFreeWrapActStaCde("");
        utProdInstm.setRatingDate(new Date());
        utProdInstm.setMonthEndDate(new Date());
        utProdInstm.setEndDateYearRisk(new Date());
        utProdInstm.setEndDateRiskLvlCde(new Date());
        utProdInstm.setFamilySequencenNum(0);
        utProdInstm.setCategorySequencenNum(0);
        utProdInstm.setAverageCreditQualityNum(0);
        utProdInstm.setDistributionFrequencyNum(0);
        utProdInstm.setExpenseRatio(new BigDecimal("0"));
        utProdInstm.setLoanProdOdMrgnPct(new BigDecimal("0"));
        utProdInstm.setChrgInitSalesPct(new BigDecimal("0"));
        utProdInstm.setAnnMgmtFeePct(new BigDecimal("0"));
        utProdInstm.setPriShareClassInd(new Character('1'));
        utProdInstm.setTopPerformersInd(new Character('2'));
        utProdInstm.setFundId("");
        utProdInstm.setAverageCreditQualityName("");
        utProdInstm.setClosingPrcCcy("");
        utProdInstm.setCreditQualityBreakdownAsOfDate(new Date());
        utProdInstm.setCcyInvstCde("");
        utProdInstm.setYieldToMaturity(new BigDecimal("0"));
        utProdInstm.setEffectiveDuration(new BigDecimal("0"));
        utProdInstm.setCurrentYield(new BigDecimal("0"));
        utProdInstm.setReturn1mthDaily(new BigDecimal("0"));
        utProdInstm.setReturn3mthDaily(new BigDecimal("0"));
        utProdInstm.setReturn6mthDaily(new BigDecimal("0"));
        utProdInstm.setReturnytdDaily(new BigDecimal("0"));
        utProdInstm.setReturn1yrDaily(new BigDecimal("0"));
        utProdInstm.setReturn3yrDaily(new BigDecimal("0"));
        utProdInstm.setReturn5yrDaily(new BigDecimal("0"));
        utProdInstm.setReturn10yrDaily(new BigDecimal("0"));
        utProdInstm.setReturnSinceInceptionDaily(new BigDecimal("0"));
        utProdInstm.setProdTopSellRankNum(new BigDecimal("0"));
        utProdInstm.setTopSellProdIndex("");
        utProdInstm.setProdLaunchDate(new Date());
        utProdInstm.setInvestmentRegionCode("");
        utProdInstm.setInvestmentRegionName1("");
        utProdInstm.setInvestmentRegionName2("");
        utProdInstm.setInvestmentRegionName3("");
        utProdInstm.setInvestmentRegionSequencenNum(0);
        utProdInstm.setListProdCode("");
        utProdInstm.setListProdType("");
        utProdInstm.setNumberOfBondHoldings(new BigDecimal("0"));
        utProdInstm.setNumberOfStockHoldings(new BigDecimal("0"));
        utProdInstm.setHoldingAllocationPortfolioDate(new Date());
        utProdInstm.setKiidOngoingCharge(new BigDecimal("0"));
        utProdInstm.setKiidOngoingChargeDate(new Date());
        utProdInstm.setFundShreClsName("");
        utProdInstm.setFundShreClsNamePriLang("");
        utProdInstm.setFundShreClsNameSecLang("");
        utProdInstm.setFundClassCde("");
        utProdInstm.setAmcmAuthorizeIndicator("");
        utProdInstm.setNextDealDate(new Date());
        utProdInstm.setIndexId("");
        utProdInstm.setIndexName("");
        utProdInstm.setSurveyedFundNetAssetsDate(new Date());
        utProdInstm.setWeekRangeLowDate(new Date());
        utProdInstm.setWeekRangeHighDate(new Date());
        utProdInstm.setRiskFreeRateName("");
        utProdInstm.setRelativeRiskMeasuresIndexName("");
        utProdInstm.setProdStatCde("");
        utProdInstm.setAllowBuyProdInd("");
        utProdInstm.setAllowSellProdInd("");
        utProdInstm.setAnnualReportDate(new Date());
        utProdInstm.setMarketPrice(new BigDecimal("0"));

        utProdInstm.getFundName();
        utProdInstm.getCurrencyId();
        utProdInstm.getUtProdInstmId();
        utProdInstm.getMarket();
        utProdInstm.getProductType();
        utProdInstm.getProductSubTypeCode();
        utProdInstm.getSymbol();
        utProdInstm.getPerformanceId();
        utProdInstm.getFundserviceId();
        utProdInstm.getProdName();
        utProdInstm.getProdPllName();
        utProdInstm.getProdSllName();
        utProdInstm.getFamilyCode();
        utProdInstm.getCcyProdTradeCde();
        utProdInstm.getFundRtainMinAmt();
        utProdInstm.getFundSwInMinAmt();
        utProdInstm.getAllowSellMipProdInd();
        utProdInstm.getAllowReguCntbInd();
        utProdInstm.getCurrency();
        utProdInstm.getRiskLvlCde();
        utProdInstm.getInvstIncrmMinAmt();
        utProdInstm.getClassType();
        utProdInstm.getDayEndNAV();
        utProdInstm.getChangeAmountNAV();
        utProdInstm.getAssetsUnderManagement();
        utProdInstm.getTotalNetAsset();
        utProdInstm.getRatingOverall();
        utProdInstm.getMer();
        utProdInstm.getYield1Yr();
        utProdInstm.getInceptionDate();
        utProdInstm.getTurnoverRatio();
        utProdInstm.getStdDev3Yr();
        utProdInstm.getEquityStyle();
        utProdInstm.getFixIncomestyle();
        utProdInstm.getTaxAdjustedRating();
        utProdInstm.getAverageCreditQuality();
        utProdInstm.getRank1Yr();
        utProdInstm.getReturnSinceInception();
        utProdInstm.getReturnYTD();
        utProdInstm.getYear1();
        utProdInstm.getYear2();
        utProdInstm.getYear3();
        utProdInstm.getYear4();
        utProdInstm.getYear5();
        utProdInstm.getBeta1();
        utProdInstm.getStdDev1();
        utProdInstm.getAlpha1();
        utProdInstm.getSharpeRatio1();
        utProdInstm.getrSquared1();
        utProdInstm.getBeta3();
        utProdInstm.getAlpha3();
        utProdInstm.getSharpeRatio3();
        utProdInstm.getrSquared3();
        utProdInstm.getBeta5();
        utProdInstm.getStdDev5();
        utProdInstm.getAlpha5();
        utProdInstm.getSharpeRatio5();
        utProdInstm.getrSquared5();
        utProdInstm.getBeta10();
        utProdInstm.getStdDev10();
        utProdInstm.getAlpha10();
        utProdInstm.getSharpeRatio10();
        utProdInstm.getrSquared10();
        utProdInstm.getRrspEligibility();
        utProdInstm.getUpdatedBy();
        utProdInstm.getUpdatedOn();
        utProdInstm.getMinInitInvst();
        utProdInstm.getMinSubqInvst();
        utProdInstm.getAsOfDate();
        utProdInstm.getFamilyName1();
        utProdInstm.getFamilyName2();
        utProdInstm.getFamilyName3();
        utProdInstm.getCategoryCode();
        utProdInstm.getCategoryName1();
        utProdInstm.getCategoryName2();
        utProdInstm.getCategoryName3();
        utProdInstm.getCategoryLevel1Code();
        utProdInstm.getCategoryLevel1SequencenNum();
        utProdInstm.getCategoryLevel1Name1();
        utProdInstm.getCategoryLevel1Name2();
        utProdInstm.getCategoryLevel1Name3();
        utProdInstm.getMean5Yr();
        utProdInstm.getTrackingError1Yr();
        utProdInstm.getRisk3Yr();
        utProdInstm.getMarketPriceChange();
        utProdInstm.getDistributionFrequency();
        utProdInstm.getRank3Yr();
        utProdInstm.getRank5Yr();
        utProdInstm.getRank10Yr();
        utProdInstm.getMinimumIRA();
        utProdInstm.getReturn1day();
        utProdInstm.getReturn1mth();
        utProdInstm.getReturn3mth();
        utProdInstm.getReturn6mth();
        utProdInstm.getReturn1yr();
        utProdInstm.getReturn3yr();
        utProdInstm.getReturn5yr();
        utProdInstm.getReturn10yr();
        utProdInstm.gethhhhMinInitInvst();
        utProdInstm.gethhhhMinSubqInvst();
        utProdInstm.getPurchaseCcy();
        utProdInstm.getProductShortPrimaryLanguageName();
        utProdInstm.getProductShortSecondLanguageName();
        utProdInstm.getProductShortName();
        utProdInstm.getCcyAsofRep();
        utProdInstm.getAnnualReportOngoingCharge();
        utProdInstm.getActualManagementFee();
        utProdInstm.getAllowSwOutProdInd();
        utProdInstm.getAllowSwInProdInd();
        utProdInstm.getAllowTradeProdInd();
        utProdInstm.getProdTaxFreeWrapActStaCde();
        utProdInstm.getRatingDate();
        utProdInstm.getMonthEndDate();
        utProdInstm.getEndDateYearRisk();
        utProdInstm.getEndDateRiskLvlCde();
        utProdInstm.getFamilySequencenNum();
        utProdInstm.getCategorySequencenNum();
        utProdInstm.getAverageCreditQualityNum();
        utProdInstm.getDistributionFrequencyNum();
        utProdInstm.getExpenseRatio();
        utProdInstm.getLoanProdOdMrgnPct();
        utProdInstm.getChrgInitSalesPct();
        utProdInstm.getAnnMgmtFeePct();
        utProdInstm.getPriShareClassInd();
        utProdInstm.getTopPerformersInd();
        utProdInstm.getFundId();
        utProdInstm.getAverageCreditQualityName();
        utProdInstm.getClosingPrcCcy();
        utProdInstm.getCreditQualityBreakdownAsOfDate();
        utProdInstm.getCcyInvstCde();
        utProdInstm.getYieldToMaturity();
        utProdInstm.getEffectiveDuration();
        utProdInstm.getCurrentYield();
        utProdInstm.getReturn1mthDaily();
        utProdInstm.getReturn3mthDaily();
        utProdInstm.getReturn6mthDaily();
        utProdInstm.getReturnytdDaily();
        utProdInstm.getReturn1yrDaily();
        Assert.assertTrue(true);
    }
}
