//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.05 at 09:48:11 AM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.trailingreturnschart;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"r"})
@XmlRootElement(name = "api")
public class Api {

    @XmlElement(required = true)
    protected List<R> r;
    @XmlAttribute(name = "_name")
    protected String name;

    
    public List<R> getR() {
        if (this.r == null) {
            this.r = new ArrayList<R>();
        }
        return this.r;
    }

    
    public String getName() {
        return this.name;
    }

    
    public void setName(final String value) {
        this.name = value;
    }

}
