//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.05 at 09:48:11 AM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.trailingreturnschart;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "r")
public class R {

    @XmlAttribute(name = "d")
    protected String d;
    @XmlAttribute(name = "v")
    protected String v;


    public String getD() {
        return this.d;
    }


    public void setD(final String value) {
        this.d = value;
    }


    public String getV() {
        return this.v;
    }


    public void setV(final String value) {
        this.v = value;
    }

}
