//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.05 at 06:54:18 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"code", "message"})
@XmlRootElement(name = "status")
public class Status {

    @XmlAttribute(name = "code")
    protected String errorCode;
    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String message;


    public String getErrorCode() {
        return this.errorCode;
    }


    public void setErrorCode(final String errorCode) {
        this.errorCode = errorCode;
    }


    public String getCode() {
        return this.code;
    }


    public void setCode(final String value) {
        this.code = value;
    }


    public String getMessage() {
        return this.message;
    }


    public void setMessage(final String value) {
        this.message = value;
    }

}
