spring:
  datasource:
    url: jdbc:postgresql://amh-dev-wppostgresql01.wealth-platform-amh.dev.aws.cloud.dummy:5432/productdb
    username: ocushkd_appuser
    password:
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always