mutation productPriceBatchUpdate($updateParams: [ProductBatchUpdateByIdInput]!, $priceHistory: [ProductPriceHistoryInput!]!) {
    productBatchUpdateById(updateParams: $updateParams) {
        matchCount
        matchProducts {
            ctryRecCde
            grpMembrRecCde
            prodId
            prodType
            prodTypeCde
            prodSubtpCde
            prodCde
            prodAltPrimNum
            prodName
        }
        updatedProducts {
            ctryRecCde
            grpMembrRecCde
            prodId
            prodType
            prodTypeCde
            prodSubtpCde
            prodCde
            prodAltPrimNum
            prodName
        }
        invalidProducts {
            product {
                ctryRecCde
                grpMembrRecCde
                prodId
                prodType
                prodTypeCde
                prodSubtpCde
                prodCde
                prodAltPrimNum
                prodName
            }
            errors {
                jsonPath
                code
                message
            }
        }
    }
    productPriceHistoryBatchImport(priceHistory: $priceHistory) {
        invalidPriceHistories {
            priceHistory {
                prodId
                pdcyPrcCde
                prcEffDt
                prcInpDt
                ccyProdMktPrcCde
                prodBidPrcAmt
                prodOffrPrcAmt
                prodMktPrcAmt
                prodNavPrcAmt
                recCreatDtTm
                recUpdtDtTm
            }
            errors {
                message
            }
        }
        importedPriceHistories {
            prodId
            pdcyPrcCde
            prcEffDt
            prcInpDt
            ccyProdMktPrcCde
            prodBidPrcAmt
            prodOffrPrcAmt
            prodMktPrcAmt
            prodNavPrcAmt
            recCreatDtTm
            recUpdtDtTm
        }
    }
}
