//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.16 at 03:19:37 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.dayenddate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"dpDayEndDate"})
@XmlRootElement(name = "api")
public class Api {

    @XmlElement(name = "DP-DayEndDate", required = true)
    protected String dpDayEndDate;
    @XmlAttribute(name = "_id")
    protected String id;

    
    public String getDPDayEndDate() {
        return this.dpDayEndDate;
    }

    
    public void setDPDayEndDate(final String value) {
        this.dpDayEndDate = value;
    }

    
    public String getId() {
        return this.id;
    }

    
    public void setId(final String value) {
        this.id = value;
    }

}
