//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.16 at 03:19:37 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.dayenddate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.hhhh.group.secwealth.mktdata.fund.beans.mstar.ResponseData;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"data"})
@XmlRootElement(name = "response")
public class DayEndDateData extends ResponseData {

    @XmlElement(required = true)
    protected Data data;


    public Data getData() {
        return this.data;
    }


    public void setData(final Data value) {
        this.data = value;
    }

}
