//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.18 at 04:18:27 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.quoteperformance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"ttrReturn1Mth", "ttrCategoryReturn1Mth", "ttrrRank1MthQuartile", "ttrrCategorySize1Mth",
    "ttrReturn3Mth", "ttrCategoryReturn3Mth", "ttrrRank3MthQuartile", "ttrrCategorySize3Mth", "ttrReturn6Mth",
    "ttrCategoryReturn6Mth", "ttrrRank6MthQuartile", "ttrrCategorySize6Mth", "ttrReturn1Yr", "ttrCategoryReturn1Yr",
    "ttrrRank1YrQuartile", "ttrrCategorySize1Yr", "ttrReturn3Yr", "ttrCategoryReturn3Yr", "ttrrRank3YrQuartile",
    "ttrrCategorySize3Yr", "ttrReturn5Yr", "ttrCategoryReturn5Yr", "ttrrRank5YrQuartile", "ttrrCategorySize5Yr",
    "ttrrMonthEndDate", "mrRisk3Year", "mrReturn3Year", "mrRatingDate", "rmbacBeta1Yr", "rmStdDev1Yr", "rmbacAlpha1Yr",
    "rmSharpeRatio1Yr", "rmbacRsquared1Yr", "rmbacBeta3Yr", "rmStdDev3Yr", "rmbacAlpha3Yr", "rmSharpeRatio3Yr", "rmbacRsquared3Yr",
    "rmbacBeta5Yr", "rmStdDev5Yr", "rmbacAlpha5Yr", "rmSharpeRatio5Yr", "rmbacRsquared5Yr", "rmbacBeta10Yr", "rmStdDev10Yr",
    "rmbacAlpha10Yr", "rmSharpeRatio10Yr", "rmbacRsquared10Yr", "rmbacCategoryBeta1Yr", "rmCategoryStdDev1Yr",
    "rmbacCategoryAlpha1Yr", "rmCategorySharpeRatio1Yr", "rmbacCategoryRsquared1Yr", "rmbacCategoryBeta3Yr", "rmCategoryStdDev3Yr",
    "rmbacCategoryAlpha3Yr", "rmCategorySharpeRatio3Yr", "rmbacCategoryRsquared3Yr", "rmbacCategoryBeta5Yr", "rmCategoryStdDev5Yr",
    "rmbacCategoryAlpha5Yr", "rmCategorySharpeRatio5Yr", "rmbacCategoryRsquared5Yr", "rmbacCategoryBeta10Yr",
    "rmCategoryStdDev10Yr", "rmbacCategoryAlpha10Yr", "rmCategorySharpeRatio10Yr", "rmbacCategoryRsquared10Yr", "rmEndDate",
    "ttrrRank1MthQuartileBreakpoint1", "ttrrRank1MthQuartileBreakpoint25", "ttrrRank1MthQuartileBreakpoint50",
    "ttrrRank1MthQuartileBreakpoint75", "ttrrRank1MthQuartileBreakpoint99", "ttrrRank3MthQuartileBreakpoint1",
    "ttrrRank3MthQuartileBreakpoint25", "ttrrRank3MthQuartileBreakpoint50", "ttrrRank3MthQuartileBreakpoint75",
    "ttrrRank3MthQuartileBreakpoint99", "ttrrRank6MthQuartileBreakpoint1", "ttrrRank6MthQuartileBreakpoint25",
    "ttrrRank6MthQuartileBreakpoint50", "ttrrRank6MthQuartileBreakpoint75", "ttrrRank6MthQuartileBreakpoint99",
    "ttrrRank1YrQuartileBreakpoint1", "ttrrRank1YrQuartileBreakpoint25", "ttrrRank1YrQuartileBreakpoint50",
    "ttrrRank1YrQuartileBreakpoint75", "ttrrRank1YrQuartileBreakpoint99", "ttrrRank3YrQuartileBreakpoint1",
    "ttrrRank3YrQuartileBreakpoint25", "ttrrRank3YrQuartileBreakpoint50", "ttrrRank3YrQuartileBreakpoint75",
    "ttrrRank3YrQuartileBreakpoint99", "ttrrRank5YrQuartileBreakpoint1", "ttrrRank5YrQuartileBreakpoint25",
    "ttrrRank5YrQuartileBreakpoint50", "ttrrRank5YrQuartileBreakpoint75", "ttrrRank5YrQuartileBreakpoint99"})
@XmlRootElement(name = "api")
public class Api {

    @XmlElement(name = "TTR-Return1Mth", required = true)
    protected String ttrReturn1Mth;
    @XmlElement(name = "TTR-CategoryReturn1Mth", required = true)
    protected String ttrCategoryReturn1Mth;
    @XmlElement(name = "TTRR-Rank1MthQuartile", required = true)
    protected String ttrrRank1MthQuartile;
    @XmlElement(name = "TTRR-CategorySize1Mth", required = true)
    protected String ttrrCategorySize1Mth;
    @XmlElement(name = "TTR-Return3Mth", required = true)
    protected String ttrReturn3Mth;
    @XmlElement(name = "TTR-CategoryReturn3Mth", required = true)
    protected String ttrCategoryReturn3Mth;
    @XmlElement(name = "TTRR-Rank3MthQuartile", required = true)
    protected String ttrrRank3MthQuartile;
    @XmlElement(name = "TTRR-CategorySize3Mth", required = true)
    protected String ttrrCategorySize3Mth;
    @XmlElement(name = "TTR-Return6Mth", required = true)
    protected String ttrReturn6Mth;
    @XmlElement(name = "TTR-CategoryReturn6Mth", required = true)
    protected String ttrCategoryReturn6Mth;
    @XmlElement(name = "TTRR-Rank6MthQuartile", required = true)
    protected String ttrrRank6MthQuartile;
    @XmlElement(name = "TTRR-CategorySize6Mth", required = true)
    protected String ttrrCategorySize6Mth;
    @XmlElement(name = "TTR-Return1Yr", required = true)
    protected String ttrReturn1Yr;
    @XmlElement(name = "TTR-CategoryReturn1Yr", required = true)
    protected String ttrCategoryReturn1Yr;
    @XmlElement(name = "TTRR-Rank1YrQuartile", required = true)
    protected String ttrrRank1YrQuartile;
    @XmlElement(name = "TTRR-CategorySize1Yr", required = true)
    protected String ttrrCategorySize1Yr;
    @XmlElement(name = "TTR-Return3Yr", required = true)
    protected String ttrReturn3Yr;
    @XmlElement(name = "TTR-CategoryReturn3Yr", required = true)
    protected String ttrCategoryReturn3Yr;
    @XmlElement(name = "TTRR-Rank3YrQuartile", required = true)
    protected String ttrrRank3YrQuartile;
    @XmlElement(name = "TTRR-CategorySize3Yr", required = true)
    protected String ttrrCategorySize3Yr;
    @XmlElement(name = "TTR-Return5Yr", required = true)
    protected String ttrReturn5Yr;
    @XmlElement(name = "TTR-CategoryReturn5Yr", required = true)
    protected String ttrCategoryReturn5Yr;
    @XmlElement(name = "TTRR-Rank5YrQuartile", required = true)
    protected String ttrrRank5YrQuartile;
    @XmlElement(name = "TTRR-CategorySize5Yr", required = true)
    protected String ttrrCategorySize5Yr;
    @XmlElement(name = "TTRR-MonthEndDate", required = true)
    protected String ttrrMonthEndDate;
    @XmlElement(name = "MR-Risk3Year", required = true)
    protected String mrRisk3Year;
    @XmlElement(name = "MR-Return3Year", required = true)
    protected String mrReturn3Year;
    @XmlElement(name = "MR-RatingDate", required = true)
    protected String mrRatingDate;
    @XmlElement(name = "RMBAC-Beta1Yr", required = true)
    protected String rmbacBeta1Yr;
    @XmlElement(name = "RM-StdDev1Yr", required = true)
    protected String rmStdDev1Yr;
    @XmlElement(name = "RMBAC-Alpha1Yr", required = true)
    protected String rmbacAlpha1Yr;
    @XmlElement(name = "RM-SharpeRatio1Yr", required = true)
    protected String rmSharpeRatio1Yr;
    @XmlElement(name = "RMBAC-Rsquared1Yr", required = true)
    protected String rmbacRsquared1Yr;
    @XmlElement(name = "RMBAC-Beta3Yr", required = true)
    protected String rmbacBeta3Yr;
    @XmlElement(name = "RM-StdDev3Yr", required = true)
    protected String rmStdDev3Yr;
    @XmlElement(name = "RMBAC-Alpha3Yr", required = true)
    protected String rmbacAlpha3Yr;
    @XmlElement(name = "RM-SharpeRatio3Yr", required = true)
    protected String rmSharpeRatio3Yr;
    @XmlElement(name = "RMBAC-Rsquared3Yr", required = true)
    protected String rmbacRsquared3Yr;
    @XmlElement(name = "RMBAC-Beta5Yr", required = true)
    protected String rmbacBeta5Yr;
    @XmlElement(name = "RM-StdDev5Yr", required = true)
    protected String rmStdDev5Yr;
    @XmlElement(name = "RMBAC-Alpha5Yr", required = true)
    protected String rmbacAlpha5Yr;
    @XmlElement(name = "RM-SharpeRatio5Yr", required = true)
    protected String rmSharpeRatio5Yr;
    @XmlElement(name = "RMBAC-Rsquared5Yr", required = true)
    protected String rmbacRsquared5Yr;
    @XmlElement(name = "RMBAC-Beta10Yr", required = true)
    protected String rmbacBeta10Yr;
    @XmlElement(name = "RM-StdDev10Yr", required = true)
    protected String rmStdDev10Yr;
    @XmlElement(name = "RMBAC-Alpha10Yr", required = true)
    protected String rmbacAlpha10Yr;
    @XmlElement(name = "RM-SharpeRatio10Yr", required = true)
    protected String rmSharpeRatio10Yr;
    @XmlElement(name = "RMBAC-Rsquared10Yr", required = true)
    protected String rmbacRsquared10Yr;
    @XmlElement(name = "RMBAC-CategoryBeta1Yr", required = true)
    protected String rmbacCategoryBeta1Yr;
    @XmlElement(name = "RM-CategoryStdDev1Yr", required = true)
    protected String rmCategoryStdDev1Yr;
    @XmlElement(name = "RMBAC-CategoryAlpha1Yr", required = true)
    protected String rmbacCategoryAlpha1Yr;
    @XmlElement(name = "RM-CategorySharpeRatio1Yr", required = true)
    protected String rmCategorySharpeRatio1Yr;
    @XmlElement(name = "RMBAC-CategoryRsquared1Yr", required = true)
    protected String rmbacCategoryRsquared1Yr;
    @XmlElement(name = "RMBAC-CategoryBeta3Yr", required = true)
    protected String rmbacCategoryBeta3Yr;
    @XmlElement(name = "RM-CategoryStdDev3Yr", required = true)
    protected String rmCategoryStdDev3Yr;
    @XmlElement(name = "RMBAC-CategoryAlpha3Yr", required = true)
    protected String rmbacCategoryAlpha3Yr;
    @XmlElement(name = "RM-CategorySharpeRatio3Yr", required = true)
    protected String rmCategorySharpeRatio3Yr;
    @XmlElement(name = "RMBAC-CategoryRsquared3Yr", required = true)
    protected String rmbacCategoryRsquared3Yr;
    @XmlElement(name = "RMBAC-CategoryBeta5Yr", required = true)
    protected String rmbacCategoryBeta5Yr;
    @XmlElement(name = "RM-CategoryStdDev5Yr", required = true)
    protected String rmCategoryStdDev5Yr;
    @XmlElement(name = "RMBAC-CategoryAlpha5Yr", required = true)
    protected String rmbacCategoryAlpha5Yr;
    @XmlElement(name = "RM-CategorySharpeRatio5Yr", required = true)
    protected String rmCategorySharpeRatio5Yr;
    @XmlElement(name = "RMBAC-CategoryRsquared5Yr", required = true)
    protected String rmbacCategoryRsquared5Yr;
    @XmlElement(name = "RMBAC-CategoryBeta10Yr", required = true)
    protected String rmbacCategoryBeta10Yr;
    @XmlElement(name = "RM-CategoryStdDev10Yr", required = true)
    protected String rmCategoryStdDev10Yr;
    @XmlElement(name = "RMBAC-CategoryAlpha10Yr", required = true)
    protected String rmbacCategoryAlpha10Yr;
    @XmlElement(name = "RM-CategorySharpeRatio10Yr", required = true)
    protected String rmCategorySharpeRatio10Yr;
    @XmlElement(name = "RMBAC-CategoryRsquared10Yr", required = true)
    protected String rmbacCategoryRsquared10Yr;
    @XmlElement(name = "RM-EndDate", required = true)
    protected String rmEndDate;
    @XmlElement(name = "TTRR-Rank1MthQuartileBreakpoint1", required = true)
    protected String ttrrRank1MthQuartileBreakpoint1;
    @XmlElement(name = "TTRR-Rank1MthQuartileBreakpoint25", required = true)
    protected String ttrrRank1MthQuartileBreakpoint25;
    @XmlElement(name = "TTRR-Rank1MthQuartileBreakpoint50", required = true)
    protected String ttrrRank1MthQuartileBreakpoint50;
    @XmlElement(name = "TTRR-Rank1MthQuartileBreakpoint75", required = true)
    protected String ttrrRank1MthQuartileBreakpoint75;
    @XmlElement(name = "TTRR-Rank1MthQuartileBreakpoint99", required = true)
    protected String ttrrRank1MthQuartileBreakpoint99;
    @XmlElement(name = "TTRR-Rank3MthQuartileBreakpoint1", required = true)
    protected String ttrrRank3MthQuartileBreakpoint1;
    @XmlElement(name = "TTRR-Rank3MthQuartileBreakpoint25", required = true)
    protected String ttrrRank3MthQuartileBreakpoint25;
    @XmlElement(name = "TTRR-Rank3MthQuartileBreakpoint50", required = true)
    protected String ttrrRank3MthQuartileBreakpoint50;
    @XmlElement(name = "TTRR-Rank3MthQuartileBreakpoint75", required = true)
    protected String ttrrRank3MthQuartileBreakpoint75;
    @XmlElement(name = "TTRR-Rank3MthQuartileBreakpoint99", required = true)
    protected String ttrrRank3MthQuartileBreakpoint99;
    @XmlElement(name = "TTRR-Rank6MthQuartileBreakpoint1", required = true)
    protected String ttrrRank6MthQuartileBreakpoint1;
    @XmlElement(name = "TTRR-Rank6MthQuartileBreakpoint25", required = true)
    protected String ttrrRank6MthQuartileBreakpoint25;
    @XmlElement(name = "TTRR-Rank6MthQuartileBreakpoint50", required = true)
    protected String ttrrRank6MthQuartileBreakpoint50;
    @XmlElement(name = "TTRR-Rank6MthQuartileBreakpoint75", required = true)
    protected String ttrrRank6MthQuartileBreakpoint75;
    @XmlElement(name = "TTRR-Rank6MthQuartileBreakpoint99", required = true)
    protected String ttrrRank6MthQuartileBreakpoint99;
    @XmlElement(name = "TTRR-Rank1YrQuartileBreakpoint1", required = true)
    protected String ttrrRank1YrQuartileBreakpoint1;
    @XmlElement(name = "TTRR-Rank1YrQuartileBreakpoint25", required = true)
    protected String ttrrRank1YrQuartileBreakpoint25;
    @XmlElement(name = "TTRR-Rank1YrQuartileBreakpoint50", required = true)
    protected String ttrrRank1YrQuartileBreakpoint50;
    @XmlElement(name = "TTRR-Rank1YrQuartileBreakpoint75", required = true)
    protected String ttrrRank1YrQuartileBreakpoint75;
    @XmlElement(name = "TTRR-Rank1YrQuartileBreakpoint99", required = true)
    protected String ttrrRank1YrQuartileBreakpoint99;
    @XmlElement(name = "TTRR-Rank3YrQuartileBreakpoint1", required = true)
    protected String ttrrRank3YrQuartileBreakpoint1;
    @XmlElement(name = "TTRR-Rank3YrQuartileBreakpoint25", required = true)
    protected String ttrrRank3YrQuartileBreakpoint25;
    @XmlElement(name = "TTRR-Rank3YrQuartileBreakpoint50", required = true)
    protected String ttrrRank3YrQuartileBreakpoint50;
    @XmlElement(name = "TTRR-Rank3YrQuartileBreakpoint75", required = true)
    protected String ttrrRank3YrQuartileBreakpoint75;
    @XmlElement(name = "TTRR-Rank3YrQuartileBreakpoint99", required = true)
    protected String ttrrRank3YrQuartileBreakpoint99;
    @XmlElement(name = "TTRR-Rank5YrQuartileBreakpoint1", required = true)
    protected String ttrrRank5YrQuartileBreakpoint1;
    @XmlElement(name = "TTRR-Rank5YrQuartileBreakpoint25", required = true)
    protected String ttrrRank5YrQuartileBreakpoint25;
    @XmlElement(name = "TTRR-Rank5YrQuartileBreakpoint50", required = true)
    protected String ttrrRank5YrQuartileBreakpoint50;
    @XmlElement(name = "TTRR-Rank5YrQuartileBreakpoint75", required = true)
    protected String ttrrRank5YrQuartileBreakpoint75;
    @XmlElement(name = "TTRR-Rank5YrQuartileBreakpoint99", required = true)
    protected String ttrrRank5YrQuartileBreakpoint99;
    @XmlAttribute(name = "_id")
    protected String id;

    
    public String getTTRReturn1Mth() {
        return this.ttrReturn1Mth;
    }

    
    public void setTTRReturn1Mth(final String value) {
        this.ttrReturn1Mth = value;
    }

    
    public String getTTRCategoryReturn1Mth() {
        return this.ttrCategoryReturn1Mth;
    }

    
    public void setTTRCategoryReturn1Mth(final String value) {
        this.ttrCategoryReturn1Mth = value;
    }

    
    public String getTtrrRank1MthQuartile() {
        return this.ttrrRank1MthQuartile;
    }

    
    public void setTtrrRank1MthQuartile(final String ttrrRank1MthQuartile) {
        this.ttrrRank1MthQuartile = ttrrRank1MthQuartile;
    }

    
    public String getTTRRCategorySize1Mth() {
        return this.ttrrCategorySize1Mth;
    }

    
    public void setTTRRCategorySize1Mth(final String value) {
        this.ttrrCategorySize1Mth = value;
    }

    
    public String getTTRReturn3Mth() {
        return this.ttrReturn3Mth;
    }

    
    public void setTTRReturn3Mth(final String value) {
        this.ttrReturn3Mth = value;
    }

    
    public String getTTRCategoryReturn3Mth() {
        return this.ttrCategoryReturn3Mth;
    }

    
    public void setTTRCategoryReturn3Mth(final String value) {
        this.ttrCategoryReturn3Mth = value;
    }

    
    public String getTtrrRank3MthQuartile() {
        return this.ttrrRank3MthQuartile;
    }

    
    public void setTtrrRank3MthQuartile(final String ttrrRank3MthQuartile) {
        this.ttrrRank3MthQuartile = ttrrRank3MthQuartile;
    }

    
    public String getTTRRCategorySize3Mth() {
        return this.ttrrCategorySize3Mth;
    }

    
    public void setTTRRCategorySize3Mth(final String value) {
        this.ttrrCategorySize3Mth = value;
    }

    
    public String getTTRReturn6Mth() {
        return this.ttrReturn6Mth;
    }

    
    public void setTTRReturn6Mth(final String value) {
        this.ttrReturn6Mth = value;
    }

    
    public String getTTRCategoryReturn6Mth() {
        return this.ttrCategoryReturn6Mth;
    }

    
    public void setTTRCategoryReturn6Mth(final String value) {
        this.ttrCategoryReturn6Mth = value;
    }

    
    public String getTtrrRank6MthQuartile() {
        return this.ttrrRank6MthQuartile;
    }

    
    public void setTtrrRank6MthQuartile(final String ttrrRank6MthQuartile) {
        this.ttrrRank6MthQuartile = ttrrRank6MthQuartile;
    }

    
    public String getTTRRCategorySize6Mth() {
        return this.ttrrCategorySize6Mth;
    }

    
    public void setTTRRCategorySize6Mth(final String value) {
        this.ttrrCategorySize6Mth = value;
    }

    
    public String getTTRReturn1Yr() {
        return this.ttrReturn1Yr;
    }

    
    public void setTTRReturn1Yr(final String value) {
        this.ttrReturn1Yr = value;
    }

    
    public String getTTRCategoryReturn1Yr() {
        return this.ttrCategoryReturn1Yr;
    }

    
    public void setTTRCategoryReturn1Yr(final String value) {
        this.ttrCategoryReturn1Yr = value;
    }

    
    public String getTtrrRank1YrQuartile() {
        return this.ttrrRank1YrQuartile;
    }

    
    public void setTtrrRank1YrQuartile(final String ttrrRank1YrQuartile) {
        this.ttrrRank1YrQuartile = ttrrRank1YrQuartile;
    }

    
    public String getTTRRCategorySize1Yr() {
        return this.ttrrCategorySize1Yr;
    }

    
    public void setTTRRCategorySize1Yr(final String value) {
        this.ttrrCategorySize1Yr = value;
    }

    
    public String getTTRReturn3Yr() {
        return this.ttrReturn3Yr;
    }

    
    public void setTTRReturn3Yr(final String value) {
        this.ttrReturn3Yr = value;
    }

    
    public String getTTRCategoryReturn3Yr() {
        return this.ttrCategoryReturn3Yr;
    }

    
    public void setTTRCategoryReturn3Yr(final String value) {
        this.ttrCategoryReturn3Yr = value;
    }

    
    public String getTtrrRank3YrQuartile() {
        return this.ttrrRank3YrQuartile;
    }

    
    public void setTtrrRank3YrQuartile(final String ttrrRank3YrQuartile) {
        this.ttrrRank3YrQuartile = ttrrRank3YrQuartile;
    }

    
    public String getTTRRCategorySize3Yr() {
        return this.ttrrCategorySize3Yr;
    }

    
    public void setTTRRCategorySize3Yr(final String value) {
        this.ttrrCategorySize3Yr = value;
    }

    
    public String getTTRReturn5Yr() {
        return this.ttrReturn5Yr;
    }

    
    public void setTTRReturn5Yr(final String value) {
        this.ttrReturn5Yr = value;
    }

    
    public String getTTRCategoryReturn5Yr() {
        return this.ttrCategoryReturn5Yr;
    }

    
    public void setTTRCategoryReturn5Yr(final String value) {
        this.ttrCategoryReturn5Yr = value;
    }

    
    public String getTtrrRank5YrQuartile() {
        return this.ttrrRank5YrQuartile;
    }

    
    public void setTtrrRank5YrQuartile(final String ttrrRank5YrQuartile) {
        this.ttrrRank5YrQuartile = ttrrRank5YrQuartile;
    }

    
    public String getTTRRCategorySize5Yr() {
        return this.ttrrCategorySize5Yr;
    }

    
    public void setTTRRCategorySize5Yr(final String value) {
        this.ttrrCategorySize5Yr = value;
    }

    
    public String getTTRRMonthEndDate() {
        return this.ttrrMonthEndDate;
    }

    
    public void setTTRRMonthEndDate(final String value) {
        this.ttrrMonthEndDate = value;
    }

    
    public String getMRRisk3Year() {
        return this.mrRisk3Year;
    }

    
    public void setMRRisk3Year(final String value) {
        this.mrRisk3Year = value;
    }

    
    public String getMRReturn3Year() {
        return this.mrReturn3Year;
    }

    
    public void setMRReturn3Year(final String value) {
        this.mrReturn3Year = value;
    }

    
    public String getMRRatingDate() {
        return this.mrRatingDate;
    }

    
    public void setMRRatingDate(final String value) {
        this.mrRatingDate = value;
    }

    
    public String getRMBACBeta1Yr() {
        return this.rmbacBeta1Yr;
    }

    
    public void setRMBACBeta1Yr(final String value) {
        this.rmbacBeta1Yr = value;
    }

    
    public String getRMStdDev1Yr() {
        return this.rmStdDev1Yr;
    }

    
    public void setRMStdDev1Yr(final String value) {
        this.rmStdDev1Yr = value;
    }

    
    public String getRMBACAlpha1Yr() {
        return this.rmbacAlpha1Yr;
    }

    
    public void setRMBACAlpha1Yr(final String value) {
        this.rmbacAlpha1Yr = value;
    }

    
    public String getRMSharpeRatio1Yr() {
        return this.rmSharpeRatio1Yr;
    }

    
    public void setRMSharpeRatio1Yr(final String value) {
        this.rmSharpeRatio1Yr = value;
    }

    
    public String getRMBACRsquared1Yr() {
        return this.rmbacRsquared1Yr;
    }

    
    public void setRMBACRsquared1Yr(final String value) {
        this.rmbacRsquared1Yr = value;
    }

    
    public String getRMBACBeta3Yr() {
        return this.rmbacBeta3Yr;
    }

    
    public void setRMBACBeta3Yr(final String value) {
        this.rmbacBeta3Yr = value;
    }

    
    public String getRMStdDev3Yr() {
        return this.rmStdDev3Yr;
    }

    
    public void setRMStdDev3Yr(final String value) {
        this.rmStdDev3Yr = value;
    }

    
    public String getRMBACAlpha3Yr() {
        return this.rmbacAlpha3Yr;
    }

    
    public void setRMBACAlpha3Yr(final String value) {
        this.rmbacAlpha3Yr = value;
    }

    
    public String getRMSharpeRatio3Yr() {
        return this.rmSharpeRatio3Yr;
    }

    
    public void setRMSharpeRatio3Yr(final String value) {
        this.rmSharpeRatio3Yr = value;
    }

    
    public String getRMBACRsquared3Yr() {
        return this.rmbacRsquared3Yr;
    }

    
    public void setRMBACRsquared3Yr(final String value) {
        this.rmbacRsquared3Yr = value;
    }

    
    public String getRMBACBeta5Yr() {
        return this.rmbacBeta5Yr;
    }

    
    public void setRMBACBeta5Yr(final String value) {
        this.rmbacBeta5Yr = value;
    }

    
    public String getRMStdDev5Yr() {
        return this.rmStdDev5Yr;
    }

    
    public void setRMStdDev5Yr(final String value) {
        this.rmStdDev5Yr = value;
    }

    
    public String getRMBACAlpha5Yr() {
        return this.rmbacAlpha5Yr;
    }

    
    public void setRMBACAlpha5Yr(final String value) {
        this.rmbacAlpha5Yr = value;
    }

    
    public String getRMSharpeRatio5Yr() {
        return this.rmSharpeRatio5Yr;
    }

    
    public void setRMSharpeRatio5Yr(final String value) {
        this.rmSharpeRatio5Yr = value;
    }

    
    public String getRMBACRsquared5Yr() {
        return this.rmbacRsquared5Yr;
    }

    
    public void setRMBACRsquared5Yr(final String value) {
        this.rmbacRsquared5Yr = value;
    }

    
    public String getRMBACBeta10Yr() {
        return this.rmbacBeta10Yr;
    }

    
    public void setRMBACBeta10Yr(final String value) {
        this.rmbacBeta10Yr = value;
    }

    
    public String getRMStdDev10Yr() {
        return this.rmStdDev10Yr;
    }

    
    public void setRMStdDev10Yr(final String value) {
        this.rmStdDev10Yr = value;
    }

    
    public String getRMBACAlpha10Yr() {
        return this.rmbacAlpha10Yr;
    }

    
    public void setRMBACAlpha10Yr(final String value) {
        this.rmbacAlpha10Yr = value;
    }

    
    public String getRMSharpeRatio10Yr() {
        return this.rmSharpeRatio10Yr;
    }

    
    public void setRMSharpeRatio10Yr(final String value) {
        this.rmSharpeRatio10Yr = value;
    }

    
    public String getRMBACRsquared10Yr() {
        return this.rmbacRsquared10Yr;
    }

    
    public void setRMBACRsquared10Yr(final String value) {
        this.rmbacRsquared10Yr = value;
    }

    
    public String getRMBACCategoryBeta1Yr() {
        return this.rmbacCategoryBeta1Yr;
    }

    
    public void setRMBACCategoryBeta1Yr(final String value) {
        this.rmbacCategoryBeta1Yr = value;
    }

    
    public String getRMCategoryStdDev1Yr() {
        return this.rmCategoryStdDev1Yr;
    }

    
    public void setRMCategoryStdDev1Yr(final String value) {
        this.rmCategoryStdDev1Yr = value;
    }

    
    public String getRMBACCategoryAlpha1Yr() {
        return this.rmbacCategoryAlpha1Yr;
    }

    
    public void setRMBACCategoryAlpha1Yr(final String value) {
        this.rmbacCategoryAlpha1Yr = value;
    }

    
    public String getRMCategorySharpeRatio1Yr() {
        return this.rmCategorySharpeRatio1Yr;
    }

    
    public void setRMCategorySharpeRatio1Yr(final String value) {
        this.rmCategorySharpeRatio1Yr = value;
    }

    
    public String getRMBACCategoryRsquared1Yr() {
        return this.rmbacCategoryRsquared1Yr;
    }

    
    public void setRMBACCategoryRsquared1Yr(final String value) {
        this.rmbacCategoryRsquared1Yr = value;
    }

    
    public String getRMBACCategoryBeta3Yr() {
        return this.rmbacCategoryBeta3Yr;
    }

    
    public void setRMBACCategoryBeta3Yr(final String value) {
        this.rmbacCategoryBeta3Yr = value;
    }

    
    public String getRMCategoryStdDev3Yr() {
        return this.rmCategoryStdDev3Yr;
    }

    
    public void setRMCategoryStdDev3Yr(final String value) {
        this.rmCategoryStdDev3Yr = value;
    }

    
    public String getRMBACCategoryAlpha3Yr() {
        return this.rmbacCategoryAlpha3Yr;
    }

    
    public void setRMBACCategoryAlpha3Yr(final String value) {
        this.rmbacCategoryAlpha3Yr = value;
    }

    
    public String getRMCategorySharpeRatio3Yr() {
        return this.rmCategorySharpeRatio3Yr;
    }

    
    public void setRMCategorySharpeRatio3Yr(final String value) {
        this.rmCategorySharpeRatio3Yr = value;
    }

    
    public String getRMBACCategoryRsquared3Yr() {
        return this.rmbacCategoryRsquared3Yr;
    }

    
    public void setRMBACCategoryRsquared3Yr(final String value) {
        this.rmbacCategoryRsquared3Yr = value;
    }

    
    public String getRMBACCategoryBeta5Yr() {
        return this.rmbacCategoryBeta5Yr;
    }

    
    public void setRMBACCategoryBeta5Yr(final String value) {
        this.rmbacCategoryBeta5Yr = value;
    }

    
    public String getRMCategoryStdDev5Yr() {
        return this.rmCategoryStdDev5Yr;
    }

    
    public void setRMCategoryStdDev5Yr(final String value) {
        this.rmCategoryStdDev5Yr = value;
    }

    
    public String getRMBACCategoryAlpha5Yr() {
        return this.rmbacCategoryAlpha5Yr;
    }

    
    public void setRMBACCategoryAlpha5Yr(final String value) {
        this.rmbacCategoryAlpha5Yr = value;
    }

    
    public String getRMCategorySharpeRatio5Yr() {
        return this.rmCategorySharpeRatio5Yr;
    }

    
    public void setRMCategorySharpeRatio5Yr(final String value) {
        this.rmCategorySharpeRatio5Yr = value;
    }

    
    public String getRMBACCategoryRsquared5Yr() {
        return this.rmbacCategoryRsquared5Yr;
    }

    
    public void setRMBACCategoryRsquared5Yr(final String value) {
        this.rmbacCategoryRsquared5Yr = value;
    }

    
    public String getRMBACCategoryBeta10Yr() {
        return this.rmbacCategoryBeta10Yr;
    }

    
    public void setRMBACCategoryBeta10Yr(final String value) {
        this.rmbacCategoryBeta10Yr = value;
    }

    
    public String getRMCategoryStdDev10Yr() {
        return this.rmCategoryStdDev10Yr;
    }

    
    public void setRMCategoryStdDev10Yr(final String value) {
        this.rmCategoryStdDev10Yr = value;
    }

    
    public String getRMBACCategoryAlpha10Yr() {
        return this.rmbacCategoryAlpha10Yr;
    }

    
    public void setRMBACCategoryAlpha10Yr(final String value) {
        this.rmbacCategoryAlpha10Yr = value;
    }

    
    public String getRMCategorySharpeRatio10Yr() {
        return this.rmCategorySharpeRatio10Yr;
    }

    
    public void setRMCategorySharpeRatio10Yr(final String value) {
        this.rmCategorySharpeRatio10Yr = value;
    }

    
    public String getRMBACCategoryRsquared10Yr() {
        return this.rmbacCategoryRsquared10Yr;
    }

    
    public void setRMBACCategoryRsquared10Yr(final String value) {
        this.rmbacCategoryRsquared10Yr = value;
    }

    
    public String getRmEndDate() {
        return this.rmEndDate;
    }

    
    public void setRmEndDate(final String rmEndDate) {
        this.rmEndDate = rmEndDate;
    }

    
    public String getTTRRRank1MthQuartileBreakpoint1() {
        return this.ttrrRank1MthQuartileBreakpoint1;
    }

    
    public void setTTRRRank1MthQuartileBreakpoint1(final String value) {
        this.ttrrRank1MthQuartileBreakpoint1 = value;
    }

    
    public String getTTRRRank1MthQuartileBreakpoint25() {
        return this.ttrrRank1MthQuartileBreakpoint25;
    }

    
    public void setTTRRRank1MthQuartileBreakpoint25(final String value) {
        this.ttrrRank1MthQuartileBreakpoint25 = value;
    }

    
    public String getTTRRRank1MthQuartileBreakpoint50() {
        return this.ttrrRank1MthQuartileBreakpoint50;
    }

    
    public void setTTRRRank1MthQuartileBreakpoint50(final String value) {
        this.ttrrRank1MthQuartileBreakpoint50 = value;
    }

    
    public String getTTRRRank1MthQuartileBreakpoint75() {
        return this.ttrrRank1MthQuartileBreakpoint75;
    }

    
    public void setTTRRRank1MthQuartileBreakpoint75(final String value) {
        this.ttrrRank1MthQuartileBreakpoint75 = value;
    }

    
    public String getTTRRRank1MthQuartileBreakpoint99() {
        return this.ttrrRank1MthQuartileBreakpoint99;
    }

    
    public void setTTRRRank1MthQuartileBreakpoint99(final String value) {
        this.ttrrRank1MthQuartileBreakpoint99 = value;
    }

    
    public String getTTRRRank3MthQuartileBreakpoint1() {
        return this.ttrrRank3MthQuartileBreakpoint1;
    }

    
    public void setTTRRRank3MthQuartileBreakpoint1(final String value) {
        this.ttrrRank3MthQuartileBreakpoint1 = value;
    }

    
    public String getTTRRRank3MthQuartileBreakpoint25() {
        return this.ttrrRank3MthQuartileBreakpoint25;
    }

    
    public void setTTRRRank3MthQuartileBreakpoint25(final String value) {
        this.ttrrRank3MthQuartileBreakpoint25 = value;
    }

    
    public String getTTRRRank3MthQuartileBreakpoint50() {
        return this.ttrrRank3MthQuartileBreakpoint50;
    }

    
    public void setTTRRRank3MthQuartileBreakpoint50(final String value) {
        this.ttrrRank3MthQuartileBreakpoint50 = value;
    }

    
    public String getTTRRRank3MthQuartileBreakpoint75() {
        return this.ttrrRank3MthQuartileBreakpoint75;
    }

    
    public void setTTRRRank3MthQuartileBreakpoint75(final String value) {
        this.ttrrRank3MthQuartileBreakpoint75 = value;
    }

    
    public String getTTRRRank3MthQuartileBreakpoint99() {
        return this.ttrrRank3MthQuartileBreakpoint99;
    }

    
    public void setTTRRRank3MthQuartileBreakpoint99(final String value) {
        this.ttrrRank3MthQuartileBreakpoint99 = value;
    }

    
    public String getTTRRRank6MthQuartileBreakpoint1() {
        return this.ttrrRank6MthQuartileBreakpoint1;
    }

    
    public void setTTRRRank6MthQuartileBreakpoint1(final String value) {
        this.ttrrRank6MthQuartileBreakpoint1 = value;
    }

    
    public String getTTRRRank6MthQuartileBreakpoint25() {
        return this.ttrrRank6MthQuartileBreakpoint25;
    }

    
    public void setTTRRRank6MthQuartileBreakpoint25(final String value) {
        this.ttrrRank6MthQuartileBreakpoint25 = value;
    }

    
    public String getTTRRRank6MthQuartileBreakpoint50() {
        return this.ttrrRank6MthQuartileBreakpoint50;
    }

    
    public void setTTRRRank6MthQuartileBreakpoint50(final String value) {
        this.ttrrRank6MthQuartileBreakpoint50 = value;
    }

    
    public String getTTRRRank6MthQuartileBreakpoint75() {
        return this.ttrrRank6MthQuartileBreakpoint75;
    }

    
    public void setTTRRRank6MthQuartileBreakpoint75(final String value) {
        this.ttrrRank6MthQuartileBreakpoint75 = value;
    }

    
    public String getTTRRRank6MthQuartileBreakpoint99() {
        return this.ttrrRank6MthQuartileBreakpoint99;
    }

    
    public void setTTRRRank6MthQuartileBreakpoint99(final String value) {
        this.ttrrRank6MthQuartileBreakpoint99 = value;
    }

    
    public String getTTRRRank1YrQuartileBreakpoint1() {
        return this.ttrrRank1YrQuartileBreakpoint1;
    }

    
    public void setTTRRRank1YrQuartileBreakpoint1(final String value) {
        this.ttrrRank1YrQuartileBreakpoint1 = value;
    }

    
    public String getTTRRRank1YrQuartileBreakpoint25() {
        return this.ttrrRank1YrQuartileBreakpoint25;
    }

    
    public void setTTRRRank1YrQuartileBreakpoint25(final String value) {
        this.ttrrRank1YrQuartileBreakpoint25 = value;
    }

    
    public String getTTRRRank1YrQuartileBreakpoint50() {
        return this.ttrrRank1YrQuartileBreakpoint50;
    }

    
    public void setTTRRRank1YrQuartileBreakpoint50(final String value) {
        this.ttrrRank1YrQuartileBreakpoint50 = value;
    }

    
    public String getTTRRRank1YrQuartileBreakpoint75() {
        return this.ttrrRank1YrQuartileBreakpoint75;
    }

    
    public void setTTRRRank1YrQuartileBreakpoint75(final String value) {
        this.ttrrRank1YrQuartileBreakpoint75 = value;
    }

    
    public String getTTRRRank1YrQuartileBreakpoint99() {
        return this.ttrrRank1YrQuartileBreakpoint99;
    }

    
    public void setTTRRRank1YrQuartileBreakpoint99(final String value) {
        this.ttrrRank1YrQuartileBreakpoint99 = value;
    }

    
    public String getTTRRRank3YrQuartileBreakpoint1() {
        return this.ttrrRank3YrQuartileBreakpoint1;
    }

    
    public void setTTRRRank3YrQuartileBreakpoint1(final String value) {
        this.ttrrRank3YrQuartileBreakpoint1 = value;
    }

    
    public String getTTRRRank3YrQuartileBreakpoint25() {
        return this.ttrrRank3YrQuartileBreakpoint25;
    }

    
    public void setTTRRRank3YrQuartileBreakpoint25(final String value) {
        this.ttrrRank3YrQuartileBreakpoint25 = value;
    }

    
    public String getTTRRRank3YrQuartileBreakpoint50() {
        return this.ttrrRank3YrQuartileBreakpoint50;
    }

    
    public void setTTRRRank3YrQuartileBreakpoint50(final String value) {
        this.ttrrRank3YrQuartileBreakpoint50 = value;
    }

    
    public String getTTRRRank3YrQuartileBreakpoint75() {
        return this.ttrrRank3YrQuartileBreakpoint75;
    }

    
    public void setTTRRRank3YrQuartileBreakpoint75(final String value) {
        this.ttrrRank3YrQuartileBreakpoint75 = value;
    }

    
    public String getTTRRRank3YrQuartileBreakpoint99() {
        return this.ttrrRank3YrQuartileBreakpoint99;
    }

    
    public void setTTRRRank3YrQuartileBreakpoint99(final String value) {
        this.ttrrRank3YrQuartileBreakpoint99 = value;
    }

    
    public String getTTRRRank5YrQuartileBreakpoint1() {
        return this.ttrrRank5YrQuartileBreakpoint1;
    }

    
    public void setTTRRRank5YrQuartileBreakpoint1(final String value) {
        this.ttrrRank5YrQuartileBreakpoint1 = value;
    }

    
    public String getTTRRRank5YrQuartileBreakpoint25() {
        return this.ttrrRank5YrQuartileBreakpoint25;
    }

    
    public void setTTRRRank5YrQuartileBreakpoint25(final String value) {
        this.ttrrRank5YrQuartileBreakpoint25 = value;
    }

    
    public String getTTRRRank5YrQuartileBreakpoint50() {
        return this.ttrrRank5YrQuartileBreakpoint50;
    }

    
    public void setTTRRRank5YrQuartileBreakpoint50(final String value) {
        this.ttrrRank5YrQuartileBreakpoint50 = value;
    }

    
    public String getTTRRRank5YrQuartileBreakpoint75() {
        return this.ttrrRank5YrQuartileBreakpoint75;
    }

    
    public void setTTRRRank5YrQuartileBreakpoint75(final String value) {
        this.ttrrRank5YrQuartileBreakpoint75 = value;
    }

    
    public String getTTRRRank5YrQuartileBreakpoint99() {
        return this.ttrrRank5YrQuartileBreakpoint99;
    }

    
    public void setTTRRRank5YrQuartileBreakpoint99(final String value) {
        this.ttrrRank5YrQuartileBreakpoint99 = value;
    }

    
    public String getId() {
        return this.id;
    }

    
    public void setId(final String value) {
        this.id = value;
    }

}
