//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.05 at 09:48:11 AM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.returnIndexChart;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "r")
public class R {

    @XmlAttribute(name = "y")
    protected String y;
    @XmlAttribute(name = "m")
    protected String m;
    @XmlAttribute(name = "v")
    protected String v;

    
    public String getY() {
        return this.y;
    }

    
    public void setY(final String y) {
        this.y = y;
    }

    
    public String getM() {
        return this.m;
    }

    
    public void setM(final String m) {
        this.m = m;
    }

    
    public String getV() {
        return this.v;
    }

    
    public void setV(final String value) {
        this.v = value;
    }

}
