//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.17 at 02:49:04 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.toptenholdings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"t10HHoldings", "psrpPortfolioDate", "psPortfolioCurrencyId"})
@XmlRootElement(name = "api")
public class Api {

    @XmlElement(name = "T10H-Holdings", required = true)
    protected T10HHoldings t10HHoldings;
    @XmlElement(name = "PSRP-PortfolioDate", required = true)
    protected String psrpPortfolioDate;
    @XmlElement(name = "PS-PortfolioCurrencyId")
    protected String psPortfolioCurrencyId;
    @XmlAttribute(name = "_id")
    protected String id;


    public T10HHoldings getT10HHoldings() {
        return this.t10HHoldings;
    }


    public void setT10HHoldings(final T10HHoldings value) {
        this.t10HHoldings = value;
    }


    public String getPSRPPortfolioDate() {
        return this.psrpPortfolioDate;
    }


    public void setPSRPPortfolioDate(final String value) {
        this.psrpPortfolioDate = value;
    }


    public String getPsPortfolioCurrencyId() {
        return this.psPortfolioCurrencyId;
    }


    public void setPsPortfolioCurrencyId(final String psPortfolioCurrencyId) {
        this.psPortfolioCurrencyId = psPortfolioCurrencyId;
    }


    public String getId() {
        return this.id;
    }


    public void setId(final String value) {
        this.id = value;
    }

}
