//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.31 at 04:20:02 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.toptenholdings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"countryId", "holdingType", "ticker", "name", "weighting", "currencyId", "marketValue"})
@XmlRootElement(name = "HoldingDetail")
public class HoldingDetail {

    @XmlElement(name = "CountryId", required = true)
    protected String countryId;
    @XmlElement(name = "HoldingType", required = true)
    protected String holdingType;
    @XmlElement(name = "Ticker", required = true)
    protected String ticker;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Weighting", required = true)
    protected String weighting;
    @XmlElement(name = "CurrencyId", required = true)
    protected String currencyId;
    @XmlElement(name = "MarketValue", required = true)
    protected String marketValue;


    public String getCountryId() {
        return this.countryId;
    }


    public void setCountryId(final String value) {
        this.countryId = value;
    }


    public String getHoldingType() {
        return this.holdingType;
    }


    public void setHoldingType(final String value) {
        this.holdingType = value;
    }


    public String getTicker() {
        return this.ticker;
    }


    public void setTicker(final String value) {
        this.ticker = value;
    }


    public String getName() {
        return this.name;
    }


    public void setName(final String value) {
        this.name = value;
    }


    public String getWeighting() {
        return this.weighting;
    }


    public void setWeighting(final String value) {
        this.weighting = value;
    }


    public String getCurrencyId() {
        return this.currencyId;
    }


    public void setCurrencyId(final String value) {
        this.currencyId = value;
    }


    public String getMarketValue() {
        return this.marketValue;
    }


    public void setMarketValue(final String value) {
        this.marketValue = value;
    }

}
