//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.17 at 02:49:04 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.toptenholdings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.hhhh.group.secwealth.mktdata.fund.beans.mstar.ResponseData;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "response")
public class TopTenHoldingsData extends ResponseData {

    @XmlElement(required = true)
    protected Data data;

    public Data getData() {
        return this.data;
    }


    public void setData(final Data value) {
        this.data = value;
    }

}
