# noinspection GraphQLUnresolvedReference
query productByFilter($filter: JSON!, $sort: JSON, $limit: Int, $skip: Int = 0, $projection: Boolean = true) {
    productByFilter(filter: $filter, sort: $sort, limit: $limit, skip: $skip, projection: $projection) {
        ctryRecCde
        grpMembrRecCde
        prodId
        prodTypeCde
        prodSubtpCde
        prodAltPrimNum
        prodStatCde
        allowBuyProdInd
        allowSellProdInd
        allowSwInProdInd
        allowSwOutProdInd
        allowSellMipProdInd
        prodName
        prodMturDt
        prodLnchDt
        eqtyLinkInvst {
            lnchProdInd
            trdDt
            setlDt
        }
        strucInvstDepst {
            mktEndDt
        }
    }
}
