//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.12 at 02:41:15 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.fundlist;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"fm2Managers", "manager"})
@XmlRootElement(name = "FM2-Managers")
public class FM2Managers {

    @XmlElement(name = "FM2-Managers")
    protected FM2Managers fm2Managers;
    @XmlElement(name = "Manager")
    protected List<Manager> manager;



    public FM2Managers getFm2Managers() {
        return this.fm2Managers;
    }



    public void setFm2Managers(final FM2Managers fm2Managers) {
        this.fm2Managers = fm2Managers;
    }



    public List<Manager> getManager() {
        if (this.manager == null) {
            this.manager = new ArrayList<Manager>();
        }
        return this.manager;
    }

}
