//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.12 at 02:41:15 PM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.fundlist;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"fmManagers", "manager"})
@XmlRootElement(name = "FM-Managers")
public class FMManagers {

    @XmlElement(name = "FM-Managers")
    protected FMManagers fmManagers;
    @XmlElement(name = "Manager")
    protected List<Manager> manager;

    
    public FMManagers getFMManagers() {
        return this.fmManagers;
    }

    
    public void setFMManagers(final FMManagers value) {
        this.fmManagers = value;
    }

    
    public List<Manager> getManager() {
        if (this.manager == null) {
            this.manager = new ArrayList<Manager>();
        }
        return this.manager;
    }

}
