//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.12.12 at 10:43:42 AM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.fundlist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"managerId", "name", "role", "display", "startDate", "tenure"})
@XmlRootElement(name = "Manager")
public class Manager {

    @XmlElement(name = "ManagerId", required = true)
    protected String managerId;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Role", required = true)
    protected String role;
    @XmlElement(name = "Display", required = true)
    protected String display;
    @XmlElement(name = "StartDate", required = true)
    protected String startDate;
    @XmlElement(name = "Tenure", required = true)
    protected String tenure;


    public String getManagerId() {
        return this.managerId;
    }


    public void setManagerId(final String value) {
        this.managerId = value;
    }


    public String getName() {
        return this.name;
    }


    public void setName(final String value) {
        this.name = value;
    }


    public String getRole() {
        return this.role;
    }


    public void setRole(final String value) {
        this.role = value;
    }


    public String getDisplay() {
        return this.display;
    }


    public void setDisplay(final String value) {
        this.display = value;
    }


    public String getStartDate() {
        return this.startDate;
    }


    public void setStartDate(final String value) {
        this.startDate = value;
    }


    public String getTenure() {
        return this.tenure;
    }


    public void setTenure(final String value) {
        this.tenure = value;
    }

}
