//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vIBM 2.2.3-03/09/2011 06:46 PM(foreman)-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.10.12 at 10:43:42 AM CST
//


package com.hhhh.group.secwealth.mktdata.fund.beans.mstar.fundlist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"narrativeLanguageId", "narrativeLanguageName", "investmentStrategy"})
@XmlRootElement(name = "MultilingualStrategy")
public class MultilingualStrategy {

    @XmlElement(name = "NarrativeLanguageId", required = true)
    protected String narrativeLanguageId;
    @XmlElement(name = "NarrativeLanguageName", required = true)
    protected String narrativeLanguageName;
    @XmlElement(name = "InvestmentStrategy", required = true)
    protected String investmentStrategy;


    public String getNarrativeLanguageId() {
        return this.narrativeLanguageId;
    }


    public void setNarrativeLanguageId(final String value) {
        this.narrativeLanguageId = value;
    }


    public String getNarrativeLanguageName() {
        return this.narrativeLanguageName;
    }


    public void setNarrativeLanguageName(final String value) {
        this.narrativeLanguageName = value;
    }


    public String getInvestmentStrategy() {
        return this.investmentStrategy;
    }


    public void setInvestmentStrategy(final String value) {
        this.investmentStrategy = value;
    }

}
