# Spring Boot PostgreSQL + pgvector 配置示例

spring:
  datasource:
    # PostgreSQL数据源配置
    url: jdbc:postgresql://localhost:5432/nl2sql
    username: nl2sql_user
    password: nl2sql_pass
    driver-class-name: org.postgresql.Driver
    
    # 连接池配置 (HikariCP)
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      
  jpa:
    # JPA配置
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # 生产环境建议使用validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  # AI配置 (Spring AI)
  ai:
    vectorstore:
      pgvector:
        # pgvector配置
        index-type: HNSW  # 或者 IVFFLAT
        distance-type: COSINE_DISTANCE  # 或者 EUCLIDEAN_DISTANCE, INNER_PRODUCT
        dimensions: 1536  # OpenAI embedding维度
        
# 应用配置
app:
  vector:
    # 向量搜索配置
    similarity-threshold: 0.8
    max-results: 10
    embedding-model: text-embedding-ada-002
    
  database:
    # 数据库特定配置
    schema: public
    vector-table: document_embeddings
    employee-table: employees
    
# 日志配置
logging:
  level:
    org.springframework.ai: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    
# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
